### ISSUE TITLE
Isaac: Up Special

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#1]
Isaac's Up Special needs to be completed.

> Animation
> Damage/ knockback
> Effects

**Comment by ghost** [comment]
You could also just make it similar to Mewtwo's up b, which has no damage or KB. The animation definitely needs to be less choppy, and grounded up b does nothing except spin Isaac around.

**Comment by RikiDVX** [comment]
Isaac's grounded up special isn't doing it's full animation. Here is what it's supposed to look like. http://i.imgur.com/ri811vk.gifv

Also, I believe Isaac's up special in the air is supposed to summon a rock that acts as a spring for him to jump off of. The rock article can be found in his .pac file. (http://i.imgur.com/hraaGBC.png) It has one animation of it appearing. (http://i.imgur.com/zD5TtWQ.gifv) The animation lasts 62 frames with the rock disappearing on frame 27. In Isaac's aerial up special, he can be seen entering his airborne state at frame 27.

**Comment by TheSmashBoy** [comment]
U.N Owen has him pretty much more complete than the current build. It's not perfect as it still has his glitchy attacks that has him glitch the screen occasionally, but it is comparatively more polished than the current one we have.
