### ISSUE TITLE
Knuckles: Side Taunt

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#10]
Knuckles's Side Taunt is still Sonic's

Suggested Fix:
Replace taunt with something else, preferably an animation from a game he is in

Knuckles says "Bring it on!", so an animation where Knuckles does something tough would be good here. Something similar to Ganondorf's side taunt where he punches his open palm and cracks his knuckles would work well here.

(Perhaps he could flex his muscles, as he is known to prefer, rather than chucking?)

**Comment by ghost** [comment]
I made a MotionEtc file for Knuckles, with side taunt, down taunt, intro, lose, and win animations being fixed up versions from an older Knuckles PSA, with fixes for the dreads to work properly for the new model.

https://www.cubbyusercontent.com/pli/FitKnucklesMotionEtc+-+Copy.pac/_1e38de405dd348678617b75c427e3d38

**Comment by bb010g** [comment]
@Rage17 Could you PR those for easier testing?

**Comment by ghost** [comment]
I cant seem to figure out how to PR them. Also, the file is just the whole MotionEtc, so if someone downloads it, they can just replace Knuckles' existing one in their copy of the build.

**Comment by bb010g** [comment]
GitHub has a nice tutorial on [forking](https://help.github.com/articles/fork-a-repo/) and a [Git cheat sheet](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf). Basically, just fork, branch if you want, commit your changes, and on your branch's GitHub page, click "Pull request". It may seem a bit odd the first time, but it's pretty quick afterwards.

**Comment by ewmb7701** [comment]
Did you get permission from the original Knuckles PSA creator creator if it was okay to use these animations? I'd prefer if we ask before using resources.

**Comment by ghost** [comment]
The creators of the original PSA are inactive. The animations are from this Knuckles PSA in particular: http://forums.kc-mm.com/Gallery/BrawlView.php?Number=36398

**Comment by ewmb7701** [comment]
Taunts added. Closing.
