### ISSUE TITLE
De syncs.

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#102]
3.6 had a wifi problem where alot of stages would desync because alternate  stage loader would load the players into different versions. For example one person would be on Pokemon stadium 1 while the other on pokemon stadium 2. Later on someone found out if both players pick a new costume that was added the stages wouldnt desync. It had something to do with the stages and the new costumes being in the same slot or something like that. Is there anyway this could be addressed?

**Comment by ewmb7701** [comment]
It's possible to fix, but I'm not sure how. ASL might be removed for the WiFi build.
