### ISSUE TITLE
Menu Music Stops for a 1-2 Seconds

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#104]
When I been on the Menu the music kind of stops for like 1-2 seconds and then plays from where it left off specially the PM theme.
(PS why is there an optional fighters folder?)

**Comment by ghost** [comment]
3.6 versions of the fighters are in there I believe.

**Comment by Darquezze** [comment]
@Rage17 so that means Brawls versions are there? I'm sorry I'm just really confused

**Comment by ghost** [comment]
no, Project M 3.6. Aka the last version that the official dev team for PM released, before their own updated versions were leaked to us.

**Comment by Darquezze** [comment]
I haven't noticed any moveset difference in 3.6 and this version unless there just bug fixes

**Comment by ghost** [comment]
https://github.com/TheOriginalSINe/Project-M-CC/blob/master/3.61%20Changelist.png

**Comment by ghost** [comment]
Changelist from the front page

**Comment by Darquezze** [comment]
Says "Too big to show, sorry"

**Comment by Darquezze** [comment]
Never mind

**Comment by ewmb7701** [comment]
This is probably an issue on your end. I recommend reformatting your SD card before installing again. Closing issue.
