### ISSUE TITLE
Lyn: Spot Dodge Animation

### ISSUE THREAD

**Issue by JCOnyx** [TheOriginalSINe/Project-M-CC#106]
Just a small thing I realized.  When Lyn spot dodges she sorta stabs herself right through her chest, should probably touch up the animation a little to avoid that lol.

**Comment by ghost** [comment]
Her model has a number of clipping issues on a few moves in addition to this. When I can test later tonight I'll open issues for them.

Some of these may be things we will have to deal with though. Even 3.6 characters have some clipping on moves.

**Comment by bb010g** [comment]
Subsumed by #305
