### ISSUE TITLE
New Build booting brawl

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#107]
New build is booting brawl up for me regardless of gct.

**Comment by bb010g** [comment]
How are you loading, what platform, try a SD reformat.

**Comment by oXMugetsuoXo** [comment]
Loading hackless. Reverted to an old build and it worked fine so don't think its the SD card

**Comment by North101** [comment]
I have the same issue. If I load 3.6, 3.61 leak or the dev leak it launches PM just fine. I'm using Dolphin Build 4.0-8319 on OSX. I launch PM via Geko. 

Using the latest build it boots into Brawl. Still using the latest build, if I replace just RSBE01.gct with the one from this [commit](https://github.com/TheOriginalSINe/Project-M-CC/commit/3f2724062daa1316489e45e0757de124c6169aa1) then it will boot into PM again. Any later version of that file and it will boot into Brawl.

**Comment by ewmb7701** [comment]
Have you two tried using the latest codeset? I was having a few issues before with the codeset.

**Comment by oXMugetsuoXo** [comment]
Yes this happens with both of the new codesets

**Comment by ewmb7701** [comment]
That's very strange, as we have confirmation that it is working for other people with similar setups. What hooktype are you guys using?

**Comment by North101** [comment]
I was using VBI hooks. Tried default hook type and it booted into Brawl. Tried messing about with various settings it booted into PM but with Dolphin errors and hanging on load. Tried with a completely clean copy (including removing config.dat), didn't change any Gecko settings and it ended up working.

**Comment by oXMugetsuoXo** [comment]
@TheOriginalSINe VBI @North101 By clean copy did you mean fresh download? No settings changed just removed config?

**Comment by North101** [comment]
@oXMugetsuoXo By clean copy I mean remove all files from sd card and get the latest build from here. I only copied codes/, gameconfig.txt and projectm/ over to the sd card, but the other files shouldn't affect anything. In gecko I leave everything as default (I don't even create the gecko config.dat file) and launch the game.

**Comment by oXMugetsuoXo** [comment]
Alright thnx ill redo everything fresh. Hope this works.

**Comment by oXMugetsuoXo** [comment]
Good to go now guys thnx. Not sure why it didnt work before when i did the same thing. Going to go ahead and close this.
