### ISSUE TITLE
Jigglypuff: Headband not using proper physics

### ISSUE THREAD

**Issue by ArtfulHobbes** [TheOriginalSINe/Project-M-CC#108]
In the latest build, Headband Jigglypuff does not have movement on her headband. Perhaps a different model was used in this update?

**Comment by ghost** [comment]
The model is the same, @TheOriginalSINe seems to have accidentally removed the Havok physics data from Jigglypuff's MotionEtc file. As Jiggs' only change from 3.6 to here was the headband costume, we just have to grab that MotionEtc from one of the leaks again.
