### ISSUE TITLE
Lyn: Side Taunt and Up Taunt

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#11]
Lyn's Side Taunt and Up Taunt are the same

Suggested Fix:
Change Lyn's side taunt to something else

I'm not sure what to put here, because I don't play Fire Emblem. I think something smug or dismissive might work, but I don't know Lyn's character.

**Comment by YunSF** [comment]
Excerpt from Lyn's page on FE wiki:

"From her humble origins in the plains, Lyn has been noted as a deep, caring, and kind-hearted soul. She rarely thinks ill of others and, despite the circumstances, always believes on the best of things."

**Comment by ewmb7701** [comment]
Hmm well then I'm not sure what to do then. Any ideas?

**Comment by ghost** [comment]
Perhaps you could add in one of her battle quotes:

https://fireemblemwiki.org/wiki/Lyn#Battle_quotes

**Comment by ewmb7701** [comment]
Hmm, we'd have to find a voice actor if we were going to do that. I like the idea tho. My friend suggested we use part of her "Shadowstep Critical Attack" animation for it.

**Comment by ghost** [comment]
Right now I'm trying to see if Lyn actually said anything, so then we could have one of her voice clips. However, it's taking me a long time, since I don't play FE.

**Comment by cobalt-blue** [comment]
Lyn has never had a VA

i'd suggest re doing her voice-clips entirely with a character's soundbank from something like dynasty warriors

hell, she was the first english lord. it wouldn't hurt for her to speak english.

**Comment by ghost** [comment]
I heard on a reddit thread that she had a sound clip in the Japanese version when you use her assist trophy. Perhaps that could be used.

**Comment by cobalt-blue** [comment]
oh wow, I completely spaced on that.

i mean, i suppose.

her assist trophy also has one in the english version, but it's generally agreed to be a really bad and unfitting match on her (rather deep and mature sounding for her age). 

https://youtu.be/p3G-kTCMoAc?t=4m25s

**Comment by ghost** [comment]
A Japanese one wouldn't be that out of place either, since Marth has his Melee taunt, which has Japanese voice.

**Comment by cobalt-blue** [comment]
fair enough, I just think the significance of her being the first lord in the first english release of the series is something that shouldn't be overlooked. at the time of brawl, Marth was still japan only FE too.

 i mean, in addition, Ike's not in japanese.

**Comment by bb010g** [comment]
Subsumed by #305
