### ISSUE TITLE
Stages from the Netplay Build

### ISSUE THREAD

**Issue by JackpotSHUnited** [TheOriginalSINe/Project-M-CC#111]
Even though the netplay build of Project M 3.6 doesn't qualify as an official release, I'm pretty sure its usage was supported by the former PMDT. I don't see why the new stages couldn't be added to the Community Completion build, just as little bonuses. The following proposal adds the netplay-exclusive stages, as well as fixes the complication involving the Pokemon Stadium slots. However, in order for the R button to work with the ASL, we would have to disable the ability to flip between stage pages with the R button.

BRIDGE OF ELDIN:
Hyrule Castle HD (A)
Bridge of Eldin (L)
Rebalanced Bridge of Eldin (R)
Hyrule Castle 64 (Z)

THE SUMMIT:
Infinite Glacier (A)
The Summit (L)
Rebalanced Summit (R)

SHADOW MOSES ISLAND:
Rebalanced Shadow Moses (A)
Shadow Moses Island (L)

POKEMON STADIUM 2:
Pokemon Stadium 2 (Project M) (A)
Pokemon Stadium 2 (Brawl) (L)

POKEMON STADIUM 1:
Pokemon Stadium (Sandfall) (A)
Pokemon Stadium (Melee) (L)

GREEN GREENS:
Dream Land HD (A)
Green Greens (L)
Dream Land 64 (Z)

GREEN HILL ZONE:
Green Hill Zone (Project M) (A)
Sky Sanctuary Zone (R)
Green Hill Zone (Brawl) (L)

WARIOWARE:
Wario Land (A)
WarioWare (Brawl) (L)
WarioWare (Project M) (Z)

NORFAIR:
Metroid Lab (A)
Norfair (Brawl) (L)
Norfair (Project M) (Z)

SMASHVILLE:
Oceanville (A)
Smashville (L)

BATTLEFIELD:
Battlefield (Melee) (A)
Battlefield (Brawl) (L)

As for where Saffron City should go, I suggest doing one of these:

JUNGLE JAPES:
Rebalanced Kongo Jungle (A)
Jungle Japes (L)
Kongo Jungle 64 (Z)

75M:
Saffron City HD (A)
Saffron City 64 (L)

SPEAR PILLAR:
Spear Pillar (A)

OR

SPEAR PILLAR:
Saffron City HD (A)
Spear Pillar (L)
Saffron City 64 (Z)

75M:
Rebalanced Kongo Jungle (A)
Kongo Jungle 64 (L)

JUNGLE JAPES:
Jungle Japes (A)

**Comment by TheGreenSlime** [comment]
Instead of R couldn't it be binded to Y or X? I think a few custom builds I played did that. Plus I'm not sure but I feel like having to hold down R could interfere when selecting Wario Man/Giga Bowser/SoPo

**Comment by JackpotSHUnited** [comment]
Y and X are used for stage striking in tournaments, and unlike page-swapping, there's no other way to do that without those buttons. And I'm pretty sure the alt-characters are locked in once you get to the stage select screen, you can let go after you hit start the first time from the character select screen.

**Comment by TheGreenSlime** [comment]
Ah damn I didn't think about that, good point. And yes that sounds right, I'll test it later but I'm sure you're correct on that. I'll delete my previous post to prevent any confusion.

**Comment by ghost** [comment]
They mentioned before that they weren't going to add in the Netplay stages, so why should we? You could, of course, do it for your own personal build after this is complete, but it doesn't deserve a place in the build.

**Comment by ghost** [comment]
@bb010g I imagine that we aren't adding in the Netplay stages, in which case this should get closed.
