### ISSUE TITLE
Completing Sami

### ISSUE THREAD

**Issue by ChronoBound** [TheOriginalSINe/Project-M-CC#112]
The consensus overall seems to be that Sami does not need to be finished or should be thrown to the backburner since unlike the other three Project newcomers, not only is she lacking a slot and character palette swaps, but also is by the far the cloniest. 

However, keep in mind that the Project M team always had Sami in mind as a Snake clone. Here is an excerpt from the Project M developer that helped work on Sami:
"We conceptualized her as a Snake clone who would use projectiles less for traps, and more to snuff approaches and earn openings in close-quarters combat. "

Sami was never supposed to be a completely unique fighter like the other three were. Indeed, the Project M team has gone on the record to say clones do have merit with the Clone Engine in terms of time resources and effort.
"We've estimated that creating all new animations for a character that live up to our quality standards would take at least 700 hours. This is why clones or partial clones are so appealing – by limiting the number of new animations created it cuts down the amount of time required substantially."

They said Roy took less than half that time (700 hours) to make. 

By simply making Sami a luigi-fied clone she makes herself a much more feasible character to complete than Isaac currently (who genuinely needs to be an unique characters and seems buggier than Sami does currently, neutral b not withstanding).

The Project M team had a far more complete build of Sami than what was available in the leaked dev build:
https://www.youtube.com/watch?v=HvSxLZKvtnU

As can be seen, she has a working grenade launcher (likely what her neutral b in the leaked dev build should be), as well as a couple more different A-moves that she does not have in the leaked dev build. 

By simply giving Sami a few different animations/moves and differing stats (weight, power, fall speed, speed) she becomes a much more feasible character to complete. She should not be held to the same standard as Isaac because the clear intention behind Sami was always for her to be a Snake clone. 

How much of a Snake clone she ends up being is for this team to decide though. Realistically, she would be fine with just her differing specials (the side b machine gun fire, the neutral b grenade launcher, the bombing target down b, and really only need a newly designed up b/recovery), and a few different A-moves. Returning Melee clones, Falco, Ganondorf, and Roy, only have a few differing A-moves from Fox, Captain Falcon, and Marth, so this would not be out of place.

The Advance Wars/Famicom Wars series is perhaps the longest running Nintendo franchise that has yet to gain any notable representation in Smash Bros. The series started in 1988, two years before Fire Emblem (both series are made and developed by Intelligent Systems). Intelligent Systems has made six games in this series to date as well. 

The Project M team clearly thought Sami was a worthy addition despite their intentions on her being a clone. Her intentional clone status should make efforts to complete her much more feasible than originally believed, and at the very least probably is closer to completion in terms of her actual moveset than Isaac as it currently stands.

I think Sami, much like other clones, can present a fresh interesting take on already existing moveset, while taking at least half the effort to make than a wholly original character.

Please feel free to contribute any ideas regarding whether developing Sami as a luigi-fied Snake clone would be the proper design route for her, or any other possible thoughts or ideas pertaining to Sami.

**Comment by JackpotSHUnited** [comment]
Perhaps she could receive some of Brawl Snake's moves that didn't make the cut in Project M, such as his old up-tilt, side-smash, and something similar to the Nikita.

**Comment by ChronoBound** [comment]
Yeah, considering that Project M Snake ditched many of his vanilla Brawl moves, Sami could definitely pick up many of them (which she currently has in the dev build such as the up-tilt and forward Smash) to serve to keep her different from Snake. 

I do prefer the side b she has in the dev build over vanilla Brawl's Nikita, though. Her neutral B in the dev build does not work properly though. It is supposed to be a grenade launcher, with the linked video in the opening post showing how they intended for this special move to operate.

**Comment by jojmaht** [comment]
This would be better suited in #18.
Nevertheless, I agree with your ideas.

**Comment by ghost** [comment]
As it is, finishing Knuckles and Lyn will already take a rather large amount of time, and these are for characters who are about 80-90% done. Finishing Issac and Sammi are monstrously larger tasks and have therefor been relegated to being worked on after the "release" of this build.

One major design goal is sticking as close to PMDT design as possible. For knuckles this is easy, his moveset is complete. For Lyn, it is a bit more difficult as her moveset is partially unfinished, but we have an old build which we can reference/utilize to finish her while still sticking to using PMDT's work.

Issac and Sammi however would require a large amount of "OC" work. When they are complete, they would fall more under the category of "brawlvault style mod" than the completion of PMDT work. Also, seeing as we aren't PMDT and lack a number of their tools, just finishing these characters will take a huge amount of time, and this isn't even to mention the time burned by endless arguing of how they should be made.

That leads me to categorize them as outside the scope of the main project.

**Comment by ChronoBound** [comment]
The point is that Sami is a much more feasible character to complete than Isaac because the intention for her is simply to be a Snake clone. We also have a leaked video of a more complete Sami to get an idea on what other moves they were considering on using for Sami. As it is, Sami is already a luigi-fied Snake clone since many of Snake's A-moves have been changed in Project M, and she has a few moves herself that neither vanilla Brawl Snake or Project M Snake have.

**Comment by cobalt-blue** [comment]
I was playing with the moveset she has in the current build. with her tweaked air attacks and the old snake attacks that are on her, she feels like Snake's "Roy", so to speak as is, and in my opinion only needs -

-dash attack needs to just look better in general
-a fixed upsmash
-a working up B (just like, a modified cypher - "something Andy built for her", or something, ect.)
-a working neutral B (perhaps even just pulling this back to Snake's grenades, just weaker and multi hitting ala Toon Link and Link's bombs)
-side b tweaked for maybe, like, 3 bursts before it needs "reloading"
-all assets changed from their placeholders and made appropriate to her AW art
-expressions
-scaled to be smaller than snake?
-vocal assets

I agree with Chrono that she's easily much more "complete" than Isaac, it's just whatever is needed to make her appear on the CSS is  missing.

**Comment by ghost** [comment]
Even if she is more "complete" than Issac, neither are complete enough to be finished without large amounts of creative license.

This is what separates them from Lyn and Knuckles.

**Comment by ChronoBound** [comment]
I am not saying she is in the same tier as Knuckles and Lyn, who are 80-90% complete, albeit unpolished (especially the latter). 

However, she certainly would be a much more feasible project to finish for fans than Isaac as it stands. Isaac is mentioned as a character to finish down the line, while Sami on the other hand is nearly often overlooked. Isaac is certainly an extremely popular character, but overall he would probably rank as the most difficult of the four to finish, especially to get on a level on par with the other four Clone Engine characters (Mewtwo, Roy, Knuckles, and Lyn).

 Sami at least has the vantage point of being able to utilize many of Snake's animations of moves for her own moveset. We also have a video reference for what a more complete build of Sami might take, whereas Isaac looks roughly the same in that video as he does in the dev build so any developers would have to utilize their own imagination and ideas for what Project M tier Isaac would play like and what his moves would be, which might prove to be quite daunting.

However, I do concur that Sami does not compare to Lyn and especially Knuckles in terms of completion, and what is workable with only a few hands on deck. However, her status as being a Snake clone at least makes her possible for a level of completion that might be approachable to Project M's Roy, or if not, the quality of some the top-tier PSA's out there.

**Comment by bb010g** [comment]
As a side note on that video, that Isaac is also newer and should be worked on. Looks like better side special (faster, looks like it can take more damage), uspecial (teleport, legitimate startup, higher?), neutral special (faster on startup, maybe drop?), usmash (at least earlier IASA, maybe faster overall), maybe dtilt (range).

**Comment by Shin-F** [comment]
The big thing that needs to be worked out with Sami is that she doesn't have a clone slot. If we want to work on her, it'll be necessary to fully figure out how the Clone Engine works and add her to it.

**Comment by somealternateaccount** [comment]
Ideally this can be split into separate discussions for each move, model, etc. Following that split, this issue may be closed.

**Comment by KymaeraK1ng** [comment]
I think you should leave Sami in. Even if you have to change her substantially.

**Comment by TYCC11** [comment]
I am not sure if this is something you have in mind, but I think I know someone who has done some work on Sami.

https://www.youtube.com/watch?v=qGM6e4XXasw
