### ISSUE TITLE
Replacing the new CSPs with PM 3.61 CSPs

### ISSUE THREAD

**Issue by PKSmashOmega** [TheOriginalSINe/Project-M-CC#116]
Yes, I know that this was discussed in Issue #16, but i'm new to GitHub and don't know how to make a pull request :(

I made a quick fix for the CSPs, BPs and RSPs; reverting them back to 3.6.

http://www.mediafire.com/download/64evh6qt9qhs259/Project-M-CC+%28PM+art+revert%29.zip

**Comment by tbelaire** [comment]
Just for future reference, you can check out [github's guide](https://help.github.com/articles/creating-a-pull-request/) to get it working.
If you're new to git, and particularly on windows, I'd recommend using the [github for windows app](https://desktop.github.com/)

The major steps would be to 
- Make your own Fork of the repository on github.  This is a repository at github.com/PKSmashOmega/Project-M-CC which you then will have to ability to push code/assets too. That's as simple as clicking the fork button on the top right.
- Make you changes.  This would mean  `clone`ing your repository locally, editing the files, and then doing `git push https://github.com/PKSmashOmega/Project-M-CC master`.  That'll work even if you cloned `https://github.com/TheOriginalSINe/Project-M-CC` instead. 
- Once they are on github, you should see a little bit of text saying "new changes, click here to make a pull request` when you visit github.com/PKSmashOmega/Project-M-CC, and it should be easy from there.

If you get stuck, comment here and I'll be happy to help with `git`

**Comment by ewmb7701** [comment]
I think we decided to keep the new CSPs and BPs. Closing this issue.
