### ISSUE TITLE
Kirby: Missing Lyn Power Hat

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#117]
Kirby gets no new power or hat after absorbing Lyn.

Suggested fix: Give Kirby a green ponytail hat (possibly use ZSS hat as a base) and an ability representative of Lyn (perhaps a quick sword slash similar to Lyn's F-Tilt)

**Comment by JackpotSHUnited** [comment]
Given that Kirby can now use Mewtwo's Shadow Ball, I don't think it'd be impossible to figure out how to give him Lyn's bow & arrow for his Lyn ability.

**Comment by ghost** [comment]
Unless I'm not mistaken, adding new articles to a character (ie projectiles) is incredibly difficult. If it can be done though, I think her arrow would be preferable as it is her actual Neutral B move

**Comment by cykeswiki** [comment]
Lyn is ported over Pit, right? So, using Kirby's Pit hat, shouldn't it be possible to just edit the properties of the arrow Kirby gets from that hat to resemble Lyn's arrow?

**Comment by PyotrLuzhin** [comment]
Once I get Knuckles working, I'll do it, but someone needs to make the hat model.

**Comment by JCOnyx** [comment]
What Kirby power are we redirecting him to for Lyn?

**Comment by PyotrLuzhin** [comment]
@JCOnyx it has to be pit's. There's no other way to do it.

**Comment by JCOnyx** [comment]
Great, I already have a hat in progress then.

![kirby lyn 3](https://cloud.githubusercontent.com/assets/16162555/11891026/7645ffb2-a50f-11e5-993d-56ba3367ecf1.png)
