### ISSUE TITLE
Kirby: Missing Knuckles Power Hat

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#118]
Kirby gets no new power or hat after absorbing Knuckles.

Suggested fix: Give Kirby a red dreadlocks hat and an ability representative of Knuckles (perhaps his neutral B dive bomb)

**Comment by ghost** [comment]
PyotrLuzhin was able to to get the game to redirect to a hat specifically for Knuckles. The hat still needs a Knuckles dreads model and power, though.

**Comment by PyotrLuzhin** [comment]
Yeah, I'm working on it

**Comment by ghost** [comment]
Made a dreads model. As the neutral B stuff is just PSA GFX, all I did to the sphere was give it Knuckles textures. It will look weird in animations, becuase I haven't edited them to compensate for PM's dreads. The important thing atm is that this works, and we can tell it apart from Sonic's hat. https://www.cubbyusercontent.com/pli/FitKirbyKnuckles00.pac/_988aa79c91824f9a8c87ce6068628ae6

**Comment by PyotrLuzhin** [comment]
@Rage17 Awesome!! As soon as I get it working I'll post a video
