### ISSUE TITLE
Kirby: Using Mewtwo's copied ability crashes the game

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#119]
I have heard from a number of people that this happens in the 3.6.1 build but have not been able to test it myself yet. Could somebody please confirm?

**Comment by JCOnyx** [comment]
Works okay on my end, using SD Hackles method.

**Comment by ghost** [comment]
Ok, I'll test it on my copy when I get home, I have the hacked version. I'll report back if this should be closed or not

**Comment by Eltrion** [comment]
The first 3.61 it did, but Kirby's shadow ball works fine in the current build.

**Comment by ewmb7701** [comment]
This is confirmed to work properly. Closing.
