### ISSUE TITLE
Knuckles: Intro Animation

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#12]
Knuckle's intro is still Sonic's

Suggested Fix:
Knuckles needs a unique entrace animation

My idea is that Knuckles would emerge from the ground by digging and hop to his feet

**Comment by ghost** [comment]
Either have him pop out of the ground by using part of his dsmash animation, or alter one of the spacies' intro animation and have knuckles glide in.

**Comment by bgtdsword** [comment]
If you want to have knuckles gliding in for his intro animation, take inspiration from here :
https://youtu.be/yj9dMRDyYx8?t=49s
From its original apparition. You see him gliding, dropping the glide mid air, falling down in a fairly stylished fashion, and then receptionning himself of his feet.
That would be a nice reference to the original animations !

**Comment by PKPenguin321** [comment]
could probably steal and tweak his side-b animation to make him appear to be gliding in

**Comment by cobalt-blue** [comment]
personally I'm for digging in from the ground. it does match his first appearance from sonic 3 and the animation work already exists in the form of his downsmash.

**Comment by ghost** [comment]
Yeah it will probably be easier to implement too

**Comment by ewmb7701** [comment]
Bumping this. His current animation doesn't work if he spawns on a platform. He should definitely glide in.

**Comment by bb010g** [comment]
@Rage17 has some sort of new animation (not sure what it is yet) in #97.

**Comment by ghost** [comment]
So Martyr on the Discord chat has a replacement animation for this, which is perfectly usable, although they want to clean it up a little bit further. Should i close this issue?

**Comment by ghost** [comment]
I suggest keeping the issue open until they finalize the animation and commit it to the build.

**Comment by ghost** [comment]
@bb010g This should get closed, as we have an official entry animation now.

**Comment by LnktheWolf** [comment]
Seconding. @bb010g
