### ISSUE TITLE
Lyn can teleport with charged up smash

### ISSUE THREAD

**Issue by nagol39** [TheOriginalSINe/Project-M-CC#120]
https://www.youtube.com/watch?v=I5dyNy7NjY0&feature=gp-n-y&google_comment_id=z123ytmwrkyrdfumn23uzfxarm3lvnonw

In my example I tried to show some of the requirements to cause the glitch. One is that it seems to only work facing to the right. The other is that it must fully charged. I tried this on final destination and got no results and then I tried it on bowsers castle. the castle has a specific area between the brown stone on the right side.

**Comment by ghost** [comment]
Tested on nearly every stage. Found when it happens but not the underlying cause.

To reproduce: Go to any stage with a rightward facing wall. Go on a floor piece to the right of that wall. Face right and fully charge up smash. Lyn will TP to the right BZ and die.

To confirm this only happens with the right walls present: Go to Shadow Moses. Face right and fully charge up smash. You will TP into to right wall. Now destroy the left wall and try again. The TP won't happen.

Cause: Unknown
