### ISSUE TITLE
Lyn: Vantage Needs Balancing

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#122]
Current implementation of Vantage is very overbearing and needs to be toned down.

In it's current state:
- Sourspot (close range) -activation- hitbox comes out on Frame 10. Sweetspot (far range) -activation- hitbox comes out on frame 11.
- Has 6 active frames.
- Does 24 damage on sweetspot. Can outright kill characters at 60%
- Sweetspot is about a third of total range of the move.
- Lyn has a 2 frame ADVANTAGE when sweetspotting on shield.

It's currently easy to hit, easy to sweetspot, situationally safe on shield, and extremely powerful.

Suggested Fix:
- Reduce active frames from 6 to 2-3.
- Reduce damage on sweetspot from 24 to 20.
- Reduce size of sweetspot to about half of current size.

**Comment by JCOnyx** [comment]
The problem with reducing active frames, she takes 6+ frames to move from her starting position to the end. So she'd move foward without any active hitboxes during part of the move.

Her sweetspot does not come out of frame 11, I know that. Are you counting the activation hit boxes as the actual hit boxes by accident?

I've been advocating for a damage nerf since we reintroduced her Vantage fix. 18 sounds good, the 2.6 damage was 20 though. Sweetspot size also does need a nerf.

No need to give it more ending frames if we reduce the damage by that much since it'll significantly reduce sheildstun. 4 isn't too bad though if we do though.

It'll only kill that early with horrible DI or if you land a super deep offstage Vantage (then good on you xD). BKB could possibly use a very slight nerf though, but I think the damage reduction will be enough of a weaken the current KB.

**Comment by ghost** [comment]
By 10 and 11 I meant the detection hitboxes that trigger the move. Same with the 6 active frames, those referred to the trigger hitboxes. I still think those should be reduced.

I want to see exactly what change to shieldstun the damage reduction would do, but as long as it puts her at a frame disadvantage, I think you may be right, endlag wouldn't need to be increased.

I outright killed a handful of characters at 60 near Smashville's edge. Perhaps Knockback adjustments should be considered after applying the other changes first.

So I guess reassessed Suggested Fix:
- Reduce active "detection" hitbox frames from 6 to 2
- Reduce damage from 24 to 18
- Reduce size of sweetspot to half of current size.

After playtesting with these changes, we can reassess if more is needed.

**Comment by ArtfulHobbes** [comment]
I agree with pretty much everything in your second statement. I've been thinking and adding in some Lyn changes. We should discuss in Discord tomorrow.

**Comment by ghost** [comment]
After testing the move in debug I think I have an understanding on how the detection hitboxes work:

There are 6 frames of activation hitboxes. eEach frame, a hitbox appears alternating at the move's minimum and maximum range. Like so:
frame 1 hitbox at minimum
frame 2 hitbox at maximum
frame 3 hitbox at minimum
frame 4 hitbox at maximum
etc

I believe the way it works is, because Brawl interpolates hitboxes between frames, it acts like there are hitboxes between the minimum and maximum ones for the duration of the 6 frames.

This next part is just a guess.
The reason that the sweetspot is so easy to hit is because these interpolated "hitboxes" inherit the properties of the nearest real hitbox making the sweetspot actually the entirety of the far half of the move's range.

So in order to cut down the activation frames and shrink the sweet spot, I propose the following change to the hitboxes.

From:
Frame 1 - Min Range Sour Hitbox
Frame 2 - Max Range Sweet Hitbox
Frame 3 - Min Range Sour Hitbox
Frame 4 - Max Range Sweet Hitbox
etc

To:
Frame 1 - Min Range Sour Hitbox
Frame 2 - Mid Range Sour Hitbox
Frame 3 - Max Range Sweet Hitbox
If the move works the way I think it does, it would reduce the active frames to 3 and reduce the sweetspot size from half the move's range to the last quarter.

**Comment by JCOnyx** [comment]
That's actually more in line with the 2.6 build from what I remember. Can't recall if it only took 3 frames or 4 to reach the max distance activation box though.

This is a change I'd be all for, since it would make connecting with a sweetspot Vantage also a little more difficult (takes longer to trigger). I don't think your interpolation theory is correct though, but I think the actual hitboxs still need to be adjusted regardless.

**Comment by ghost** [comment]
Talking with artful hobbes, the sweetspot hitbox is actually twice the size of the sourspot in brawlbox which throws off my theory.

It's really strange though because in debug mode, both hitboxes appear as the same size. Maybe we should talk to Kitsu...

**Comment by JCOnyx** [comment]
I actually contacted Kitsu myself on the Lyn Update 2 video.  Here's the convo:

JamesOnyx117
"I love that you have her vantage working correctly now.  My only gripe is a rather minor one, the sweetspot does 24% and can be followed up at high percents.  That seems pretty high.  

Rewatching the old leak video, the grounded sweetspot seemed to do 20% fresh (at 2:11 in the video) and 16% later after a bit of staling (at 8:17).  So perhaps weakening it a bit would be a good thing.

The only other detail I found that's missing from the leaked video, is the aerial version of vantage seemed to be able to kill even when not connecting with the sweetspot (8:02 in the leaked video).  Perhaps that is for the best, but you could probably change the angle of some of the final hits and give them a very tiny boost in KB Growth and the move would be perfect.

I'll probably try to change all these values myself, but I'd be afraid of screwing up.  I'm not that confident in PSA edits >_<﻿"

thedudemonn 2 days ago
"I'm just working on making her seem more complete, not balance, sorry.﻿"

**Comment by ghost** [comment]
haha welp, at least we tried

**Comment by bb010g** [comment]
3f2e31c changed:

> Vantage:
> SweetSpot Damage 24 > 18
> SweetSpot hitbox size 7 > 3.5 (Matched to SourSpot hitbox size. Questionable in game effect.)

Credit to @ArtfulHobbes.

**Comment by ghost** [comment]
After testing:

Realized that hitboxes for move were centered around her back food (sour spot) and middle of her body (sweet spot). This contributed to why the Sweet Spot was overly easy to land. Also explained strange wiffs when the sword passed directly through opponent.

Working on fixing the hitboxes for the move now. Also, given the amount of risk involved in the move, I believe the kill power should be raised, to be roughly equivalent to FSmash. As it stands, FSmash kills earlier than sweet spot vantage.

**Comment by bb010g** [comment]
What about making it less of a kill move and more of a combo starter/extender on read with increased hit stun?

**Comment by ghost** [comment]
Ok. Made some changes. Harder to sweetspot. Less unreliable wiffing. Lowered base KB slightly, at very low %'s you can follow up a sweet spotted vantage with a combo. High %'s it kills at roughly the same time as FSmash.

I think this is now at a fair risk/reward tradeoff for wiff endlag.

**Comment by ghost** [comment]
I believe the current version of vantage is a very workable move with similar function to Wolf's side B.

Unless anyone has major issues with it's current implementation, I will close this issue. Can I get a confirmation?

**Comment by JCOnyx** [comment]
It's at a good spot now. I'd say this could be closed.

**Comment by somealternateaccount** [comment]
Since @Azuran01 has effectively signed off on this change, I will do the same and close it. There is some discussion in the Lyn channel on the discord with regard to changing the properties of this move (paralyzing, hitstun, etc) but further discussion should take place in new issues.
