### ISSUE TITLE
Lyn: Revert Recolored Slash Effects

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#123]
For a few moves, I believe Fsmash, Dair and Vantage, Kitsu added a personal flair of Red slash effects to the sword swings.

Suggested Fix: They should be reverted back to their original effects. Personal aesthetic touches aren't in line with the project goals.

**Comment by Hellraz0r** [comment]
If we go through with this I want to have the option to put the red tracers back. I really like them.

**Comment by bb010g** [comment]
I'm for keeping them. They're a nice reference to the original game, something the PMDT always tried to put in.

**Comment by ghost** [comment]
This build isn't about taking creative liberties, it's about finishing what we had leaked. This is a subjective stylistic change to something that didn't need changing.

**Comment by Hellraz0r** [comment]
It's already in and there's no reason to put extra effort into removing them. If someone had "add red tracers" pinned on a bullet list of design goals for this build then, yeah, I'd understand where you're coming from.

**Comment by ghost** [comment]
By the same reasoning, if I contributed an animation fix for say Lyn's D-Smash, but also changed her hair to be purple in all her costumes because I thought it looked cool, it wouldn't be worth the effort to revert that change. Changes like these belong in personal builds. This is an Open Source project with clear goals. Even if you like a certain unnecessary change, it doesn't mean everyone else will appreciate it.

**Comment by Hellraz0r** [comment]
...No. That's a fucking retarded stretch of logic. Lethality tracers adhere to the character/universe, create a defining, distinct aesthetic for primary kill moves, and don't detract from the experience. If someone were to come forward and actually state that there is a reason _not_ to include them, then there could be reason to do so. I could equally argue that identifying the Lyn moveset further with her origin game would fall in line with the PMDT's goals of finishing the characters off, because that's an obvious design element that makes itself apparent all throughout animations and attack properties.

@bb010g already stated why the change was more than something that "looked cool." Kitsu himself even stated why in the video's description.

**Comment by Eltrion** [comment]
I'm for keeping them. One of the key things in designing a smash character is making it easy to tell what move a character is doing and where the hitboxes are. The tracers actually help with this, especially since lyn's strikes are so fast. Taking them out would be actively hurting the character's design direction.

**Comment by ghost** [comment]
Why do you dispute that reasoning. The issue was to fix Vantage. What was submitted was both a fix for vantage, and a subjective aesthetic fix. I could just have easily said it's the same as contributing an animation fix for D-Smash and also adding in a fur collar to her suit because she had one in FE Awakening and I thought it looked cool. This is still a subjective and unnecessary change.

As for reasons why not to:
- There is no real precedence in PM for this sort of change. None of the other swordsman have a similar effect.
- What moves the effect should be on is subjective. Why isn't it on bair? Up air is a pretty good kill move too.
- Though you may like the aesthetic change, others may not. Even if I did like the color change myself, it has a very muted look on her FSmash that doesn't portray the power behind the attack well.
- This generally goes against the project goal of adhering to PMDT's design. There is no evidence they were going to add this kind of effect, not in the files, move mockups, or previous leaked builds.

**Comment by Hellraz0r** [comment]
> there is no real precedence

Actually, I would point at my main, Roy. His nair and S4/U4 on DED all have the same tracer as Flare Blade, indicating fire.

Hell, if you added an Awakening costume I wouldn't argue. Shit's badass.

> which moves are affected

I agree here. I think bair deserves it as well. Uair doesn't kill as early and is typically juggly, so I wouldn't put it there.

> others may not like it

Then let them come forth and say so. We have free reign to make the red tracer stand out more to better relay the power behind moves. Maybe you can make it like Falcon's knee taunt and have it only turn red if you press up taunt at the same time.

> goes against goals

I already stated why that's not necessarily true. What the PMDT wanted is up to interpretation, and in the end it's up to the consumers to decide what we think fits the game most.

**Comment by ghost** [comment]
Roy's fire tracers indicate the move has fire effects. This is something that can be objectively decided on move by move. Fire effect on this one? Add fire tracer.

Lyn's "most common kill moves" is subjective and completely relies on play style. Like you saying Up Air doesn't deserve the tracer, but I would say it does because it can kill around 70-80 on a number of stages. Completely subjective.

The goals are clear. Complete what was unfinished in the leaked builds. Not play "guess what PMDT might have added".

If we allow changes like this into the build, we set a precedent for anyone to contribute all sorts of new changes that may or may not benefit the project, and then are forced to argue subjective opinions why adding red tracers was a cool and good change vs why adding Waluigi as a playable character is not.

**Comment by Hellraz0r** [comment]
Whatever, man. I put forward my two cents. I'm not arguing semantics anymore.

**Comment by bb010g** [comment]
The strongest argument against the tracers probably is that "most common kill moves" is subjective. Also, you do have the smoke trail for high knockback moves.

**Comment by JackpotSHUnited** [comment]
Yeah, if the original Lyn didn't have red sword trails, I see no reason for her to have them in the CC build. That's like saying we should give her combo-oriented moves a green sword trail just because it looks cool.

**Comment by ewmb7701** [comment]
Alright I feel like I should weigh in on this. Personally, I like the idea is pretty cool. However, as @Azuran17 pointed out, it's not really part of the project goal. However, there are some moves with different effects on them that have different effects to indicate extra damage. I think that this argument is a bit silly, as it is all over sword tracers. I would like to say "let's keep them in", but I don't want it to set a precedent of adding personal flair to the project. I think we should revert them, as it isn't in line with the project goals.

**Comment by bb010g** [comment]
> That's like saying we should give her combo-oriented moves a green sword trail just because it looks cool.

Didn't Sakurai do that with Dancing Blade? :)

**Comment by oXMugetsuoXo** [comment]
I understand Azurans reasoning however it is a nice touch. Maybe just leave it on vantage? Considering thats a "critical" move.

**Comment by pharoahfawcett** [comment]
i'd recommend reverting them. it really doesn't fit with the project goals.

**Comment by bb010g** [comment]
[**@oXMugetsuoXo**](https://github.com/oXMugetsuoXo) commented on [Dec 10, 2015, 8:13 PM PST](https://github.com/TheOriginalSINe/Project-M-CC/issues/123#issuecomment-163834991):

> I understand Azurans reasoning however it is a nice touch. Maybe just leave it on vantage? Considering thats a "critical" move.

For the normal "flair" tracer on special moves, it would make sense, but Vantage already has the teleport animation "flair".

**Comment by somealternateaccount** [comment]
I believe this is a blocker for Lyn's completion, so long as it is undecided whether or not she should have these trailing effects. Needs discussion.

**Comment by ghost** [comment]
Still of the opinion that it was a personal change that Kitsu thought "looked cool" and this build is not a place for arbitrary subjective artstyle changes.

**Comment by Hellraz0r** [comment]
No discussion needed. @TheOriginalSINe made his decision. Theoretically we could objectify Lethality tracers on moves like fsmash, Vantage, dsmash (back), and bair by calling them the _strongest_ KO moves rather than "most common" by comparing BKB and KBG values, but that requires work and adding them to bair.

**Comment by LnktheWolf** [comment]
Fixed by #323
