### ISSUE TITLE
Lyn: Slow Walk Animation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#124]
Lyn's slow walk animation is very stiff and low quality. Her upper body barely moves and her feet visibly slide on the ground. Hand also hovers near the hilt of her sword rather than grip it.

Suggested Fix: Redo the animation. Perhaps use Marth's walk as a base.

**Comment by ghost** [comment]
Additionally, her hair floats in a very unnatural way

**Comment by bb010g** [comment]
Subsumed by #305
