### ISSUE TITLE
2 Knuckles?!?

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#126]
When playing the Green Hill zone stage (the alternative one) I'd your playing as Knuckles or any character, there's already a Knuckles running around in the background.

I'm pretty sure its not a bug but was left in.

**Comment by ghost** [comment]
Yeah, It's an untouched Brawl Green Hill Zone, so that never got taken out or replaced.

**Comment by ewmb7701** [comment]
I was going to just delete the textures, but then an amazing idea struck me: Replace Knuckles with Mecha Knuckles.
![mecha boyz](https://cloud.githubusercontent.com/assets/8096152/11732305/d9df4352-9f70-11e5-8f2c-81a94829a295.PNG)

Working on fixing up some stuff before I push the commit with this in it.

**Comment by ghost** [comment]
Neat idea.

**Comment by Darquezze** [comment]
@TheOrignalSINe is Mecha Knuckles an actual thing? (PS that will also be cool for a alternative costume since none of the new characters have one)

**Comment by ghost** [comment]
@Darquezze Mecha Knuckles is from Sonic Advance, yeah. Also, Knuckles already has two alts in the Discord chats.

**Comment by ewmb7701** [comment]
@Darquezze Mecha Knuckles is my ORIGINAL CHARACTER DO NOT STEAL. I'm not sure if we should add alts, but it would be very cool.
@Rage17 Which alternates? Vector and Espio, right?

Also closing this issue, I pushed my changes.

**Comment by Darquezze** [comment]
@TheOriginalSINe trust me I won't ;) PS since u used thedudemonns version of Lyn, I want to ask him if he can help you guys? I'll tell him if u want me too

**Comment by ghost** [comment]
@TheOriginalSINe the vector and espio ones, yeah. A Charmy and Jet Set one will be made as well.

**Comment by bb010g** [comment]
[/u/TeiunBomb](https://www.reddit.com/user/TeiunBomb) [brought up](https://www.reddit.com/r/SSBPMCE/comments/3xiff9/about_assist_trophies/cy5cu1u) the nice idea of using Blaze instead of Knuckles. She has a trophy, so we could just rig it for animations and go. She's more recognizable, and IMHO would look nicer on the stage.

**Comment by ghost** [comment]
@bb010g her model would need to get downgraded for it not to lag, AFAIK. The character models that are there now are downgraded trophy models.

**Comment by JackpotSHUnited** [comment]
King Dedede still appears on Dream Land doesn't he? Nobody uses Brawl GHZ, we don't need to replace Knuckles with a random character. That would definitely be outside of the project goals.

**Comment by ghost** [comment]
@JackpotSHUnited King Dedede does not appear on Dreamland, actually. The PMDT changed it so that these guys appear instead: 
![image](https://cloud.githubusercontent.com/assets/16145986/11921278/56c6c630-a753-11e5-9b46-9165b276b9a5.png)

In other words, it has a precedent.

**Comment by JackpotSHUnited** [comment]
Bronto Burts already appeared in Dream Land in Smash 64.

Going by that precedent, Knuckles should be removed, not replaced.

**Comment by ghost** [comment]
Both Bronto Burts and D3 show up, but D3 is only a sprite

**Comment by JackpotSHUnited** [comment]
If they both show up, that means the stage wasn't changed.

Green Hill Zone shouldn't be changed either, then.
