### ISSUE TITLE
Isaac: Pivot grab and B-reverse

### ISSUE THREAD

**Issue by BlackDrMario** [TheOriginalSINe/Project-M-CC#128]
When a pivot grab connects, it seems to, on occasion, cause a grab effect behind Isaac as well.

Grabs in general seem to bug out at times, even shifting Isaac's position on screen for a frame or 2 before returning to where he should be. Same for Neutral B when B-reversing. However is inconsistent.

**Comment by UNOwen3** [comment]
I want to add that at some times, the grabbed character will teleport from the grab effect on the back to the real one. I managed to recreate it and save it frame per frame:

Regular one: http://imgur.com/fGrHnNp
Teleporting one: http://imgur.com/3KuX2N9
