### ISSUE TITLE
Lyn: Missing metal texture

### ISSUE THREAD

**Issue by Bizcocho** [TheOriginalSINe/Project-M-CC#129]
Lyn doesn´t have a metal texture.

**Comment by ghost** [comment]
https://www.cubbyusercontent.com/pli/lyn.rar/_9ce14490e1b24ce38fa0d2838615e184 Link to fixed metals for all costumes. Note: Includes a new purple recolor(based off of the CSPs that PMDT made to mess with Evolution) and a pattern for Green Lyn(every other costume has a unique pattern layered onto the dress and skirt texture, while green oddly lacked one).

**Comment by bb010g** [comment]
Fixed in #150.
