### ISSUE TITLE
Isaac: Franchise Logo

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#13]
Isaac's franchise logo is the Smash Bros Logo

Suggested Fix:
Add a Golden Sun logo to all files that need them:.Files in info2, sc_selcharacter.pac, STGRESULT.pac, etc.
Redirect Isaac's to use the franchise logo (Unknown how to do this, need to do more research)

**Comment by ewmb7701** [comment]
![smaller logo](https://cloud.githubusercontent.com/assets/8096152/11574116/af6d30c8-99d7-11e5-8174-e267c826daa5.png)

**Comment by cykeswiki** [comment]
There's no need for redirection. His logo (as in the Smash Bros one he currently has) is right in the files, you just have to replace it with the Golden Sun one. By replacing MenSelchrMark.20 in every file you listed, you can give Isaac his franchise logo.

That's how it worked for me, at least.

**Comment by JCOnyx** [comment]
The problem with doing that is anything else that also had the SSB logo would then have the Golden Sun logo.  It's actually pretty simple to add a completely new logo tho, so this should be a relatively quick fix.

**Comment by AgentBlizz** [comment]
http://vignette3.wikia.nocookie.net/ssb/images/2/28/Gssymbol2.png/revision/latest?cb=20140915054233
That's pretty cool that Golden Sun already has a series logo. Found it here:
http://supersmashbros.wikia.com/wiki/Series_symbol

**Comment by vdenzen** [comment]
Here is the code 0445596C 16000000. Add this to the GTC.
You also have to add a MenSelchrMark and increase the number in AnmTexPat(NW4R) to 22 in the MiscData[30] in your sc_selcharacter. This will make Isaac load MenSelchrMark.22

https://gyazo.com/ce409bb03ef4577c199c929200ac377c

**Comment by vinegar97** [comment]
@vdenzen i'm gonna try and test your code and see if it works right, and then try to commit it if that's alright for you, with proper credits of course.

@TheOriginalSINe would all text codesets need to have the code if this is going to be committed ?

**Comment by bb010g** [comment]
There's a nicer Golden Sun logo we may be able to import [here](http://smashboards.com/threads/the-official-smash-bros-4-character-logo-icon-database-and-requests-thread.326025/).
