### ISSUE TITLE
Lyn Balancing: My Thoughts

### ISSUE THREAD

**Issue by RafikMetri** [TheOriginalSINe/Project-M-CC#130]
Luna here

Since we have been looking on how to balance Lyn I just wanted to share my thoughts on this

I made this as an issue because I wanted this to be on git somewhere and not in a chat room where it will eventually disappear and adding a new file to the repository didn't sound like a good idea so i'll just leave this as an issue. If this needs to be moved I'm willing to do that.

In order to balance Lyn first we must give her an identity. From how lyn was left when we got the leaked build I would say that Lyn is a rushdown combo character who kills by comboing into a gimp or comboing into a kill move. She also uses mid-range spacing to keep characters at bay. Her raw kill moves should be risky and difficult to land.
In other words, Lyn can play a safe pokey game but needs to take a risk in order to get a good kill.

So far the biggest moves that are being requested to nerf in order from greatest to least are:
1. Arrows
2. Down-throw
3. Vantage
4. Back-air

Here are my thoughts on each:

Arrows:
Arrows as of now are really strong
There's a lot that they can do 
- You can gimp while on stage
- You can camp with them
- You can combo with them
- They do a lot of damage especially when charged

There are only two downsides to arrows
- only two angles making their vertical range limited
- punishable if arrow missed

As of now the there is too much reward for the little risk of using arrows therefor making arrows unbalanced
The way I would balance arrows is by keeping the low risk but lowering the reward
 More specifically, uncharged arrows need to less work.
- Uncharged arrows should pop up more and knock back less
- The longer the charge the less pop up and the more knock back and damage
- maybe increase lag after arrow shot... maybe

What do these changes do?
- Uncharged arrow's damage and knockback gets nerfed but still allows for comboing with arrows
- Charged arrows becomes a strong and potentially kill move but requires a read or set up
- if after lag is increased this will discourage camping since lyn is an offensive character and makes this move more punisheable

In regards to the arrow's damage, here's how the damage scales right now:
close range # / long range #
long distance = distant planet's ledge to ledge
- uncharged - 7% / 13%
- fully charged 15% / 21%

I would change this too:
- uncharged 4% / 13%
- fully charged 10% / 21%
  or something like this

Vantage:
Just change knock back... make sure you can still combo out of it though.

Down-Throw:
Down throw is a pretty strong move it can kill at higher percents and at lower percents get characters off stage
I've seen a lot of suggestions to nerf the knockback on down-throw but I simply disagree
Why? Well first I think it should be nerfed but not this way
Lyn is a spacing character that when spaced well is rewarded with combos. 
If Lyn wants to goe in for a grab, it means she needs to lose her spacing advantage.
If Lyn is playing against a skilled opponent this means she's putting herself in great risk.
Since grab is risky, it should be rewarded with a good throw.
If there is anyway to nerf down-throw, it would be to make grab more punished by increasing lag either before or after.
I would say Lyn's grab maybe needs to have a teeny tiny bit more after lag. Just a few frames.

Back-Air:
Now this move isn't getting requested to get nerfed all that much but some people are saying it so I'll comment on it.
I think back-air is fine as it is. This assuming the auto-cancel thing gets fixed.
Some people have suggested to nerf the knock back on this move and I completely disagree
Why? If back-air no longer becomes a kill move, then Lyn will no longer have a semi-safe semi-reliable kill move.
She only has 3 other kill moves
- F-smash which is hard to land and requires a read or set-up
- Down-throw which requires a risk to get
- Charged arrow which should be hard to land
  After this, the only other way she can kill is by gimping
  By removing back-air's kill potential her only reliable way of killing is by gimping
  I think back-air is fine the way it is but if it is decided that it needs to be nerf this is how I would nerf it:
  Don't nerf it by removing it's kill potential
  make it more risky to use by increasing the wind up or after lag

**Comment by aFracture** [comment]
I like where you're coming from. Personally I think Vantage, Down-throw, and Back-air (except for adding landing lag) should be completely untouched for a while. We really need to let things play out after these new characters are simply cleaned up.

Arrows could probably use some tweaking, but I'm hesitant to do too much to them, for the reasons stated above. Yes, they're crazy good right now, and they'll almost certainly need some changes done in the future, I just don't know that we have enough information right now to decide what changes those are. But like I said, you're suggestion is totally reasonable. It may end up coming to that. 

All I want is to not jump the gun too early on this (a mistake I feel the PMDT made a little too often in what seemed like a series of over-nerfs, in the past).

**Comment by ghost** [comment]
A major goal of this project is sticking as close to PMDT design as possible, and therefor do as little of our own "balancing" as possible.

Bair, Arrows, and Vantage have been determined to be "broken" or unfinished in their current state and have issues already opened for them. If you want to leave input on those individual moves, leave a comment on their respective issues.

This isn't a specific issue and is already covered by #122 #98 #48 I believe it can be closed.

**Comment by ewmb7701** [comment]
This issue is already been split into multiple issues. Closing.
