### ISSUE TITLE
Lyn: Nair Hitboxes

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#135]
The second frame of hitboxes for Lyn's Nair angle too far into the Z plane.

Suggested fix: move these hitboxes into the players plane.

**Comment by somealternateaccount** [comment]
This is potentially a balance-affecting change and likely needs discussion.

**Comment by ghost** [comment]
To clarify:

She has a number of frames in this move where the hitboxes are entirely in the Z plane due to the nature of the move (spinning sword slash)

The only issue with frame 2 is that the innermost hitbox still can hit while the outer ones can't.

**Comment by somealternateaccount** [comment]
There are plenty of other moves that move into the Z-axis. Is this truly a concern, or do they leave the Z-axis far enough that hitting smaller characters is inconsistent when otherwise well-spaced?

**Comment by ghost** [comment]
Frame 2 meant the second frame of hitboxes, not the second frame of the move, sorry.

This potentially could be fine, but I want to see if other character's moves behave in a similar fashion. Marth or Roy dash attacks could be good to look at for comparison.
