### ISSUE TITLE
Melee battlefield texture error

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#136]
battlefield`s melee alt has an incorrect texture assigned on the main platform (seen here http://smashboards.com/threads/official-stage-discussion.372723/page-38#post-20497158)

fix: simply opening the file in brawlbox ,finding the "TockBF" model ,opening the material named "Center" ,and changing the texure name inside to "front" should fix it.

**Comment by ewmb7701** [comment]
Fixed this issue. Closing.
