### ISSUE TITLE
Subspace Emmisary Doors

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#140]
I can't enter any sort when playing subspace

**Comment by ghost** [comment]
Single player issues are out of scope of the project I believe.

**Comment by ghost** [comment]
@Azuran17 , nah, I would say that not having SSE be broken by our patch is a goal. PMDT did want the mode to work, after all.

**Comment by ghost** [comment]
I checked this out myself, and I have no issues with entering subspace emissary doors. Be sure to follow the PMDT's instruction of completing a match with any clone characters before you start SSE mode.
