### ISSUE TITLE
Knuckles: Dodge rolls fall off platforms

### ISSUE THREAD

**Issue by Shredster7** [TheOriginalSINe/Project-M-CC#151]
Whenever Knuckles uses a dodge roll that causes him to reach the edge of a platform, he will fall off the side of the platform when the dodge roll animation ends. This results in either a regular fall when the shield button is released, or a tumble whenever the shield button is held down. He will automatically snap to any grabbable ledges that he rolls off of.

**Comment by ghost** [comment]
Tested. Only occurs on back rolls.

In debug mode (L+R+down taunt) if you enable collision points (Y+left taunt) you can track where Knuckle's grounded collision is.

On both forward and back roll, on frame 38, you can see that Knuckle's floor collision point shifts in the direction he was rolling. However, there is a slightly bigger shift during back roll than forward roll. I believe this difference is enough for him to no longer be in collision with the ledge/platform so he falls off.

Suggested Fix: Tweak the animation/character model during the animation so whatever is determining the position of his floor collision shifts the same amount during his back roll as it does during his forward roll.

**Comment by ghost** [comment]
Additionally, if you shield after a front roll on ledge, you were also forced off stage.
