### ISSUE TITLE
All-Stars Mode. Characters with different alts

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#152]
In all-star Mode when playing as a new character (Mewtwo,Roy,Knuckles, Lyn,Issac) the characters they were at first from use a different alt instead of the original.
 Example: Using Mewtwo=Red Lucario 
Using Knuckles=Red Sonic

**Comment by somealternateaccount** [comment]
If I'm reading this correctly, then selecting a cloned character blocks the cloning character's costume slot as though there were 2 of the cloning character. If this does not occur in standard Versus, the ideally a coder can look at the differences between the all-star and the versus menu codesets and resolve the issue.

**Comment by DarkLink1996** [comment]
@Darquezze, Wait, All-Star Versus (Special Brawl), or All-Star Mode (Singleplayer)?

**Comment by Darquezze** [comment]
@DarkLink1996 All Star Mode (single player)
