### ISSUE TITLE
3.61 Kirby Hats

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#153]
Mewtwo Kirby uses Mewtwo's 3.0 Shadow Ball graphic. Should just be a matter of replacing the model and adding the trail for when it is fired.

Ganon Kirby needs a cape for his new special. Currently he just swings his arms around.

New character Kirby hats do not exist. Isaac's has the correct fix for now(Kirby acts as if he inhaled another Kirby), but Lyn and Knuckles do not have hats, and Kirby T-poses when he tries to use their powers.

**Comment by somealternateaccount** [comment]
This may have been resolved with the commits of new Kirby hats - they should be diffed with the 3.61 Kirby hats and the new hats should be bugtested.
