### ISSUE TITLE
Lyn Recolor Texture Issue

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#154]
There seems to be a black texture on the back of her neck in her recolor costumes that aren't around in her normal costume.

Regular Lyn: http://i.imgur.com/mpFuhzp.png

Red Lyn: http://i.imgur.com/9LOgorp.png (all recolors like this one are affected by this issue).

**Comment by ghost** [comment]
This is covered by issue #69

**Comment by MrGameCrazy** [comment]
Thanks for letting me know.
