### ISSUE TITLE
Knuckles: Spot Dodge Normalization

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#156]
Knuckles seems to have the wrong spot dodge stats. It currently doesn't match the stats of anyone else in the cast. Invulnerability starts on 2, lasts until 15, and first actionable frame is 23. This is almost in line with the lowest timing tier of spot dodges, just has the wrong First Actionable Frame.

Suggested Fix: Increase first actionable frame from 23 to 25 to match the rest of the cast.

[Link to normalized Roll and Spotdodge Data](https://docs.google.com/spreadsheets/d/17c4fKa81eB193OvexoIpsbiFp7lxVD1XSwMAdRHPOdw/edit#gid=0)

**Comment by Tottle** [comment]
Are his current stats better than the heavy characters or worse? I think it would be a mistake to arbitrarily assume he goes with the worst group. There are heavy exceptions including Samus and Ganondorf. He might belong with one of the next heaviest groups instead.

**Comment by ghost** [comment]
I just realized his stats are mostly in line with the lowest timing tier of spot dodges. The only thing wrong is his first actionable frame is early.

Changing issue to reflect this.

**Comment by bb010g** [comment]
Has this been fixed with the new Knuckles?
