### ISSUE TITLE
Isaac: Teleportation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#159]
Using Isaac's nuetral special anywhere on the Temple stage makes him teleport randomly in the direction he performs the attack in. Also using Smash attacks makes you teleport in the direction you use them in.

**Comment by BlackDrMario** [comment]
This happens on quite a few stages. It also seems to happen randomly too. Sometimes neutral B will send me high in the air, others, straight down to the ground (or into the blastzone if I'm off-stage, irritatingly). Throwing an opponent has also made me teleport at least once before as well.
