### ISSUE TITLE
Isaac: Down Taunt

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#160]
Currently, Using Isaac's down taunt puts him in a "T" shape. Isaac cannot move in this state until he's hit.

**Comment by somealternateaccount** [comment]
If this occurs, it looks like Isaac does not have any down-taunt animation. We would need an animator to resolve this.

**Comment by LinkTahuterasuSpirit** [comment]
@Thomascoolkid actually issac can move out of itby any input by the person playing issac
