### ISSUE TITLE
Knuckles: Placeholder Sound Effects

### ISSUE THREAD

**Issue by Karrotkonvoy** [TheOriginalSINe/Project-M-CC#161]
Knuckles' dodge roll uses a sound effect from Sonic's up taunt animation. Also, his sound effect for balancing on a ledge is a copy of the one he uses for jumping.

Suggested fix: Use a common dodge roll sound, and find some kind of "woah" clip to use for balancing.

**Comment by pharoahfawcett** [comment]
http://www.sounds-resource.com/search/?q=knuckles

**Comment by bb010g** [comment]
Duplicate of #81.
