### ISSUE TITLE
Hackless download not working

### ISSUE THREAD

**Issue by cimpyhigh** [TheOriginalSINe/Project-M-CC#165]
The download for hackless didn't work. I fixed it by changing the bin file in the st folder with the one from project m 3.6.

**Comment by Yohan1044** [comment]
Hackless install works fine for me.

**Comment by bb010g** [comment]
Works fine for me on multiple Wiis. Try deleting `projectm/pf` and re-copying `projectm`, `codes`, `gameconfig.txt`, and the contents of `[Hackless]`.

**Comment by ghost** [comment]
Since others have no issues doing a hackless download, I'm closing this. Check out the [help board](https://discordapp.com/channels/123214554363723782/123216400792682498) on discord for troubleshooting.
