### ISSUE TITLE
Knuckles: Glide can go through stage.

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#166]
Gliding through a stage can occur when using Knuckles.

**Comment by ghost** [comment]
Hey dididan2000.

Can you please give more details to help us recreate this issue? What stages can he glide through? Under what circumstances?

**Comment by ghost** [comment]
I'll show you

**Comment by somealternateaccount** [comment]
This has been reported by others, but nobody has provided steps to reproduce it.

**Comment by ghost** [comment]
Oh, I forgot to post a video of it. Let me do that today.

**Comment by Awsoman62** [comment]
There was a glitch with Knuckles where he started on the right and he Side B, he teleported to the left side of the stage and couldn't use any moves and there were no sounds I also could not hit him so I had to exit the game. It was on Green Hill Zone.
