### ISSUE TITLE
Missing Final Smash Eyes

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#167]
All three of the new characters are missing Final Smash eyes(or some model indicator to the same effect).

**Comment by ghost** [comment]
https://www.cubbyusercontent.com/pli/knucklesfseyefix.rar/_191f8c43e02b4459b0da63c9a0de1a23 A link to a fix for Knuckles

**Comment by bb010g** [comment]
Could you give a picture?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11771710/205d79c0-a1e2-11e5-8843-f62e212bb242.png)

**Comment by bb010g** [comment]
You can't use BBCode on GitHub. It's [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by ghost** [comment]
fixed it, dunno if you see the edit yet.

**Comment by bb010g** [comment]
:shipit:

**Comment by bb010g** [comment]
Could you PR this?
