### ISSUE TITLE
RFC: Completed Wii ROB

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#168]
@Rage17 has put together a very nice [completion](http://forums.kc-mm.com/Gallery/BrawlView.php?Number=208968) of ROB's Wii alternate costume. It adds a Final Smash expression and fleshes out the Hurt expression. However, I'm not quite sure whether adding this falls under the scope of this project. On the one hand, it's completing the PMDT's work to the same level of detail as everything else, is very limited in scope, and is not intrusive to normal play. On the other hand, it's not completing leaked content. I personally lean towards adding it, but I want to hear what everyone else thinks.

**Comment by ghost** [comment]
I have made fixes to a few other 3.6 and below things as well, and I want to know if we want them to be added.

**Comment by Eltrion** [comment]
I would support adding this. I would consider it a completion or bugfix of that costume.

**Comment by jojmaht** [comment]
I'd say it falls under completion.
:shipit:

**Comment by bb010g** [comment]
Closed in d60a7dd.
