### ISSUE TITLE
Menu: New Version Number

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#17]
The version number should be changed to reflect that this is not an official build

Suggested Fix:
Change the version name on the result screen (STGRESULT.pac) and the strap screens. 

I'm not sure what the version should be called. I think something like Project M: Complete would suffice.

**Comment by jojmaht** [comment]
How about "Project M : The Definitive GOTY Edition Turbo Master HD Remix"?

(👍 for Project M : Complete)

**Comment by KaBombz** [comment]
Here's just a few sample ideas, maybe one of them will seem good

Project M Gold
Project M Final
Project M Community

**Comment by ewmb7701** [comment]
I do like Project M Gold, but I think Project M: Complete sounds more definitive.

**Comment by jojmaht** [comment]
Both Complete and Final would be strong contenders.

**Comment by thesmashking25** [comment]
Project M: 4.0 Community Build

**Comment by ghost** [comment]
Complete and Final imply this being a definitive version of the game, or official works by PMDT. As this is an open source project, I would suggest something more along the lines of Community.

**Comment by jojmaht** [comment]
I'm waiting on a consensus to be reached before I start the pull request.

**Comment by ghost** [comment]
Project M 3.6 Communal Bugfix?
Project M 3.6 Unofficial Bugfix?
Project M 3.6 Community Patch?

You should differentiate yourself from custom builds (Complete, Gold, etc.) and avoid terms like 4.0... 

It's important to emphasize that it's a bugfix/patch as well

**Comment by ghost** [comment]
I think I agree most with the Community Patch suffix. A) Community represents the open source nature and B) Patch as this technically is further reaching than just bugfixing (finishing Lyn and Knux)

**Comment by thesmashking25** [comment]
@Azuran17 community build makes much more sense. There are also other melee and netplay hacks that have the "build" suffix.

**Comment by ghost** [comment]
@thesmashking25 Patch, Build both sound fine. Just further reaching than "Bugfix" and not as official as "Final" or "Gold"

EDIT: Scratch that, I agree with Pharoah, build is typically associated with custom content and brawlvault mod projects.

**Comment by ghost** [comment]
I feel like patch makes more sense... I feel like most PM "builds" add custom content while this one just patches up the holes.

Project M 3.6 Community Patch

**Comment by bb010g** [comment]
[**@TheOriginalSINe**](https://github.com/TheOriginalSINe) commented on [Dec 3, 2015, 2:56 PM PST](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/issues/17#issuecomment-161815653):

> I do like Project M Gold, but I think Project M: Complete sounds more definitive.

Gold should be reserved for the final 3.6.1ish build the community decides on.

I'm partial to {3.6,3.7} Community Edition. Patch makes it seem more like PMDT.

**Comment by ewmb7701** [comment]
What about Project M: Community Complete? Or Project M: CC for short?

**Comment by jojmaht** [comment]
Maybe we should distance ourselves from the PM name too?
Open M?
Le 4 déc. 2015 9:37 PM, "TheOriginalSINe" notifications@github.com a
écrit :

**Comment by bb010g** [comment]
Ooh, I like Community Completion. As to distancing ourselves from PM, why? I don't think we are going to be in that much trouble, as a mod of a mod Nintendo isn't going after and probably won't.

**Comment by ghost** [comment]
@skinnyfoetusboy This is a project meant to patch a Project M dev version from what I understand. Nothing past that is planned. Therefor, the main focus is just tying up the loose ends of PMDT's work. Given that, I don't see reason in distancing from their name.

@TheOriginalSINe That doesn't really sound like it makes semantic sense. "Gold" "Complete" "Final" etc all sound like they are dressing the project in grandeur. Kinda like why "Smash Evolution" sounds a bit much. Just call it what it is. A community patch.

**Comment by thesmashking25** [comment]
OK, it's official. Project M 4.0: Community Patch. Now let's go finish Isaac.

**Comment by ghost** [comment]
Yeah, community completion seems a bit pretentious. I feel that "Project M 3.6 Communal Patch" hits the nail: it's not the PMDT, no non-official content, and patches the missing content.

**Comment by ghost** [comment]
also, just to be clear, you shouldn't call it 4.0 or even 3.7 as this isn't what they would have planned for either of those

**Comment by ewmb7701** [comment]
Hmm I like Community Patch. Communal sounds a bit too fancy. Also I agree with you on those points  @Azuran17 and @pharoahfawcett

**Comment by bb010g** [comment]
We don't know what they were planning. My issue with Patch is that it signifies a small set of changes. What we are doing to Isaac is more than just a couple of bug fixes and balancings, but instead finishing a character's move set. That is significant.

On the same note, there's no issue with a new version number if we annotate it. The PMDT will never release beyond 3.6 flat as far as we can see, and we don't know what those releases would contain anyway. This feels like a 3.7 to me personally: new characters and art, but not enough changes to justify a major version bump.

**Comment by bb010g** [comment]
We don't know what they were planning. My issue with Patch is that it signifies a small set of changes. What we are doing to Isaac is more than just a couple of bug fixes and balancings, but instead finishing a character's move set. That is significant.

On the same note, there's no issue with a new version number if we annotate it. The PMDT will never release beyond 3.6 flat as far as we can see, and we don't know what those releases would contain anyway. This feels like a 3.7 to me personally: new characters and art, but not enough changes to justify a major version bump.

**Comment by ghost** [comment]
@bb010g it's the definition of a patch... he didn't create project m, he's just fixing some glitches and aesthetics.

and on another note, i hope @TheOriginalSINe just gives Isaac and Sami updated renders and an announcer call for people that can't bear to not have the "complete" set. knuckles and lyn have all of their moves either in the game or outlined, and can be made almost identical to PMDT specification. Isaac and Sami would basically just be fanmade PSAs.

**Comment by bb010g** [comment]
Balancing three new characters and adding substantial functionality to two is not fixing some glitches and aesthetics. I think Isaac can very well be saved and brought in with the same amount of care as the rest of PM, but Sami may be too far gone. (I'm not sure, though. How much of Sami is there?) Even without finishing Isaac and Sami, we're still balancing two characters and adding major parts of moves to Lyn. The addition of moves is where I would draw the line.

**Comment by ghost** [comment]
@bb010g Knuckles and Lyn can be completed nearly to the specifications of the PMDT. Neither are missing moves (Lyn's specials that don't work have official PMDT documentation on them) and Knuckles only needs a little animation cleanup.

Adding a number is implying that this is what the PMDT were thinking. It confuses people who thought the game ended at 3.6. "Project M 3.6 Community Patch" covers everything that @TheOriginalSINe has created so far fairly well.

**Comment by Jeelix** [comment]
I vote for Project M Community Edition. Patch, Build, Complete, etc. all imply certain meanings, and Edition is the most general of these.

At this point, I would consider this a patch, but if/when rebalancing and fixing up Isaac become subjects, I feel the word 'Patch' would be a bit stretched.

I don't think we should specify any version number, be it 4.0, 3.7, or even 3.6. This version is already and will coninue to be quite different from the official 3.6, and referencing ourselves even partially as 3.6 might create some confusion, specifically for newcomers. We also don't need to put 3.6 in the name because it is implied we are working off the last official release.

**Comment by bb010g** [comment]
My issue with Community Edition is that it would conflict with [/r/SSBPMCE](https://reddit.com/r/SSBPMCE), and I don't really want more confusion there. I wouldn't mind dropping the version number.

**Comment by ghost** [comment]
@bb010g that subreddit has to be the stupidest thing i've ever seen. why the hell is there this AND that? just to add more confusion? are you so desperate to pretend to be PMDT? close that shit down, jesus christ.

**Comment by jgd124** [comment]
I vote for stripping the number and just calling it "PM" with no suffix.

Simple, clean, and it appropriately removes this from the PMDEV timeline.

**Comment by bb010g** [comment]
@jgd124 The problem with just calling it PM is that it's ambiguous, and sounds official, which we aren't.

@pharoahfawcett CE is not in any way competing with this project. Right now, it's just the subreddit so people actually have a place to talk about this sort of thing. The last thing I want to be is PMDT. :)

**Comment by jgd124** [comment]
@bb010g Well then calling it /anything/ is problematic isn't it?

People are worried that calling it 3.6.1, 3.7, 4.0 would imply that this project is somehow supplanting the DT's original work. 

You already said that CE would compete with whatever that sub is doing.

GOLD is what 3.6 is being referred to as now... so that's out.

---

I'm switching to PM 3.CC

That said, this is probably the least pressing issue of them all.

**Comment by bb010g** [comment]
3.CC LGTM.

**Comment by bb010g** [comment]
3.CC LGTM.

**Comment by bb010g** [comment]
3.CC LGTM.

**Comment by bb010g** [comment]
3.CC LGTM.

**Comment by Jeelix** [comment]
This is unlikely, but if no other continuation projects crop up, that /r/SSBPMCE could be dedicated to this project. If that happens, there wouldn't be any confusion. This project's mission statement is more conservative than the others that we've seen, and that may help in the long run in terms of popularity and adoption.

The problem with 'Complete' to me, whether it's in 'Community Complete', 'Complete Edition' or just 'Complete' is that it imples that the project is complete, which this won't be for a long time. I guess you could say this is more complete than anything else so far, but this is still quite rough around the edges. It's an innacurate name for now, but the name could be appropriate for later iterations.

I feel having no suffix and calling this just "PM" or just "Project M" would be even more confusing than if we added a version number. I would only consider that if this became the de facto standard version of Project M.

We could take a different naming approach and name this:
Project M+
Project M C (with 'C' having no explicit meaning)
Project M Net (with 'Net' meaning that it is the net total of the latest PMDT builds)
Something else

We don't have to remain in the set of words we've been juggling with in here to name this. I just don't want this to end up being called something stupid like "The New Project M".

**Comment by jojmaht** [comment]
The pull request is live at #60

**Comment by ewmb7701** [comment]
Alright, I merged the pull request. Project M: CC (Community Complete) it is.

**Comment by bb010g** [comment]
We should probably change the repo name too while the project is still young. `Project-M-CC`?

**Comment by ewmb7701** [comment]
Yeah that's a good idea. Do you know if old links will get redirected?

**Comment by bb010g** [comment]
Not sure, but I can at least go edit or comment with fixed links where ever they are on Reddit if not. Better to get this done earlier than later.

**Comment by ewmb7701** [comment]
True. Alright I'll change the name of the repository.

**Comment by bb010g** [comment]
Looks like they redirect, but I'll still go put out the new name for clarity.

**Comment by jojmaht** [comment]
Maybe we could also create a github organization in order not to tie the
project to a particular user.

**Comment by bb010g** [comment]
We should probably wait on an organization until later.

**Comment by ewmb7701** [comment]
Oh is that how organizations work? Yeah that's a good idea, but I agree. We should wait on an organization, at least until the drama dies down.

**Comment by bb010g** [comment]
I'm seeing 3.6 CC and Project M 3.6 : Community Complete in the build. Aren't we doing just 3.CC and Project M: Community Complete?
