### ISSUE TITLE
Lyn Side B: uneven effects

### ISSUE THREAD

**Issue by UltraSyko** [TheOriginalSINe/Project-M-CC#170]
I don't think this was mentioned before 
![00000000-315](https://cloud.githubusercontent.com/assets/16283463/11772775/e9e83738-a1ee-11e5-9eda-0ac76e2ab9a5.png)

I'm not sure if this is how it's supposed to be but I think it should be adjusted

**Comment by ghost** [comment]
Can you please give more details about what exactly the issue is?

**Comment by UltraSyko** [comment]
The white streaks don't align with the flat 2D aura
![00000000-316](https://cloud.githubusercontent.com/assets/16283463/11791790/b3ce0376-a270-11e5-9601-13d5ebfdceb0.png)

**Comment by ghost** [comment]
Aaah, now I get you. Ok this will get looked at.
