### ISSUE TITLE
RFC: Sky Sanctuary Zone (Knuckles' home stage)

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#174]
There's been some nice discussion on [SmashBoards](http://smashboards.com/threads/official-stage-discussion.372723/page-38#post-20587778) about Sky Sanctuary Zone's viability as a competitive stage. It's legal in Australia, it's a quality stage, and we need a home stage for Knuckles. I'd suggest putting it for now as a L alt for Yoshi's Island (Brawl). (It seems to fill that spot on a lot of stage lists, and the alt slot is open.)

**Comment by ghost** [comment]
Also, we can use wiiztec's Alt Song Forcer code for t to have it's songs be independent from the Yoshi's Island ones.

**Comment by JCOnyx** [comment]
Or we can put it as an alt on GHZ, and have GHZ Brawl be a secret alt via Z.  That would make the most sense to me at least.

**Comment by ghost** [comment]
I'll have to disagree on this change. Adding extra stages in can be done in custom builds after the fact. This doesn't fit the project's scope. "It is also not a new custom content mod. "

The stage is not PMDT's work, and it is not a requirement for Knuckles, or any character, to have their own stage. Also, Knuckles and Sonic are both represented by GHZ as well as Kirby and DDD are represented by Dreamland. Or Fox Wolf and Falco are represented by Corneria and Lylat Cruise.

**Comment by oXMugetsuoXo** [comment]
I second Azuran here. As much as i love more competitive stages i feel they should stick to custom builds. If i want it ill add it myself.

**Comment by Eltrion** [comment]
Perhaps in a fork. But not in the main project.

**Comment by Yohan1044** [comment]
I third omission. Scope of project is to tie up PMDT loose ends, allowing for some poetic license. But this is just adding content. I've a good 30 stages added to my CC-custom build, but the only stages to even consider adding to CC are those left out from Brawl (GreenGreens, MarioBros., MarioCircuit, 75m, MushroomyKingdom)

**Comment by pharoahfawcett** [comment]
I fourth it. Not only do I not like the look of the stage, it goes beyond the project goals.

Also, it's legal in one group in Sydney, which does not qualify as "legal in Australia". In that case, I'm designating Port Town Aero Dive as a legal starter in America

**Comment by jgd124** [comment]
Fifth. Love the stage, but this goes beyond the project goals.

**Comment by jojmaht** [comment]
Sixth.
Outside of scope.

**Comment by ghost** [comment]
I would like to continue this discussion. Knuckles is a new character - and when new characters get added in about any other game, they get a new stage.

**Comment by JackpotSHUnited** [comment]
That's not true in the slightest.

Besides, Knuckles already has Green Hill Zone as a home stage.
