### ISSUE TITLE
Knuckles

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#177]
Just updated and noticed some things with knuckles.
-His CSP Green color is not aligned with the rest of his alts.
-His CSP while a nice pose still looks bad and not consistent with the other characters CSPs "look" wise. 
-In game some of his colors "ball form" when jumping do not match the color of knuckles.

**Comment by ghost** [comment]
Can you please make separate issues for each of these?

**Comment by oXMugetsuoXo** [comment]
Sure thing. Regarding his CSP not matching the rest of the cast. Thats more of a personal gripe so ill just ignore that one.
