### ISSUE TITLE
Knuckles: DDD Down throw issues

### ISSUE THREAD

**Issue by chickangamer** [TheOriginalSINe/Project-M-CC#178]
When knuckles use his down throw on DDD he punches the floor while ddd is on the ground behind him

**Comment by chickangamer** [comment]
![1214151801 1](https://cloud.githubusercontent.com/assets/16257911/11798099/98720042-a28d-11e5-93c1-d5f758fff20d.jpg)

**Comment by ghost** [comment]
This is already covered in another issue. Down throw has some oddities with other characters in general. Closing.

**Comment by chickangamer** [comment]
Did anyone made an issue that knuckles aheild don't cover his whole body

**Comment by bb010g** [comment]
I don't know; use the repo search functionality in the top bar. If not, make one.

**Comment by bb010g** [comment]
Also, **_never**_ name an issue like that. Issue names need to be descriptive.
