### ISSUE TITLE
Knuckles Green Alt.

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#179]
When cycling through Knuckles alternate colors you can tell his green color is not aligned with the rest of his CSPs.

**Comment by pharoahfawcett** [comment]
doesn't seem to be that way in brawlbox

**Comment by Kosyne** [comment]
It's fine for me in-game. (dolphin 4.0-7840)

**Comment by oXMugetsuoXo** [comment]
Well this was before Knuckles had his CSP reverted.
