### ISSUE TITLE
Sami: Announcer, Moveset, Taunts, Voice, etc.

### ISSUE THREAD

**Issue by jojmaht** [TheOriginalSINe/Project-M-CC#18]
I know Sami isn't a top priority right now, or even a priority at _all_ but the files are here, so we should establish a roadmap on what to do with her.

**Comment by ewmb7701** [comment]
Alright, I added labels and a milestone.

**Comment by ghost** [comment]
Honestly, we shouldn't worry about her. She has barely any unique animations, no voice clips afaik, and no individual slot. If we manage to make another slot for her, then we should work on her. But it might be best to just leave her alone.

**Comment by thesmashking25** [comment]
We could pull her voice clips from advanced wars directly, although she doesn't talk much. We could remove the random slot entirely to make room for her (and resemble the melee character select screen). I think we could pull this off if we could find a decent psa on brawl vault.

**Comment by dcampora** [comment]
There are indeed voice clips from some voice actress. Still, I don't think you guys should care about Sami at this stage.

http://www.20xx.me/files/theme/sami.mp3

**Comment by cykeswiki** [comment]
https://www.reddit.com/user/PyotrLuzhin

This user on reddit managed to give Sami her own slot, and then I made her CSP and BP and stuff like that.

http://imgur.com/a/0SX88

**Comment by jojmaht** [comment]
@amircury Looks good. Can you do a pull request?

**Comment by bb010g** [comment]
I'll just go see if I can get Pyotr over here to be able to do things directly. @skinnyfoetusboy They haven't released anything yet.

**Comment by cobalt-blue** [comment]
I have to say her moveset seems to be a hell of a lot more complete than Isaac's - remember, she was intended to be a clone of snake, most of the unchanged/copied moves are probably supposed to still be there. too bad that she doesn't have a slot on the select screen yet.

**Comment by jojmaht** [comment]
Closing this issue, as #112 is more recent and better describes the situation.
