### ISSUE TITLE
Knuckles Alt Jumping Color

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#180]
When jumping knuckles enters a "ball form". While using some of  his alternate colors not all of them have a matching "ball form".

**Comment by somealternateaccount** [comment]
Needs testing as to whether this happens with Sonic as well.

**Comment by oXMugetsuoXo** [comment]
Pretty sure i tested it and it doesnt happy  with sonic.

**Comment by bb010g** [comment]
Yeah. We probably could look at Sonic for an example of how to fix this.

**Comment by ghost** [comment]
I think this can only be addressed once we nail down which Knuckles costumes will get implemented.

**Comment by ghost** [comment]
This should be closed, as the new Knuckles costume set doesn't have this issue.
