### ISSUE TITLE
Lyn:Bair/Back Aerial Attack--  Auto Cancels..?????

### ISSUE THREAD

**Issue by SzionBlue** [TheOriginalSINe/Project-M-CC#184]
So, i see we have some down b and neutral b balancing, think we can wrap this up with some end lag on back air? It's powerful, it's safe, the shield pressure's incredible and makes for a good Reverse Aerial Rush approach. No endlag upon landing..has some endlag if you're airborne long enough to experience it..which is unlikely. 

SO

How 'bout it? Anyone willing and have the time to look into this? 

Edit: oh right the issue...Auto Cancelling is too good for this character..or so i'd think. Landing lag for this move wouldd be greatly appreciated.

**Comment by jgd124** [comment]
I think that you're on the right track, guy.

And the good thing is, it's being worked on. The issue was so glaring that it was one of the first to be brought up re: balancing Lyn. For some reason, I thought this was solved back in issue #48.

Any thoughts, other guys? Was this issue already closed or no?

**Comment by SzionBlue** [comment]
I had no clue it was already up for discussion, i was looking around and didnt see it..

im like "there's noway they haven't seen this..there's just no way" xD

**Comment by jgd124** [comment]
Yuppers. By far one of the most redonkulous things about her character. http://www.gfycat.com/PlaintiveCrispAmazondolphin

**Comment by SzionBlue** [comment]
DANG look at that crystal clear framerate. I can't believe that's even possible. So smoothe..I feel like thats even better than the game right off the wii itself..

Edit: with 48 looks like it was fixed. ill grab this fix immediately!

**Comment by ghost** [comment]
So, AFAIK, Lyn has landing lag on bair now. Closing.
