### ISSUE TITLE
Isn't Kirby's 3.61 Ganondorf ability kind of useless?

### ISSUE THREAD

**Issue by JackpotSHUnited** [TheOriginalSINe/Project-M-CC#185]
Why would Kirby need a cape reflector against a character that has no projectiles?

I know we want to keep all of the 3.61 bugfix changes intact, but I really think we ought to make an exception for Kirby's Warlock Punch.

**Comment by thesmashking25** [comment]
Bruh, there is more multiplayer than just 1v1. @JackpotSHUnited

**Comment by JackpotSHUnited** [comment]
I understand that, but then you're forced to deal damage to your teammate if you want to take advantage of a niche ability.

**Comment by thesmashking25** [comment]
@JackpotSHUnited Some people play free for all

**Comment by Nekudot** [comment]
Kirby's ability is to copy the Neutral B of the other character no matter how useless it is. What happens when Kirby absorbs DDD? Wario?

**Comment by thesmashking25** [comment]
This shouldn't be an issue.

**Comment by UltraSyko** [comment]
@thesmashking25 Agreed

**Comment by ewmb7701** [comment]
This isn't an issue. The reflector's best use isn't to reflect projectiles. Closing issue.
