### ISSUE TITLE
Lyn down taunt

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#191]
Her right arm (sword arm) bends awkwardly in the middle of her d-taunt.

![lyn](https://cloud.githubusercontent.com/assets/16313695/11828844/1b6789e4-a366-11e5-82ea-55bdb20fd107.PNG)

**Comment by ghost** [comment]
Also, Lyn lacks a unique down-taunt in general AFAIK. It's a copy of one of her other taunts atm.

**Comment by MrGameCrazy** [comment]
I believe the down-taunt is a copy of the side-taunt atm.

**Comment by bb010g** [comment]
Subsumed by #305
