### ISSUE TITLE
ROB Special Costume Stock Icons Error

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#193]
ROB's special costume stock icons (Virtual Boy and Wii costumes) don't match up with their character icons.

Virtual Boy ROB:
![00000000-62](https://cloud.githubusercontent.com/assets/16161703/11832971/c74735ee-a383-11e5-9f0b-a65b710dcf55.png)

Wii ROB:
![00000000-63](https://cloud.githubusercontent.com/assets/16161703/11832975/ca972bd2-a383-11e5-8e1a-316e71c6fb97.png)

**Comment by Tac24** [comment]
this is the case with several characters- mostly their alt costumes or other colors

**Comment by MrGameCrazy** [comment]
Oh. Thanks for letting me know.

**Comment by Tac24** [comment]
Yea recheck all the battle portraits for every character- bloody tedious
but it's for completion

Also I know there were more custom drawn portraits.... can we use those for
the characters who didn't get their art updated?

**Comment by MrGameCrazy** [comment]
Will do that.

**Comment by Tac24** [comment]
While I couldn't find the Files on brawl vault

http://www.nintendojo.com/news/underground-smash-bros-mod-project-m-closes-shop

The picture here shows the custom CSS I speak of.

Maybe use the unchanged ones to keep the flow of custom art?
