### ISSUE TITLE
Knuckles: Wall Climb Ledge Interactions

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#196]
When wallclimbing, knuckles won't grab ledge unless he goes near it and starts climbing down. When he wall climbs onto stage, the animation looks unnatural as he transitions into a falling animation and "falls upwards".

Suggested fix: Either A) Give knuckles an animation to transition from wallclimb to onstage (possibly his ledge getup animation)

Or B) Figure out a way to force Knuckles to grab ledge when he gets near enough, even if he has no downward momentum.

**Comment by somealternateaccount** [comment]
I'm not sure this is necessary - as it is, the Knuckles player can choose whether or not to ledgegrab.

An alternative solution might be to remove the ledgegrab box from the animation and force Knuckles to go onstage, but that feels kind of weak and is probably a balance change.

The only way spacie up-b's could grab the ledge from below is to run out of distance while near the ledge or hit the stage in such a way that it slows or stops them climbing the wall, allowing them to run out of distance near the wall.

**Comment by Hellraz0r** [comment]
Appears to be intended. You can still sweetspot (by sweetspot I mean grab the ledge w/o going over the base of the stage) the ledge while wallclimbing but it takes a bit of timing practice and a specific input.

**Comment by vinegar97** [comment]
maybe instead of snapping to the ledge, you could have him climb up the ledge to the floor, though i imagine that would require some knowledge in PSA and a new animation.

i realize my suggestion isn't actually a "fix", but i think it could be better than how awkward it is now.

**Comment by ghost** [comment]
The real issue I found is that him climbing onto stage is a really odd interaction, both functionally and animation wise.

**Comment by vinegar97** [comment]
to clarify, i meant disable the grabbox altogether when clinging on walls and have him automatically go up the ledge when at the end of the wall, similar to how its done in 2D sonic games.

you know, i'm not even sure that's possible.

**Comment by Hellraz0r** [comment]
That's pretty much how it already works. He only grabs the ledge if he lets go (either by input or timeout).

**Comment by ghost** [comment]
This seems to be fixed in the newer Knux leak,along with the odd stick sensitivity used in wall climbing. In other words, I can climb by tilting the stick straight up now, and grab the ledge by simply climbing up until he grabs it.
