### ISSUE TITLE
PAL Version

### ISSUE THREAD

**Issue by LoanSPW** [TheOriginalSINe/Project-M-CC#199]
As you know, the team always wanted to release a PAL version. However due to PM's cancellation, an official PAL Version will never happen...

So i think that it could be a Great idea to create a PAL version of the Community Edition, so the Europeans could play the ultimate version of PM ever.
Doing such a thing isn't impossible (a team is actually working on making a PAL version of 3.6, with so far 106 of the 500 codes already ported in 4 days) but time consuming due to added glitches...
So of course, PAL version should be made when the Community Edition is considered finished, cause redoing it again and again would be stupid.

What do you think? :) (Also sorry for my bad english, I try my best...)

**Comment by ghost** [comment]
For the record, the Project is Community Completion, not to be confused with the Reddit hub named PM Community Edition.

Second, this isn't in the scope of our project. At the very least not the first release. A PAL codeset was not in any of the leaks and would take a considerable amount of extra effort to implement. It seems especially futile if others are already doing almost identical work for 3.6.

If someone else wants to take the CC release when it's out and make a PAL version of it, they are free to.

My 2 cents.

**Comment by bb010g** [comment]
Someone on /r/SSBPM is starting work on a PAL port, and it's not a small task. _Maybe_ in the future, but that's far down the line.

**Comment by ghost** [comment]
Ok, 2 collabs said no, closing this for now.
