### ISSUE TITLE
Right arm (sword arm)

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#201]
various moves leave her arm disfigured.

![arm](https://cloud.githubusercontent.com/assets/16313695/11858224/9f187e84-a42d-11e5-8cf8-38c17eec757c.PNG)

![vantage hand and arm](https://cloud.githubusercontent.com/assets/16313695/11858240/cb8977fc-a42d-11e5-82ad-a734903f41d8.PNG)

![vantage](https://cloud.githubusercontent.com/assets/16313695/11858245/e4e8f6d2-a42d-11e5-8998-ae23cb5b8291.PNG)

**Comment by ewmb7701** [comment]
Ew. Which moves are these?

**Comment by ghost** [comment]
@bb010g this is covered in a general animation polish issue. Please close.
