### ISSUE TITLE
Hand positioning

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#202]
Her hand grabs next to the hilt of her sword in some of her attacks, or are not doing anything.

![down smash](https://cloud.githubusercontent.com/assets/16313695/11858267/0aa0e006-a42e-11e5-843e-493af437f063.PNG)

![forward tilt](https://cloud.githubusercontent.com/assets/16313695/11858281/2726c5f6-a42e-11e5-9cce-782285cfc231.PNG)

![hand positioning](https://cloud.githubusercontent.com/assets/16313695/11858285/34890e70-a42e-11e5-9b5f-ebc0c1c1b23b.PNG)

![vantage hand and arm](https://cloud.githubusercontent.com/assets/16313695/11858304/54261c14-a42e-11e5-8ff7-b5c89f3a723a.PNG)

**Comment by ghost** [comment]
@bb010g this is covered in a general animation polish issue. Please close.
