### ISSUE TITLE
CSS layout with new characters

### ISSUE THREAD

**Issue by AgentBlizz** [TheOriginalSINe/Project-M-CC#203]
This is very far down the line but I noticed that when we get another slot for Sami, with 46 spots (including Random) the organization of the CSS icons will need to be changed.

Proposed Solution:
I made a concept CSS screen inspired by 3.6. A final decision doesn't need to be made now but I thought it would be a good idea to have an idea what we want it to look like for the final release.
http://i.imgur.com/m44G59R.jpg

**Comment by meta-neo-omega-ridley** [comment]
Why don't we just change the CSS icons all-together? This one brawl mod I fond looks like this. Not this exactly, but something of the sort should be incorporated. It fills out nicely, and gives the CSS an interesting look.

![purplee](https://cloud.githubusercontent.com/assets/16313695/11858500/3a9eeb8e-a430-11e5-9304-1e4a2ece9cdf.jpg)

**Comment by ghost** [comment]
@meta-neo-omega-ridley Overhauling the CSS is not in the project scope.

@AgentBlizz For the first major release, I don't see the issue with simply removing Issac from the menu and centering the bottom row.

**Comment by meta-neo-omega-ridley** [comment]
Isaac is unplayable now, but what will happen once he's completed?

**Comment by bb010g** [comment]
The sooner we get Sami on the CSS and easily testable, the better.

**Comment by ghost** [comment]
Changing labels. Everything Sami and Issac related are low priority.

**Comment by shitaki** [comment]
@meta-neo-omega-ridley what brawl mod is that? I would like the css and the menus to change eventually but I know there are more important things. I know there's a css editor right?

**Comment by Eltrion** [comment]
make the character select boxes slightly narrower, arrange it 4x12, cut out the two bottom corners, done.

**Comment by somealternateaccount** [comment]
There's been several mockups of a 9, 10, 10, 9, 8 layout, which accomodates 46, making room for Isaac, Sami, Lyn, and Knuckles.
![css_final](https://cloud.githubusercontent.com/assets/16196962/11862642/042a6164-a453-11e5-9559-116021a6f368.jpg)
This is the one I'm partial to - it's similar to the 3.6 CSS while grouping series together well.

**Comment by andy-bond** [comment]
I like the image that @somealternateaccount posted above. It keeps things close to where they were so that people don't have to search for their main.

**Comment by oXMugetsuoXo** [comment]
the CSS screen shown in the beginning of this video looks nice. https://www.youtube.com/watch?v=LQCmLkHjkWI Pretty sure it would fit 46 characters aswell.

**Comment by ghost** [comment]
@somealternateaccount going to reiterate that Sami and Issac won't be on the screen for first release, so a design should be decided on for 44 (9, 9, 9, 9, 8 seems most straightforward)

![image](https://cloud.githubusercontent.com/assets/7049878/11872337/b8ad087c-a4a2-11e5-9044-84801667610a.png)

**Comment by PyotrLuzhin** [comment]
hopefully tonight I'll upload the sami css fix

**Comment by bb010g** [comment]
:+1: for those last two designs.

**Comment by ewmb7701** [comment]
I like the second second one better, but Olimar should be in the far left instead of the right.

**Comment by AgentBlizz** [comment]
I like the latest 2 proposals for the 46 and 44 slots, respectively. Both keep the characters in familiar places. I also agree with TheOriginalSINe with moving Olimar to the far left at the bottom of the 44-char one, keeping sonic and knuckles at the far right

**Comment by ghost** [comment]
Updated the Release 1 CSS Mockup with Olimar moved as per feedback.

![image](https://cloud.githubusercontent.com/assets/7049878/11880246/a99953c4-a4cd-11e5-9ea4-f3444e54f4f6.png)

**Comment by AgentBlizz** [comment]
Looking good!

**Comment by oXMugetsuoXo** [comment]
Every character has their series others side by side horizontally  but Samus and ZSS are vertically? Doesnt matter though just eats at me on the inside lol.

**Comment by pvrker** [comment]
I like @somealternateaccount's final CSS, only change I'd make is moving the Metroid series inbetween Zelda and Starfox. Makes it a bit more similar to Melee's CSS and also puts Ganon beside Cpt. Falcon.

Anyways here's mine:

![image](https://cloud.githubusercontent.com/assets/16171785/11883058/4b82b5a8-a4de-11e5-88ff-deeafe4e95dc.png)
- quite similar too Melee CSS
- has third parties off to the corner
- all (semi)clones are beside eachother

@Azer-X's first release CSS is nice aswell but Pokemon series being interrupted by Random and Samus and ZSS being seperated kinda irks me. I don't really know how to fix it though.

**Comment by AgentBlizz** [comment]
I still like somealternateaccount's better, as I'd rather the CSS be closer to 3.6 than melee

Oh and @PyotrLuzhin when you put in the new sami slot can you organize the CSS like the one somealternateaccount put up please?

**Comment by PyotrLuzhin** [comment]
@AgentBlizz I'll see what i can do

**Comment by UltraSyko** [comment]
I honestly like what we have have already. Me personally, I'm not a fan of the Random slot being in the middle. But I think what we have should stay. 
If any changes 
We should attempt this:
![05](https://cloud.githubusercontent.com/assets/16283463/11911024/62f340d8-a5d6-11e5-8ecd-8bd94b54e654.png)

**Comment by oXMugetsuoXo** [comment]
^I like this

**Comment by Nekudot** [comment]
I don't like the 1st Release CSS with Samus in 2 different rows and the pokemon split. Push Samus to the third row, Random to the bottom right and someone from the bottom row (MrG&W? Pit?) to the second one. Or use the one we have now, only remove isaac from it.
I like Psycho_Hedgie mockup for a final release with Sami and Isaac, but that would leave no spot for Random. Maybe adding invisible Random tiles to the left and right of it would be acceptable?

**Comment by Grangach** [comment]
I like random being in the middle.

**Comment by Shin-F** [comment]
Hi there, been lurking for a while and figured I'd weigh in on this subject a bit. 

For the final roster of 46, I think a 10-10-10-9-7 would look the most natural. Smash 3DS used a similar arrangement for its initial roster (9-9-9-9-8-6) and that looked pretty good. With that in mind, I made one here with the current official arrangement in mind, with the changes from that one being minimal. (Pit moved to top to make room for Lyn with other FE characters, Isaac below him. Knuckles put next to Sonic, Olimar moved beside Samus to make room for Sami next to Snake. Everything else basically in the same place as the current official release.)

Excuse the fact I didn't use the actual PM CSS for this arrangement, but I already had these icons on-hand and it was just easier and faster this way. 
![m](https://cloud.githubusercontent.com/assets/16230973/11919982/c8e83a64-a726-11e5-960d-ffa744aef8ab.png)

**Comment by chickangamer** [comment]
That's awsome

**Comment by oXMugetsuoXo** [comment]
Ice climbers/Isaac should be dropped from second row. Move Samus and ZSS to the right side of the second row to complete it.

**Comment by JackpotSHUnited** [comment]
I feel like clone characters should always be touching the box of their original.

Pit should be next to Lyn and the other Fire Emblem characters.

Isaac should be next to Toon Link and the other Legend of Zelda characters.

**Comment by oXMugetsuoXo** [comment]
That makes no sense >.>

**Comment by JackpotSHUnited** [comment]
That's how it was in Melee.

Dr. Mario was next to Mario.
Ganondorf was next to Captain Falcon.
Falco was next to Fox.
Young Link was next to Link.
Pichu was next to Pikachu.
Roy was next to Marth.

Roy was cloned from Marth.
Mewtwo was cloned from Lucario.
Knuckles was cloned from Sonic.
Lyn was cloned from Pit.
Isaac was cloned from Toon Link.
Sami was cloned from Snake.

It is worth noting that Isaac, although cloned from Toon Link, also seems to have some of Ike's attributes as well.

The row could go: Pit-Lyn-Roy-Marth-Ike-Isaac-Tink-Link-Zelda-Sheik with Ganondorf and Captain Falcon above Zelda and Sheik, similar to how Ganondorf was near the other Zelda characters in Melee, but not on the same row.

**Comment by oXMugetsuoXo** [comment]
Apart from Ganondorf every other character was from the same background. That is why they were placed next to each other. 

I wish Project ganondorf filled the current ganon spot and then old one was taken for Black Shadow and placed next to cap. It would be my dream come true :D

**Comment by Shin-F** [comment]
Although Lyn and Pit are, technically speaking, cloned and altered from Pit and Toon Link / Ike, they hold little resemblance outside the portions of their moveset that are incomplete, so I saw no need to put them together, unlike Sami who still retained several Snake-like aspects. 

That said, as I was moving the roster around to take the Metroid / Icies / Isaac feedback into account, I decided to play around with the idea anyways. 
![mrevised](https://cloud.githubusercontent.com/assets/16230973/11921271/db4631f6-a74a-11e5-95c2-cb27b484eedb.png)
Samus and Zero Suit Samus moved up a row, Zelda franchise is on the end again. Captain Falcon moved so he still remains in vertical contact with Ganondorf. Pit moved to third row instead of Ice Climbers so he's now connected vertically to Lyn. Isaac now connected vertically to both Toon Link and Ike. 

Pit and Isaac look nice next to one another as well, which is a nice little plus.

**Comment by Willstolife** [comment]
I wonder why Pichu and Young Link who are the last 2 veterans from Melee still aren't in? Mean the icon for Pichu were leaked as well.

**Comment by Nekudot** [comment]
Isaac and Sami still need a lot of work, more characters may come later. I don't understand why people want a third Link in the game, if you don't like Toon Link replace him in your build with Young Link :/

**Comment by Willstolife** [comment]
Well, Young Link can be a character who is in the middle between Link and Toon Link on Smash, Throws and Specials. And if not, least be like an alt for him.

**Comment by JackpotSHUnited** [comment]
We'd only be adding characters that were actually planned for Project M. As of right now, the only two that we know of that were ever considered for the final slot were Skull Kid and Ridley.

**Comment by bb010g** [comment]
A friendly reminder that discussion about _new_ new content (e.g. Skull Kid & Ridley) is tabled until February.

**Comment by thesmashking25** [comment]
CAN WE PLEASE MOVE WARIO!!!

**Comment by ghost** [comment]
Covered in newer issue. Closing.
