### ISSUE TITLE
Sheath

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#204]
F-air make her sheath face the opposite direction.

![sheathe](https://cloud.githubusercontent.com/assets/16313695/11858318/7c1927a2-a42e-11e5-9679-ca9b0f10446b.PNG)

**Comment by AgentBlizz** [comment]
it looks fine to me. It's just rotated, with the axis being the belt

**Comment by meta-neo-omega-ridley** [comment]
I just thought it should be consistent through-out.

**Comment by AgentBlizz** [comment]
oh i see now.
yeah i wouln't mind if it was changed to be pointing downward, but I kinda like it like that, as if Lyn was falling and the sheath flew upward because of air resistance

**Comment by meta-neo-omega-ridley** [comment]
This way does make it seem more realistic, but in that case, this should be for all of her airs. That would be pretty nice. I now view this totally differently. Not as an issue, but as a step towards awesomeness.

**Comment by Nekudot** [comment]
Can the sheath have gravity applied to it? Because if it looks like that while ascending then it breaks the effect. And the amount of clipping in that image is disgusting.

**Comment by meta-neo-omega-ridley** [comment]
That's Dolphin screen-shotting in a nut-shell.

**Comment by ghost** [comment]
@bb010g this is covered in a general animation polish issue. Please close.
