### ISSUE TITLE
Standing

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#205]
Feet don't touch the ground.

![standing](https://cloud.githubusercontent.com/assets/16313695/11858324/9a957690-a42e-11e5-9bd7-1ea3e50e2bf2.PNG)

**Comment by ghost** [comment]
@bb010g this is covered in a general animation polish issue. Please close.

**Comment by bb010g** [comment]
Subsumed by #305
