### ISSUE TITLE
Knuckles: Final smash

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#207]
In Knuckles' final smash, he should transform into Super Knuckles. In gameplay, when he transforms, his powers are enhanced (glides further, jumps higher). Just read this to get the idea: http://sonic.wikia.com/wiki/Super_Knuckles

**Comment by ghost** [comment]
Knuckles has a super knuckles final smash in the works but there is no issue open for this.

Lyn's final smash is covered in #138 

Isaac and Sami both have a while to go before we work on final smashes. Separate issues should be created to discuss them.

**Comment by UltraSyko** [comment]
Is this okay?
![00000000-118](https://cloud.githubusercontent.com/assets/16283463/11888739/1f9254cc-a50f-11e5-994b-347704ba2671.png)
Because frankly, the Super Bubbles are dumb

**Comment by ghost** [comment]
@Psycho-Hedgie , Program in the discord chat has been working on a massive revamp of it into Hyper Knuckles, with the S3&K glide, Super Emeralds, glowing fur, and everything. I suggest that you wait on that.

**Comment by meta-neo-omega-ridley** [comment]
Is the final smash going to be identical to Sonic's?

**Comment by ghost** [comment]
Not quite, he'll at least have the different hitbox positioning involved in Knuckles' Side B glide attack, if not a unique hitbox on his fists themselves. also, the changes in the above comment I made.

**Comment by meta-neo-omega-ridley** [comment]
That's going to be one hell of a final smash. One of the best, I might add.

**Comment by JackpotSHUnited** [comment]
Wait, shouldn't we just make it a clone of Sonic's but with Super Knuckles instead? That's probably what the PMDT would have done, seeing as even Mewtwo has the same Final Smash as Lucario.

**Comment by ghost** [comment]
The difference between Super Sonic and Super/Hyper Knuckles is that Program's Final Smash will work the way Knuckles' actual forms work, which is with the glide and emphasis on the fists.

**Comment by Darquezze** [comment]
I think the difference between Sonic's and Knuckles' is that Knuckles could have more power, is slower, and the final Smash duration is shorter than Sonic's

**Comment by Darquezze** [comment]
And how about instead of the bubbles, have the master emerald go inside him (like how the chaos emeralds go into Sonic)

**Comment by LnktheWolf** [comment]
@rage17 any news on Program's hyper knux?

**Comment by ghost** [comment]
@LnktheWolf Still waiting to hear from @Pr0gram on completion of it.
