### ISSUE TITLE
Stages

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#208]
Would adding stages for Isaac and Sami count as part of the mission to finish what PMDT started? Each character does have their own stage...

**Comment by JackpotSHUnited** [comment]
R.O.B. does not have a stage.

**Comment by meta-neo-omega-ridley** [comment]
But R.O.B. is like 10% of a character. Golden Sun and Advance Wars are fairly renown among Nintendo fans. Brawl did give him the Famicom stage, but no one liked him, so they took it away for Fountain of Dreams.

**Comment by ghost** [comment]
No unfortunately. The project scope is finishing leaked content. Issac and Sami do not need dedicated stages to be "complete" characters and are both low priority. Closing.
