### ISSUE TITLE
Knuckles: Victory animation

### ISSUE THREAD

**Issue by PKPenguin321** [TheOriginalSINe/Project-M-CC#21]
Knuckles shares victory animations with Sonic. His mouth will move, but he lacks voice lines.

Also, I found that if Sonic is the defeated opponent, Knuckles will speak Sonic's respective voice lines.

**Comment by PKPenguin321** [comment]
> Also, I found that if Sonic is the defeated opponent, Knuckles will speak Sonic's respective voice lines.

https://github.com/TheOriginalSINe/Project-M-CC/issues/81 seems to be the cause of this.

**Comment by bb010g** [comment]
Closing as duplicate.

**Comment by PKPenguin321** [comment]
Not a dupe, the main issue is 

> Knuckles shares victory animations with Sonic. His mouth will move, but he lacks voice lines.

which from what I can tell is not covered anywhere else.

**Comment by bb010g** [comment]
It's the same issue: Knuckles is missing clips and will take Sonic's sounds in a match with him. The fix is the same.

**Comment by PKPenguin321** [comment]
Fixing the sound will not give Knuckles new victory animations... Sound != animations.

**Comment by bb010g** [comment]
Sorry, I missed the bit about the same animations. _derp_

**Comment by PKPenguin321** [comment]
Not sure if the voicelines issue has been fixed yet, but victory animations have been added, although they are rough. https://github.com/TheOriginalSINe/Project-M-CC/issues/246 covers the issue better. Closing this.
