### ISSUE TITLE
SSS Preview Resolution and Stock Icons

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#211]
Previously, we had a dillema where it seemed that the only way to restore stock icons to the SSS was to shrink the SSS Prevbase textures. There was a bit of a divide around here on whether to have stocks or full res Prevbases. Today, I found a solution that lets us have both. Link is here: https://cdn.discordapp.com/attachments/123214554363723782/127069048214257664/sc_selmap.pac

**Comment by ghost** [comment]
Restoring stock Icons is not part of the scope as we have no evidence from leaks that PMDT were attempting to do so.

It seems that they removed them on purpose. In the old builds' SSS, there was an open space where the stock icons went:
![image](https://cloud.githubusercontent.com/assets/7049878/11874142/2c5aec68-a4ac-11e5-8692-ec6c32efe4d5.png)

In the new builds, the SSS was redesigned and stock icons were removed in order to give larger focus to the Stage Name and Franchise Logo:
![image](https://cloud.githubusercontent.com/assets/7049878/11874224/92b468a4-a4ac-11e5-8faa-b87fd929c04f.png)

Stock icons on the SSS add little to the game and don't mesh well in with the SSS redesign.

**Comment by somealternateaccount** [comment]
+1 Azer-X

**Comment by vdenzen** [comment]
With the extra space from the removed stock icons i thought about making the quality of the stage previews better by using HD stage preview images and upscaling the resolution from 175x175 to 200x200.

example: http://imgur.com/LsusbOR , http://imgur.com/AyWZwfU
And the download link: https://www.dropbox.com/s/hihpclw8sffm2b0/sc_selmap.pac?dl=0

What are your thoughts about this?

**Comment by ghost** [comment]
@vdenzen Hm. On one hand, it's a non subjective change which people could universally agree would increase the quality of the build. On the other, it's potentially out of scope.

Please make a new issue devoted to this potential change for people to discuss.

**Comment by vinegar97** [comment]
even though i really want this to be the main file, i suggest this be included as an optional file, and adding #216 as the standard.
