### ISSUE TITLE
Knuckles: "Explosive" range on fully charged Fsmash

### ISSUE THREAD

**Issue by SzionBlue** [TheOriginalSINe/Project-M-CC#214]
Hits below ledge, in the body, and above. Lingering hitbox. 
Is this how it should be? I think it makes a decent edge-guard at times...that kills.

Anyone wanna weigh in? I mean it's a fully charged Fsmash whatre the odds of you getting hit by this but i just wanted to bring it up just in case...havent seen more than one page of knuckles threads and i've yet to see anything about this in it.

**Comment by ArtfulHobbes** [comment]
An increased hitbox n a fully charged attack isn't anything new. Ike has one on his neutral B. I think its fine if we leave it.

**Comment by ghost** [comment]
Not making balance changes unless a move is unfinished. Closing.
