### ISSUE TITLE
Sonic Heroes Metal

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#215]
So PM added Peach's offical metal form. I want to gauge how much we would be in approval of these official metal forms, as I can implement them.
![image](https://cloud.githubusercontent.com/assets/16145986/11879843/d13d6df4-a4cb-11e5-819e-7ce301fc173a.png) 

So basically, metal box turns Sonic and Knuckles into this, from Sonic Heroes.

**Comment by AgentBlizz** [comment]
I like it.
Not sure how I feel about the evil eyes, but that's up for discussion. It would look more official that way, though.

**Comment by jgd124** [comment]
It's very nice and a fantastic idea, but I believe it is a custom concept beyond the scope of the project.

That said, you have more of a say in this than I, Rage.

**Comment by Eltrion** [comment]
Well, there is a precedent, and if it's a relatively minor effort. It wouldn't affect tournament play.

I don't see why not. Obviously very low priority,  but go for it if you don't have any other things to work on.

**Comment by ghost** [comment]
Question for all: Do we want to have the eyes included, or not. Here's an example of how they look without the eyes: 
![image](https://cloud.githubusercontent.com/assets/16145986/11883166/f5e6c9ee-a4de-11e5-9012-a5d8f5ddcd15.png) 

And with them: 
![image](https://cloud.githubusercontent.com/assets/16145986/11883205/4a51cd62-a4df-11e5-84dd-c53ff0cc014e.png)

**Comment by vinegar97** [comment]
:+1:  for eye to stay true to how the original was.

**Comment by chickangamer** [comment]
I'm down with it it's nothing that can effect tourny

**Comment by chickangamer** [comment]
The one with the eyes of course

**Comment by AgentBlizz** [comment]
omg those eyes look amazing. that metal texture looks amazing. Rage, your work is amazing.
+1

**Comment by ghost** [comment]
Someone suggested that I look into a more Brawlish texture than a flat-out rip, so... 
![image](https://cloud.githubusercontent.com/assets/16145986/11883644/70ecedd2-a4e2-11e5-9c80-d8fa9a5cd25f.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11883902/ff4a8372-a4e3-11e5-8570-f615bcd9a66c.png)

ingame test of new texture. thoughts?

**Comment by Tottle** [comment]
Looks very professional. I love it.

**Comment by chickangamer** [comment]
Awsome

**Comment by andy-bond** [comment]
That looks amazing. Awesome work!

**Comment by bb010g** [comment]
Don't particularly care either way. They're a nice touch.

**Comment by JackpotSHUnited** [comment]
Looks amazing, but not part of project goals.

If these get in, then Metal Kirby from Kirby Squeak Squad should be added.

**Comment by ewmb7701** [comment]
This is kind of out of scope, but it is something that feasibly the PMDT would add in. There's already Pink Gold peach, so there's a precedent for it. That's pretty much what makes this okay as an addition for me.

**Comment by JackpotSHUnited** [comment]
Couldn't the same be said about alt team colors for some costumes, like Beta Knight or Dry Bowser, that got shot down in another issue thread?

**Comment by bb010g** [comment]
Alt team colors are more costume slots, though. Metal Sonic & Knuckles are already here. (Also, [Metal Kirby](http://kirby.wikia.com/wiki/Metal) for reference.)

**Comment by Darquezze** [comment]
@bb010g Yes we need a Metal Kirby too! But I think that's doing to much :/

**Comment by DarkLink1996** [comment]
@bb010g Not sure how possible, or desirable, it is to change a character model by using the metal box.

**Comment by ghost** [comment]
@DarkLink1996 @bb010g Changing models for Metal box isn't possible.

**Comment by Darquezze** [comment]
@Rage17 U can just use the textures

**Comment by vinegar97** [comment]
Special models for metal could be possible if the original model has objects that use a transparent texture without any special shading by default and the metal texture for..well, metal mode.

Keep in mind this is only an idea, i'm not sure how well this actually works.

**Comment by vinegar97** [comment]
In kirby's case, the metal texture would be the texture for the "metal" copy ability if the idea is going to be used.

**Comment by ghost** [comment]
@vinegar97,that's true, never thought about that. Might mess with hats, though.

**Comment by vinegar97** [comment]
Well, you could always keep the top where the hats rest round and change the other parts to your heart's content.

**Comment by vinegar97** [comment]
That might look a little awkward though

**Comment by pharoahfawcett** [comment]
it's cool, I'll ise it, but put it on brawlvault. it has no place in the build. the project goals exist for a reason.

**Comment by bb010g** [comment]
@pharoahfawcett It's fine under project goals. The PMDT has a precedent of doing metal color references.

**Comment by JackpotSHUnited** [comment]
They have precedent of giving team colors to previously introduced alt costumes.

They have precedent of bringing back stages from Brawl to appeal to the causal audience.

They now have precedent of revamping a character's entire model to be more accurate to the source material.

By this logic, things like recolors for Beta Knight and Dry Bowser, the return of Green Greens and Brawl PS2, and using revamped character models are within the scope of the project.

Where do we draw the line?

**Comment by bb010g** [comment]
We draw the line with alt recolors when we don't have the slots. Green Greens' return may fit due to Brawl PS2 and Rainbow Cruise showing up again. We draw the line when no precedent can be shown or it's indefeasible to implement.

**Comment by JackpotSHUnited** [comment]
Bowser has three open slots, enough for team recolors of Dry Bowser (based off of PM:TTYD's Red, Dark, and Dull Bones, perhaps).

Meta Knight has two open slots, just enough for blue and green versions of his Beta Knight alt costume.

Roy also obviously has three open slots for team colors of his Awakening alt costume.

**Comment by pharoahfawcett** [comment]
I'm sorry, but that just seems stupid. I guarentee you that the PMDT were not going to add this obscure Sonic Heroes reference regardless of how cool it is. 

Awakening Roy was planned to have recolors, but I guarentee they wouldn't look like whatever fan colors you guys come up with. Even things like Green Greens and Brawl PS2 are personal choice. The reason they're not using Brawl PS2 is because it won't have SFX if shared with PS1.

**Comment by bb010g** [comment]
Brawl PS2 was already in the build, though. We're not mind readers for alt colors, but we can try to do our best. As for this, I really don't see why the PMDT wouldn't add them. Perhaps someone could explain why if they've talked to a member.

**Comment by JackpotSHUnited** [comment]
@pharoahfawcett An easy fix for the Pokemon Stadium situation exists.

PS2 slot: PS2 (Project M) / PS2 (Brawl)
PS1 slot: PS1 (Sandfall) / PS1 (Melee)
Spear Pillar: Saffron City HD / Spear Pillar / (Saffron City N64)

Making the N64 versions of HD stages hidden Z alts fits in with what's already been done for Hyrule Castle and Peach's Castle. Adding back Green Greens and making Dream Land N64 a secret as well would also fit in perfectly.

**Comment by bb010g** [comment]
@JackpotSHUnited I think that's the sanest stage change set for the build I've heard so far. (IIRC there was talk on the subreddit of getting Sandfall's PS1 in; I can try to find links.) Make an issue! :)

**Comment by bb010g** [comment]
@Rage17 just put this up on Discord:

![Metal Knuckles BrawlBox Screenshot](https://cdn.discordapp.com/attachments/123229282792243203/128362570112434176/unknown.png)

**Comment by jojmaht** [comment]
I think adding those textures would not particularly be out of scope. As long as it doesn't conflict with more important work and it has motivation behind it (i.e not being a Coldsteel The Hedgehog recolor), I think it should be fine.

**Comment by ghost** [comment]
@bb010g Thanks for linking the Knuckles screenshot here. Also, should this get closed?

**Comment by Darquezze** [comment]
Off topic but how's N64 Mode going?

**Comment by ghost** [comment]
It's going good, i'd say. Mario, Peach, and Bowser all got revamps on the discord chat. But yeah, we should talk about that there, not here.

**Comment by chickangamer** [comment]
What's your point

**Comment by JackpotSHUnited** [comment]
@chickangamer 
They said that we draw the line with alt costumes when we don't have the slots. As it turns out, we do have the slots. We have exactly enough slots.

**Comment by bb010g** [comment]
@Rage17 Any idea of when you can PR these?

**Comment by bb010g** [comment]
Aww. I always liked these.

**Comment by ghost** [comment]
I can still get them PRed, I just haven't seen too much desire for them(at least on the Discord).

**Comment by vinegar97** [comment]
most of the initial response was approving of this, the only one i've seen that didn't agree on discord was nanobuds. i'm not saying he doesn't matter, of course, but i think alot of people would like to see this in the build

**Comment by LnktheWolf** [comment]
Most of the people seem to like it, there's pmdt precedent, it looks decent. So I say approved. Though we should consider nano said because of his previous position, though he hasn't liked things that were put in official pm before.

**Comment by DestinyHiro** [comment]
Well I agree to it, it doesn't effect the competitive scene at all either; Also the allowed Pink Gold Peach why can't Sonic and Knux have their Metal forms represented too, since it is only fan service like PGP.

**Comment by bb010g** [comment]
@Rage17 Any updates on this?

**Comment by LinkTahuterasuSpirit** [comment]
maybe all the characters can have a metal texture that represents them in some way, just a suggestion though

**Comment by bb010g** [comment]
We're trying to stick to canon references. Pink Gold Peach fits, as that's in universe, as well as metal versions of some Sonic characters. That's pretty much it.

**Comment by LinkTahuterasuSpirit** [comment]
@bb010g yea i know, it was just a sugestion

**Comment by bb010g** [comment]
@Rage17 Is this tabled for a bit, or is this still in progress? It would be nice to just get these PR'd and out of the way.
