### ISSUE TITLE
Increased Quality Stage Previews

### ISSUE THREAD

**Issue by vdenzen** [TheOriginalSINe/Project-M-CC#216]
With the extra space from the removed stock icons i thought about making the quality of the stage previews better by using HD stage preview images and upscaling the resolution from 175x175 to 200x200.

example: http://imgur.com/LsusbOR , http://imgur.com/AyWZwfU
And the download link: https://www.dropbox.com/s/hihpclw8sffm2b0/sc_selmap.pac?dl=0

As @Azer-X mentioned will this increase the quality of the build but it is also potentially out of scope, so i would like your opinion about this matter.

**Comment by ghost** [comment]
I personally would like to see this included.

**Comment by ghost** [comment]
As I stated before, I may be in support of this. While technically it is out of project scope, this is a non subjective change that can be universally agreed upon that will make the game better. Also it is a relatively small time investment.

Biggest concern is to test it to the 9s and make sure the increase in filesize doesn't cause any lag or freezing etc.

**Comment by AgentBlizz** [comment]
If there are no problems with lag and such then I'd also like to see this included

**Comment by Kippy232** [comment]
I agree with the reasoning that as long as nothing breaks, so to speak, this should be included.

**Comment by bb010g** [comment]
Out of scope.
