### ISSUE TITLE
Pikachu Shiny Intro

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#217]
Currently the graphic only shows for PM's new alternate, even though both that costume and Brawl's red team Pikachu are Shiny Pikachu.

**Comment by vinegar97** [comment]
Shiny graphics are now on both shiny costumes, tested and working: http://www89.zippyshare.com/v/ed1d2dZh/file.html

**Comment by ghost** [comment]
Thanks a bunch, vinegar!

**Comment by vinegar97** [comment]
no problem! , now how would i go about making a pull request ?

**Comment by ghost** [comment]
I'm actually not too knowledgable about that. Chances are that someone on the Discord chat knows, though.

**Comment by vinegar97** [comment]
alright then, to discord!

**Comment by ewmb7701** [comment]
Fixed in #229. Closing.
