### ISSUE TITLE
roy & mewtwo's kirby hats missing metal textures

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#218]
When kirby is copying mewtwo or roy while he's in metal mode, the hats show with their normal textures
as opposed to every other hat where it also has metal.

fix: add metal materials, it's as simple as right-clicking the hat model in brawlbox and choosing "regenerate metal materials".

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11906113/5df08c64-a598-11e5-8a73-d7de829f40bf.png)
![image](https://cloud.githubusercontent.com/assets/16145986/11906117/613f4766-a598-11e5-8979-058e05857cbb.png)

just grabbed the screenshots for those concerned about change documentation.

**Comment by ewmb7701** [comment]
This was fixed in #229. Closing.
