### ISSUE TITLE
Giga Bowser Recolor Texture Updates

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#219]
some of giga bowsers textures for his recolors are poorly made and don't fit the rest of the brawl cast

fix: MagicManNo9 over at smashboards remade the textures to be more fitting and fix them up a little.

here is a comparison image:  http://i.imgur.com/SmmOLE8.jpg

and here is the download link: https://www.dropbox.com/s/6k9yes1qa08cs15/Giga%20Bowser%20Updated%20Textures.rar?dl=0

**Comment by pvrker** [comment]
Someone should ask him if we could use these and if he'd like to help with the project at all. He actually has a lot of really nice fixes such as these:

![image](http://cdn.makeagif.com/media/2-15-2015/IgfJ7N.gif)

![image](https://cloud.githubusercontent.com/assets/16171785/11887556/4c6ddc0c-a503-11e5-9aea-dd8401789f57.png)
![image](https://cloud.githubusercontent.com/assets/16171785/11887560/52a10680-a503-11e5-91cc-68316121ea20.png)
![image](https://cloud.githubusercontent.com/assets/16171785/11887563/58f805a6-a503-11e5-80db-f3ed19b3ae7c.png)

"Shogun Dedede's body texture was half the size than the default making the texture low quality in game. Solution: I updated the texture and restored the original size, cleaning a couple of things as well."
![image](https://cloud.githubusercontent.com/assets/16171785/11887592/967dd87e-a503-11e5-8601-c4f79d715ef9.png)

**Comment by ghost** [comment]
Note that the PMDT saw that thread, and some(but not all) of the fixes are already in our build (carried over from 3.6).

**Comment by vinegar97** [comment]
that's my point, some of these (like shogun dedede texture updates and i remember there being one for DK as well)are still not implemented and have no reason not to be, so if anyone is able to contact him that would be great!

**Comment by pvrker** [comment]
Yeah I figured some had made it in, I picked the ones I wasn't sure made it too the official build.

**Comment by bb010g** [comment]
:+1: The PMDT was already adding those in.

**Comment by ewmb7701** [comment]
This was fixed in #229. Closing this.
