### ISSUE TITLE
Various outset toon link fixes  

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#220]
when outset toon link was first included in PM, he had some vertex issues with holes between the hair and the head, and his feet not being revertexed from his default costumes's boots.

MagicManNo9 made a fix for the boot that was included in 3.5 but the hair issue was still present, and later Aghanim built on that and fixed the hair and proportions, as well as adding 
modeled handcuffs, which should fix all issues mentioned.

link to fix here: http://forums.kc-mm.com/Gallery/BrawlView.php?Number=209089

**Comment by bb010g** [comment]
Could you put this in a PR?

**Comment by vinegar97** [comment]
sure ! as soon as i find out how.

**Comment by vinegar97** [comment]
should i make separate PRs for the rest of the issues or should i put them all together ?

**Comment by fkukuck** [comment]
Separate, and with references what issues they are fixing

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11905722/f2b88872-a595-11e5-825c-0f56c9175e9d.png)
![image](https://cloud.githubusercontent.com/assets/16145986/11905727/f673bfea-a595-11e5-8bb7-df759a1ee2de.png)
![image](https://cloud.githubusercontent.com/assets/16145986/11905732/fd63342a-a595-11e5-8c03-9868fc7fdc4d.png)

Pictures added here for change documentation.

**Comment by vinegar97** [comment]
@clawish it's too late now, sorry.
@Rage17 thanks, you save me some effort

thank you both.

**Comment by ewmb7701** [comment]
This got fixed in pul #229. closing.
