### ISSUE TITLE
Prime Power Suit Samus

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#223]
![image](https://cloud.githubusercontent.com/assets/16145986/11887156/56d7f7c6-a4ff-11e5-9055-0ce43f8a8ce0.png)
I'm not trying to make a full force push for this to be added, but here's some food for thought. Nanobuds made an import of it, and put it up on Brawl Vault along with the Project M suits. A few days later, and the entry has been removed, and there's been no mention of it since. Trying to get a backup of the costume from anyone who has it atm.

**Comment by ghost** [comment]
A link was found, yee. Feel free to share your thoughts on it now that we have a link. https://www.dropbox.com/s/tn6k56ay4vzl2hh/Power%20Suit.rar?dl=0

**Comment by cobalt-blue** [comment]
samus's wardrobe is already pretty extensive

I think we can leave it.

**Comment by AgentBlizz** [comment]
Something tells me that Nanobuds would rather this not make it to the CC build, but if he gives us permission then I'm all for it

**Comment by ewmb7701** [comment]
Samus doesn't have any more slots open for costumes. If she had to get one added, another would have to be removed. As much as I don't like the light suit, I don't think we should replace any PMDT official costumes.

**Comment by ghost** [comment]
Yeah, i'm not down for replacing official costumes. Later on we might tinker with Mewtwo2000's fixed cBliss codes(which add the features from the PM costume engine to it, while keeping cBliss' 14 costumes and such), but until then, no.

**Comment by ewmb7701** [comment]
Correct me if I'm wrong, but doesn't the 14 costumes keep you from using stock icons and battle portraits? I never got them to work properly.

**Comment by ghost** [comment]
I haven't looked into the portraits myself actually, but I feel like the people who were trying to get BrawlEx to work with PM might be able to fix it, as they had to deal with some form of it apparently(in regards to clones' icons and such).

**Comment by ewmb7701** [comment]
I thought about this, and it is technically possible. As I'm sure you know, each character has a cosmetic slot assigned to them. for example, Character A has 150-159, and character B has 160-169. Normally, going above 10 would have the 11th costume be on the next character's slot.  However, some characters with no characters in the cosmetic slot in front of them (like Ganondorf) can have more than 10 costumes with cBliss while keeping cosmetics. Ganondorf occupies cosmetic slot 19, and Meta Knight occupies 21. There is no character in slot 20, so there's no danger in using the cosmetics for that slot. If we wanted to give everyone 14 costumes, we'd have to remap everyone's cosmetic slots to create buffer slots for those that need it.. While this is easily done in BrawlEx, I'm not sure if PM's clone engine has that functionality.

**Comment by jgd124** [comment]
I'd rather this didn't get in. There are already two (three if the PED suit is \* really \* getting in) other suits with remarkably similar design cues.

This is another proposal that I think steps too far out of line with what the PMDT would do.

**Comment by DarkLink1996** [comment]
I'd say put it in the git as an alternate Retro Samus. Even if you guys do get CBliss working there's plenty of possible suits to add.

**Comment by Kippy232** [comment]
While I agree with tinkering with the idea of adding more costumes for each fighter further down the line, I feel like this suit is too similar to the Varia Suit, PED Suit (though currently unimplemented), and Retro Power Suit. Like @DarkLink1996 said, maybe add it as an alternate Retro?

**Comment by bb010g** [comment]
If we are to use this, we need to get Nanobuds' blessing.
