### ISSUE TITLE
Ganon sheath

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#225]
![image](https://cloud.githubusercontent.com/assets/16145986/11888156/b4f87a34-a508-11e5-9de5-f57e89683008.png)

![image](https://cloud.githubusercontent.com/assets/16145986/11888173/e2f1ed8a-a508-11e5-8ec2-89003f4bd87b.png)

Added a sheath to both Ganon models, so their swords don't come out of nowhere when drawn. Textures are OOT Ganon are modified in the screenshots, but will not be modified in files for the main build.

**Comment by Kippy232** [comment]
I've wanted someone to do this for so long, but unfortunately I have no skill in Brawl modding. +1

**Comment by ghost** [comment]
Personal stylistic change not in project scope. Closing.

**Comment by ghost** [comment]
Atm, there is no indication of how Ganon's swords appear(they have no graphic when they come out unless the attack is done), so they simply appear out of nowhere.

**Comment by ghost** [comment]
Much like how King DDD's side B's come out of no where, Kirby's Hammer, Peache's F-Smashes and Parasol, Rob's Gyro, etc etc. If PMDT wanted Ganon to have a sheath, they had 6 years to give him one.

**Comment by Grangach** [comment]
I think it hurts the readability of the model but I would need to see it in motion.

**Comment by AgentBlizz** [comment]
I don't really like the sheath. It's really bulky and I'm already used to Ganon moving freely like Falcon. A huge appendage like that would be something i'd be constantly aware of.

**Comment by bb010g** [comment]
:+1: for what @Azer-X said.
