### ISSUE TITLE
Kunckles' F-smash face animation 

### ISSUE THREAD

**Issue by UNOwen3** [TheOriginalSINe/Project-M-CC#228]
I don't know whether this was intentional or just lazy animating, but only the right side of Knuckles' face is animated during his F-smash and his throws:

![00000000-1](https://cloud.githubusercontent.com/assets/16328148/11895991/245490d2-a583-11e5-897c-e0d6b1cf871b.png)
![00000000-3](https://cloud.githubusercontent.com/assets/16328148/11895992/245b6452-a583-11e5-9180-ad188ff7871e.png)
![00000000-7](https://cloud.githubusercontent.com/assets/16328148/11895993/2460df4a-a583-11e5-9049-d8bd5a2145ed.png)

It doesn't even get mirrored if he's looking left.

**Comment by Kippy232** [comment]
I'm certain it was an intentional, if somewhat odd, stylistic choice. 

Edit: Now that you mention it, the more I see this, the stranger it becomes. Maybe on the left side of his face, his eye should match the right; or vice versa.

**Comment by UNOwen3** [comment]
Yeah, I kinda understand what they were going for, but they did it rather oddly. A slight correction to the left eye could make it better. Just tried fixing it a bit with editing, seems like it improves:
![knuckles mejorado](https://cloud.githubusercontent.com/assets/16328148/11897769/c385379c-a592-11e5-9eae-3f5ebee641ef.png)

**Comment by Tottle** [comment]
The side mouth for Sonic characters is fine, but if your going to do that it needs to only be on that side of the face and not so wide.

**Comment by Kippy232** [comment]
I agree with this change. Could you do this for each of the appropriate animations and push it?

**Comment by Karrotkonvoy** [comment]
Honestly, I like the asymmetrical eyes. Looks like he's feral and going insane. I also feel like symmetrical eyes with an asymmetrical mouth kinda looks off.

**Comment by Grangach** [comment]
Most of these images are from straight on but what matters is if they look good during gameplay.

**Comment by ewmb7701** [comment]
As @Grangach said, you really won't be seeing these from straight on. And as @Tottle pointed out, the side mouths on Sonic characters is fine. Every Sonic character does that stupid side mouth thing; it's part of their style. To me, fixing this would be like making Mario's mustache a realistic size. (However it does look a tad ridiculous).

**Comment by UltraSyko** [comment]
Ya know the whole side mouth thing has been a problem in actual Sonic games, right? Sonic has 2 mouths in Generations

**Comment by Grangach** [comment]
maybe he should have 2 mouths in this so it doesn't matter which side he's facing? I can't check to see how it looks in motion right now.

**Comment by UNOwen3** [comment]
![00000000-17](https://cloud.githubusercontent.com/assets/16328148/11912842/21876668-a650-11e5-9c4d-c3f8f265c351.png)
![00000000-19](https://cloud.githubusercontent.com/assets/16328148/11912841/2184aebe-a650-11e5-80a0-64a37a834205.png)
![00000000-21](https://cloud.githubusercontent.com/assets/16328148/11912843/219dd092-a650-11e5-8107-e4fe58a4c602.png)

I only corrected the eye while keeping the mouth intact. Seems like it looks better than before, at least to me.

**Comment by Kippy232** [comment]
An improvement in my opinion, however, it may look odd from the other side as seen in your last pic. I like it, but beauty lies in the eye of the beholder.

**Comment by LinkTahuterasuSpirit** [comment]
here's what i don't get, why does Knuckles have jagged/sharp teeth?

**Comment by toonjoey** [comment]
Well, I think the whole "Mouth side isn't animated" thing is from Sonic X. I've seen some of the shows old intro, it had a similar face for Knuckles.
