### ISSUE TITLE
Shogun DDD texture resolution

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#231]
vinegar97 made a pull request that fixes this, with a fix from this thread: http://smashboards.com/threads/project-m-visual-fixing-updating-thread-lastest-update-10-03-15.384954/

Made an issue entry for proper documentation of changes. 
![image](https://cloud.githubusercontent.com/assets/16145986/11906049/e6e15220-a597-11e5-98ba-270a1a1c7d50.png)

**Comment by ewmb7701** [comment]
I believe pull request #229 fixed this. Closing.
