### ISSUE TITLE
Project M on Dolphin Crashing Since Latest Update

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#232]
Edit: Never mind. I was able to fix the issue.

I have been getting this error when I try to start up Project M since the new update. Here's the image of the issue happening below.
![untitled](https://cloud.githubusercontent.com/assets/16161703/11907405/30797ae2-a599-11e5-9811-f19a68a8391f.png)
The main source is the Kirby Roy and Mewtwo metal texture changes. I am very sure of this because I have attempted to add metal textures to the Roy and Mewtwo hats via brawlbox a couple days ago and experienced the same issue. Please revert the Kirby changes until the metal textures can be added properly (as in without having the same issues).

**Comment by Kippy232** [comment]
For future reference, how were you able to fix this issue? Was it an issue with your setup, with Dolphin, or with the latest build?

**Comment by bb010g** [comment]
...you should just be able to close the issue yourself, as creator. (His fix is [here](https://github.com/TheOriginalSINe/Project-M-CC/commit/2de619bdff909cdb411cd84bebae6d040bc3a3b3#commitcomment-15079111).)
