### ISSUE TITLE
Lyn Down-B

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#234]
During her down-b, her eyes close and become swollen.

**Comment by ghost** [comment]
@meta-neo-omega-ridley It seems that the real issue there is that Lyn shows all of her expressions at once, causing a weird look.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11909236/d857f5dc-a5b1-11e5-832f-33b35fc5ba9c.png)

Here's a picture of the issue, for the sake of documentation.

**Comment by meta-neo-omega-ridley** [comment]
What other expressions does she have? All I ever see is that expression-less, psycho-path look when she gets hurt (its only psychopathic when she's being damaged. otherwise, its fine)

**Comment by ghost** [comment]
@meta-neo-omega-ridley blink, half blink, damage, and default are the expressions IIRC. judging from your message, I guess that the all faces showing up thing happens when she gets damaged as well.

**Comment by ewmb7701** [comment]
This is covered by #54. Closing.
