### ISSUE TITLE
Knuckles battle entry

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#235]
Knuckles kind of just floats out of the ground. I had thought he had something similar to Sonic's, but maybe that was before. Maybe his entry could be similar to his neutral-B (the second-half, where he punches the ground)

**Comment by ghost** [comment]
This is already covered in a previous issue thread, if not more. this should get closed.

**Comment by ewmb7701** [comment]
This is already covered by #12. Closing.
