### ISSUE TITLE
Knuckles has Sonic's mouth

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#236]
When Knuckles is doing a certain attack, he has sharp teeth while in some moments (getting hit, near the ledge) He has the mouth of Sonic

**Comment by bb010g** [comment]
What's the issue here? (Feeling like a duplicate of #228.)

**Comment by Darquezze** [comment]
@bb010g kinda similar, Knuckles has different mouths in different moments 
1st  is like #228 with Knuckles sharp teeth
The 2nd is like Sonic teeth, not sharp

**Comment by bb010g** [comment]
Could you give examples of the second?

**Comment by Darquezze** [comment]
Me being dumb, I don't know how to post pictures on here (I'm using Mobile version)

**Comment by Darquezze** [comment]
@bb010g here u go https://plus.google.com/115474315144239483658/posts/VH56TQ1Yvng

**Comment by jgd124** [comment]
I mean... Looking at it, it seems pretty intentional. 

Knuckles would look extremely stupid if he had those big, sharp teeth showing in every animation. 

Personally, I think it looks stupid on his side smash, but that's just me.

**Comment by UNOwen3** [comment]
Knuckles has 7 different mouths used in different animations. The sharp teeth only appear in the Angry_Mouth one.

Him having no teeth on his surprised face is completely intentional.

**Comment by bb010g** [comment]
Toothless mouth is intentional.
