### ISSUE TITLE
PED Suit Samus morphball size issue

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#238]
PED Suit Samus' morphball is too big compared to the other costumes' ones. As Nano made the original import before PM 3.0, he didn't check the size. As the leaked model only has material updates, the issue is still there.

**Comment by vinegar97** [comment]
In addition to not being the proper size, the morph ball is also not centred properly, making samus go inside the floor a little and hover over the floor when in ball form

**Comment by ghost** [comment]
https://www.cubbyusercontent.com/pli/pedballfix.rar/_ea7bbc23792c4f8c932d9d310b13772c

This should fix it. Based size and placement off of Dark Suit Samus.

**Comment by vinegar97** [comment]
if brawlbox is anything to go by, i'd say this is working properly :shipit:

**Comment by medaman3** [comment]
If this question already has an answer, forgive me, but I noticed that Samus has 10 costumes while ZSS has 9?

**Comment by vinegar97** [comment]
@medaman3 this was discussed in #209

**Comment by medaman3** [comment]
Thanks and sorry

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/16145986/11921377/febb1920-a755-11e5-848b-a485dfb49076.png)

A picture for showing that the PED Suit Morphball was fixed.

**Comment by ghost** [comment]
Closed, since the PED Suit isn't being included here anymore(at Nanobud's request).
