### ISSUE TITLE
Lyn: taunt effects and directional differences

### ISSUE THREAD

**Issue by bungholemaster** [TheOriginalSINe/Project-M-CC#24]
The green effect/outline on lyn's sword during her taunts extends past the hilt a significant amount.

Also when she's facing left her side taunt does her down taunt and when she's facing right it does her up taunt.

**Comment by ghost** [comment]
If we're talking about aesthetics, her arrow streak has an odd shape, where it's pointed on one side instead of being pointed at the tip of the arrow

**Comment by thesmashking25** [comment]
thedudemonn on youtube has a finished lyn psa

**Comment by bungholemaster** [comment]
That PSA was already added to this build. In the video where he shows it off though it looks like this bug isn't there, but I'm not sure.

**Comment by ghost** [comment]
IIRC this was fixed in one of our recent Lyn builds.

**Comment by somealternateaccount** [comment]
Can anybody confirm if this was indeed fixed? We should find the exact commit where it happened, if possible.

**Comment by bb010g** [comment]
Subsumed by #305
