### ISSUE TITLE
Victory Animations

### ISSUE THREAD

**Issue by meta-neo-omega-ridley** [TheOriginalSINe/Project-M-CC#240]
Lyn has Pit's victory animation, and Knuckles has Sonic's victory animation.

**Comment by ghost** [comment]
@meta-neo-omega-ridley Dunno how far back you are on the main build, but Knuckles has his own victory animations atm. Lyn's issue still has to be dealt with though. This is covered in previous issue entries, so this should get closed.

**Comment by Kippy232** [comment]
I'm maybe one or two commits behind in the main build, but Knuckles' Victory Animations are odd. Most notably where he jumps into the air, then slowly falls with little to no animation as dust stirs below him.

**Comment by meta-neo-omega-ridley** [comment]
I had thought that, and the one where he gives thumbs up were Sonic's victory animations.

**Comment by ewmb7701** [comment]
These are covered in other issues. Please check the issues before making new ones. #22 #246 

Closing.
