### ISSUE TITLE
(NOT A BUG) ThedudemonnsIssac

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#241]
Thedudemonns has made a fix for Isaac, check his channel

**Comment by ghost** [comment]
@Darquezze Thanks a bunch for pointing this out. I'll look into it.

**Comment by UltraSyko** [comment]
Yo, I'm watching his video! The sfx are so fitting

**Comment by bb010g** [comment]
Video link for the lazy?

**Comment by UltraSyko** [comment]
https://www.youtube.com/watch?v=QpaEoKbn_Sc

**Comment by Darquezze** [comment]
@bb010g https://m.youtube.com/watch?v=QpaEoKbn_Sc

**Comment by UNOwen3** [comment]
Has he said anything about fixing Isaac's U-smash, U-special and D-special?

**Comment by ewmb7701** [comment]
I'll ask him if we can include the SFX files and the other fixes he's made.

**Comment by Darquezze** [comment]
So, since thedudemonn added a fix for Issac around this hour again, this time he has a up smash

**Comment by UNOwen3** [comment]
I don't really like how he did it. Isaac and Felix were the only characters unable to use the Plasma series. Can't help to think that Gaia would be a better fit as his Up-smash. Any thoughts?

**Comment by IngaRasen** [comment]
While I think that Gaia is much more fitting as an Up Smash as well, I don't hate the idea that Kitsu has in place for his. While you're correct that Isaac can't learn Plasma, if I'm not mistaken, he _can_ learn the Bolt series of attacks. (I'm thinking that particular one is based on Flash Bolt.) Besides that, there's kinda precedence for it with the Mother characters learning attacks that they couldn't in their source material... although I would really prefer it if Isaac stayed with the moves that he has in his game, of which he has plenty.

If you could create a rocking version of Gaia for your PSA, then I'm pretty sure that I'd be sold on it.

(On a slightly tangential note, I think that Bolt could be fitting for an Up Tilt. It would give him more variety for his Psynergy attacks seeing as he already has two Growth moves. However, It would be understandable if no changes were made to it, as it works perfectly fine as is, and Isaac is pretty low priority right now.)

Edit: According to his notes in the upload, it's meant to be Thunderbolt. Whatever; that works just as well.

**Comment by UNOwen3** [comment]
Huh, didn't think about the Bolt series, you're completely right. I just saw the color of the flashes and got reminded of Plasma, but it may very well be a Bolt. 

I can try creating a gaia move by using the rock from his Up-B and resizing it to pebble level, but no promises.

Edit: WPI version. I have to add a hitbox to the pebbles, some GFX (dust, explosion, beam of light), and copypaste it a few times in different locations, but you get a general idea:

![output_rijbg0](https://cloud.githubusercontent.com/assets/16328148/11919262/ec2220b8-a74d-11e5-8e22-a29836c9070c.gif)

Should I go for it? Or does the Lightning look better? I'm all up for suggestions.

Edit 2: Went for it anyway:
![output_bwuqbk](https://cloud.githubusercontent.com/assets/16328148/11919614/661e773c-a757-11e5-9e3f-c1ffce8c2944.gif)

For now it's all graphic effects, gonna build the hitboxes now

**Comment by bb010g** [comment]
My only complaint is that it's too fancy. Imagine those going off in doubles. General design wise, it looks awesome.

**Comment by UNOwen3** [comment]
You actually bring up a good point. Right now I don't have my Wii, so I can't do a performance test, but at least on Dolphin it won't slow down as long as there are no more than 2 Isaacs spamming it non-stop. With all 4 it dropped to 55 FPS.
I'm all up for economizing in GFXs, if anyone knows a less fancy effect that fits the bill, I can change them in a second.

**Comment by bb010g** [comment]
I'm not worried about performance; I'm worried about visual noise. It's a very busy effect, and that could be detrimental in an active doubles match when you're trying to watch where the other opponent is.

**Comment by UNOwen3** [comment]
I resized the light and the explosion, since they were the main source of flashiness. Here's the result:

![output_5eudj3](https://cloud.githubusercontent.com/assets/16328148/11928201/f5936e48-a7d1-11e5-9ad1-a03e4d9ba006.gif)

And as a bonus, the Bolt uptilt:
![output_zf5vde](https://cloud.githubusercontent.com/assets/16328148/11928532/90c465be-a7d4-11e5-98cc-8536ae42be06.gif)

**Comment by Darquezze** [comment]
Does anyone know how to give Isaac a voice since Thedudemonn gave him one but I'm having trouble putting it in. If anyone has a file that will help alot. (It replaces a sound of Rayquaza) and j dont have a computer so can't edit any PM files but instead could only replace them

**Comment by chickangamer** [comment]
You guys know that this can just be a place holder till we get our own
issac done

**Comment by PowerpointSmasher** [comment]
@Darquezze 

https://drive.google.com/file/d/0B-xJC1KEuTpMczNUTW9TTndNUUk/view?usp=sharing

**Comment by ghost** [comment]
@bb010g This is oddly still open. Please close.

**Comment by Darquezze** [comment]
Did it @Rage17
