### ISSUE TITLE
Issac Down Special

### ISSUE THREAD

**Issue by UNOwen3** [TheOriginalSINe/Project-M-CC#242]
Right now, Isaac's down special is just Toon Link's with the animation for some psynergy (I would say the Quake series, since the Up-smash is a better fit for Gaia).

Suggestion: Change down-special's effect to something that would resemble the Quake Psynergy.

I've been tinkering with PSA a bit and already have the attack itself. What's left are the properties. It could mirror DK's down-b, it could have a high slip chance, or bury the target into the ground. 

What properties would be more fit for it?

**Comment by ewmb7701** [comment]
I have not played Golden Sun, but I think a slow, high risk high reward AOE burying attack would work nicely

**Comment by cobalt-blue** [comment]
as someone who has played golden sun, if the down B is suggesting the quake psynergy, then it'd make more sense to be made as a copy of donkey kong's down B.

**Comment by UNOwen3** [comment]
My idea was a single hit move, with a launching effect (just like quake launched enemies upwards)

Right now it looks like this:
![00000000-25](https://cloud.githubusercontent.com/assets/16328148/11917238/24ecca46-a6ff-11e5-97e9-8a7ed10905f7.png)

It launches enemies directly upwards. Since it can't be cancelled, and it can't hit airborne opponents, I decided to make it bigger than a shine. But since it's faster than DK's Down-B, i made it smaller than it.
As a comparison, DK's looks like this:
![00000000-29](https://cloud.githubusercontent.com/assets/16328148/11917257/00287e0c-a700-11e5-92fd-842af9cc2bb7.png)
And Falco's shine:
![00000000-31](https://cloud.githubusercontent.com/assets/16328148/11917261/5d7f2420-a700-11e5-8fab-0cc07b2e8771.png)

 Thoughts on it?

**Comment by Grangach** [comment]
We really need to decide on what isaacs archetype is, I assumed he was a zoner and I don't know if this reflects that. I think having cohesion not just aesthetically but also from a gameplay perspective is very important.

**Comment by UNOwen3** [comment]
Thanks, that's the kind of suggestions I was looking for.

I had no real idea about what kind of move I should give him, so it has two hitboxes as placeholders, and the effects aren't decided yet. Still, from the looks of the animation (since we are gonna finish what the PM team already did, not modify it), it's an attack that has something to do with the ground. So the easy answers are Gaia and Quake. And as a personal opinion, I think Gaia is better fitted to be his Up-smash.

What kind of ground-like attack would be a nice tool for a zoner? 
We could have a ground only attack, with great reach but poor power, that works as a disturb on dashing opponents. The slip or down properties would work great with that.

I only need to know what kind of attack you guys think would fit the best, and I'll try to deliver.

Edit: Also, since his grab is long-range only, an attack that puts enemies right on his grab range would also work great. So the effect could be some set knockback to easy his grab game. Although I think his grab is meant to do that.

**Comment by chickangamer** [comment]
Do you have a demo of your psa

**Comment by KymaeraK1ng** [comment]
Is there a download link? Also, MAKE SURE HE HAS ONE MID-AIR!

**Comment by LinkTahuterasuSpirit** [comment]
i've seen a fix for issac, whale i like most of the changes he did, i don't like the side-smash he gave him

**Comment by bb010g** [comment]
Still needs to be taken care of, but will be re-opened on the dedicated repo when that gets rolling ([Project-M-CC/isaac](https://github.com/Project-M-CC/isaac)).

**Comment by TheSmashBoy** [comment]
@UNOwen3 Hey dude. I made a pull request with your Isaac PSA (pressuming you are the same Owen that made the Isaac PSA from your YouTube account). It was currently reverted by bb010g. I was wondering if you approve of your PSA of Isaac being in PMCC.
