### ISSUE TITLE
Knuckles crouch doesnt cause him to duck

### ISSUE THREAD

**Issue by darkralts** [TheOriginalSINe/Project-M-CC#243]
When knuckles crouches he doesnt duck, instead he just moves both his fists to the right.

**Comment by ghost** [comment]
@darkralts it's intentional for Knuckles to just position himself lower and make a battle stance. Not all characters duck. For example, Ganon merely goes down on one knee. This should get closed.

**Comment by darkralts** [comment]
Ok i diddnt know. Does an admin have to close it or do i?
