### ISSUE TITLE
[RFC] Stages (again)

### ISSUE THREAD

**Issue by Yohan1044** [TheOriginalSINe/Project-M-CC#245]
I don't know what medium to use to propose changes to the GitHub administrators, or how to open a vote to the CC-community, so I'm opening a new issue. I understand that the scope of the project is to finish up incomplete work of the Dev leak and not to add custom content. I do, never-the-less, propose adding/rearranging the stages, in line with how PM might have continued their work. I'm not posting this to get stages I love into CC, (I already have a custom build of CC with ~30 added stages), I'm posting this because I feel it's the direction CC should head in. Ultimately, I'd like this to be considered and voted upon.

Attached are two stage slot plans. The first plan is what I'd do for CC if I were supreme dictator. The second plan is more likely to be accepted by all. Both are flexible.

Plan 2 adds in MarioCircuit and GreenGreens from Brawl, by moving Kongo'64 to JungleJapes as an alt.

Plan 1 continues, merging BigBlue with Porttown and SaffronCity with SpearPillar to make room for new fighter home stages. It also adds in Retro version of Battlefeild and FinalDestination, and gives us back the OnlineTrainingRoom.

[Proposed_PM-CC_stageList_Yohan1044_v1.pdf](https://github.com/TheOriginalSINe/Project-M-CC/files/67671/Proposed_PM-CC_stageList_Yohan1044_v1.pdf)
[Proposed_PM-CC_stageList_Yohan1044_v2.pdf](https://github.com/TheOriginalSINe/Project-M-CC/files/67673/Proposed_PM-CC_stageList_Yohan1044_v2.pdf)

Green = new
Yellow = moved
Blue = Non-hidden retro (forgive the color scheme)

Things to note:
A lot of people on Discord today wanted these changes. I heard no rebuttals
PMDev added homestages for their fighters... giving Bowser his own and restoring Distant Planet for Olimar
The plans remove nothing already in the build (except the SFX of BigBlue in v1, a constant engine noise)
The plans only add stages already in SSB/PM games (except homestages in v1)

.

**Comment by ghost** [comment]
Noting that Big Blue's engine noise is drowned out by it's own music, and it has no stage GFX IIRC.

**Comment by jgd124** [comment]
Alrighty. Here's my rebuttal. Project M CC "is also not a new custom content mod. The goal is to stay as true to PMDT's design as possible."

Like it or not, several of the changes you are suggesting, such as Venus Lighthouse, a change to the Online Training Room, adding 64 Battlefield, creating a new home stage for Sami, adding Big Battlefield, or even simply moving stages around have no actual president to point to.

I can understand how the spirit of completion would apply to the stagelist itself, but if the design goal of " staying as true to PMDT's design as possible," then this change is needless should be relegated to a personal custom build.

If we really want things like this to go through, then we should collectively change the design goals of this project.

**Comment by Yohan1044** [comment]
Did you see V2? All it does is add GreenGreens and MarioCircuit by moving Kongo'64.
And the "BigRooms" refer to the PM3.6 training rooms.

**Comment by ewmb7701** [comment]
This is out of the scope of the project. 

Clearly there is a bit of disconnect between what the users of Discord are saying and the established goals of the project.

**Comment by Yohan1044** [comment]
Just to clarify, Are you against V2?
It adds no custom content. It only returns two stages removed from Brawl in earlier PM builds before the Alt stage loader.

I'd also like to add that the "BigRooms" refer to the TrainingRooms of PM3.6

**Comment by jgd124** [comment]
Whoops, you're right. I misread v1. I'm pretty much wholly against v1.

And yes, I saw V2. I'd be "least against it" I guess.

That said, I see the changes of v2 as kind of... needless? 

I'm sorry. In any other context I would let this slide, as I'm doing something incredibly similar in my own build. And it's a great idea.

But the only stage that I can truly see making the case for coming back would be Peach's Castle Melee, as that was the only one I can recall making a return in the leaked Dev Build.

**Comment by Yohan1044** [comment]
Peach's Castle Melee and Dracula's castle are already in CC. They are just in hidden slots right now. See issue 57

**Comment by jgd124** [comment]
Awesome. 

Well, anyway, I could see this working really well in a later build, the one that @Rage17 seems to be working towards on discord what with adding characters, extra skins, custom stages, and metal sonic skins and such. But whatever that vision is, it's not this build. 

I was under the impression that 3 CC existed to fix/complete characters and crush bugs, with anything beyond that as beyond the scope of the project.

Am I wrong @TheOriginalSINe?

**Comment by ewmb7701** [comment]
@jgd124 You are completely correct. I have been working on a document which should define what exactly the scope of the project is. I'm okay with the metal skins because it's a nice easter egg and Pink Gold Peach is similar to this, but new skins, stages, and characters were never a part of this build's goals.

**Comment by ArtfulHobbes** [comment]
You are correct. Keep all the custom stuff to personal builds guys, the main goal of this build is very specific.

**Comment by ghost** [comment]
hm? @jgd124 i'm not adding extra custom stuff in my build atm.

**Comment by jgd124** [comment]
@Rage17 I just meant the general "what should we do with the final two character slots" and "we should eventually fill up the costume slots of each character" type stuff. I assumed that you were eventually going to do it at some point.

**Comment by Darquezze** [comment]
All are Brawl stages coming back? I'll love to see that

**Comment by Yohan1044** [comment]
...sigh.
There is no custom stuff in V2. Only brawl stages, which used to be part of PM way back when.
So, we're against adding GreenGreens into the middle of Dreamland...
But we're for adding HD stage previews and Knuckle's easter eggs. Oh well.

![0picture3](https://cloud.githubusercontent.com/assets/16171767/11916432/899a02b6-a6a4-11e5-8c23-1fab80699f84.png)
-stage preview by RadiantThunder4

Is there a way to open this to vote?
@Darquezze I've added all Brawl Stages to my custom CC build, but when bouncing ideas off the Discord chat, people didn't seem to like the sacrifices involved in adding 75m, MarioPast, and MarioBros. Adding more stage slots degrades image quality, and I'm against that for CC

**Comment by ewmb7701** [comment]
@Yohan1044 It's not that I'm against the stages themselves, I'm just afraid this will lead to a slippery slope type issue. No stages should be added to the build. That being said, seeing as the Pokemon Stadium 2 Brawl stage was added in the Dev Build, and there are unbalanced hidden Brawl and Melee stages as alternates, I don't think this is entirely too much of a stretch to have them as alts. 

I'm very hesitant to allow this, but I think that you have a fair argument for including them, so I think this should get a pass. But I think that the only stages that should get added as alternates are ones that:
1) Aren't horribly janky
2) Don't replace anything
3) Are an appropriate alt

**Comment by jgd124** [comment]
Look, I'm personally against HD stage previews (less room for custom music) and the Metal Sonic change (it looks super sweet, but it's the one exception to the rule).

If there was a vote, I would still vote no to both versions (although I'm going to do something similar with my build) because this is suddenly a matter of preference. What about the people that want Kongo Jungle as its own slot for its own music? What about the people that think that Mario Kart was a bad stage?

What happens when they make their own issue?

The PMDT made their stage choices out of preference. What you are suggesting is a competing preference.

I'm not sure I'm about that.

That said, if there are people on dischord that want to back this idea up, I'm all ears.

**Comment by LoanSPW** [comment]
I'm totally up for v2! It looks great and only adds stages that were in Brawl or Past PM versions!

In fact, a PM developper leaked just a few hours ago stuff that was considered / scrapped to be in PM V4.0. The topic seems to have been removed as other persons of the dev team were unhappy about it...
I'll do an issue about this soon, asking if the stuff is going to be included or not.

**Comment by vdenzen** [comment]
I am with @jgd124 on this one and also said to you in de discord chat that adding stages was out of scope for this project so it is not true that you said that everyone in the discord chat agreed with this.

**Comment by ghost** [comment]
@LoanSPW do you have a link to that leak?

**Comment by LoanSPW** [comment]
Unfortunately, no, everything seems to have been removed... However, I've kept some of the images! I'll open the issue in some hours!

**Comment by ghost** [comment]
@LoanSPW thank you. This should be useful.

**Comment by bb010g** [comment]
Closing and tabling until February at least.

**Comment by JackpotSHUnited** [comment]
https://gist.github.com/JackpotSHUnited/c6e01dfe06a6ac45ff5d

Here is my proposal. A bit much, but not everything here would need to be included.

**Comment by bb010g** [comment]
...#57?
