### ISSUE TITLE
Knuckles victory animation.

### ISSUE THREAD

**Issue by darkralts** [TheOriginalSINe/Project-M-CC#246]
His hand is glitched and the victory animations are somewhat incomplete. But this is pretty minor and shouldnt really matter until some major bugs are worked out.

**Comment by jgd124** [comment]
Could you give a specific example or a picture of how the animations are incomplete/glitched?

**Comment by darkralts** [comment]
Sure! Dont have a capture card so camera was all i got.
Video in the zip file

[20151219_224717.zip](https://github.com/TheOriginalSINe/Project-M-CC/files/67684/20151219_224717.zip)

**Comment by jgd124** [comment]
Yeesh. That thumb thing _is_ pretty weird.

**Comment by darkralts** [comment]
The other victory screens arent as bad but they still have problems. At
least its not isaac, that thing is a mess.

**Comment by ghost** [comment]
Closing this, as a generic issue entry(albeit one made after this) covers both Knuckles' win and taunt animations.
