### ISSUE TITLE
Issac's Up-special

### ISSUE THREAD

**Issue by UNOwen3** [TheOriginalSINe/Project-M-CC#250]
Right now, Isaac's Up-B doesn't use the graphical effect the PM team designed.

I've been tinkering with PSA, and managed to fix his Up-B to acceptable results:

![output_jlmvnk](https://cloud.githubusercontent.com/assets/16328148/11918100/a3b77b2c-a723-11e5-92ff-d6f505c33095.gif)

As you can see I've added a (temporarily misplaced) hitbox to the rock. I also intended to give it a meteoric hitbox just at the bottom. Thoughts on this? 

Slightly related: Anyone knows if it's possible to use negative offsets on hitboxes on PSA? I fixed the height, but I can't get the hitbox near the rock, I can only move it away.

**Comment by vinegar97** [comment]
That up B suddenly make so much sense, looks great BTW.

about your hitbox problem, have you tried brawlbox ?, i know one of the older version (v0.63b i believe ? ) had a hitbox editor that might help.

**Comment by UNOwen3** [comment]
I use Brawlbox for checking the animations, bones and stuff like that, but not for editing. When I checked the net yesterday for ways to create new moves, Project Smash Attacks popped up and I've been having a great time using it. It's pretty intuitive and easy to pick up.

**Comment by vinegar97** [comment]
glad you could find a solution, really hope this works out !

...actually you should find some way to contact thedudemonn/kitsu since he's working on issac as well.

**Comment by IngaRasen** [comment]
I think that the PMDT may have meant for his Up B to be Retreat, but never got around to completing it. (I could be wrong, though; I'm not huge into Golden Sun.) Regardless of what they intended for it, though, I'm loving the hell out of this, and I wouldn't mind seeing it in a future build.

**Comment by UNOwen3** [comment]
Update: Isaac's aerial Up-B is more or less finished.
Here you can see it in action:
https://youtu.be/zuvfu4KxnRY
As you can see, the bottom of the rock has a small meteor hitbox, while the rest is a regular one launching at 50 degrees.

EDIT: I know they intended to give him retreat as his grounded up-b. But they wanted to do exactly this as his aerial Up-B. They have different animations and all in the files. I'll try to fix the grounded Up-B too, but that will take me a bit of time since I don't really understand how it works (I'm guessing I'll do something similar to mewtwo).

**Comment by IngaRasen** [comment]
Well then, I didn't realize that. Thanks for informing me on the matter, and again, great job on the aerial Down B. It looks fantastic, and has a pretty neat application to boot.

**Comment by SuperSandbag** [comment]
For the sake of aesthetics, is there a way to give the rock a shattering visual effect after Isaac jumps off of it? Perhaps similar to Charizard's old Rock Smash attack from vBrawl, but maybe without necessarily having actual random hitboxes and all that? That seems like something that would help the look of the attack greatly.

**Comment by UNOwen3** [comment]
Yeah, you're exactly right. I'm currently checking if I can import charizard's rock smash animation and apply it to this one, since it's actually the same model.

Edit: Sadly, I can't seem to find the animation for the rock breaking anywhere on the files I currently have. For now I used the GFX number 51, since it was a fire-less explosion, and seemed fitting. If anyone finds the animation of the rock being smashed, I'll be happy to try and implement it.

**Comment by UNOwen3** [comment]
Update: I managed to fix the grounded Up-B, or at least give it a function. 
https://youtu.be/82CJidFV1JM
Mi idea was to use Mewtwo's teleport as a basis, but I'm having problems implementing the directional inputs. For now it only teleports a fixed distance horizontally.

**Comment by theroy734** [comment]
The whole rock thing may have been a previous idea, but as you can see in this newer build https://youtu.be/HvSxLZKvtnU?t=3m34s the teleport is the aerial up-b as well.

**Comment by UNOwen3** [comment]
Huh, I didn't see that. I just downloaded the files, watched the animations, and worked from there. 
I personally think that having more variety in moves makes it more interesting, and there was an animation(SpecialAirHi, the one used for this) and a model(the rock itself) meant specifically for this, it would be a shame to not use them.

Although, if the team decides to scrap this and use the teleport for both, I'l l change it.

**Comment by bb010g** [comment]
I think the teleport was a temporary animation while they were still figuring out how they wanted uspecial to function. Same thing with the grab magic effect instead of the floating hand.

**Comment by theroy734** [comment]
But why would they revert back to a placeholder when they already had a functional version in a previous build to test around? I still think the leaked build was leaked in the process of the rock up-B being scrapped and changed into the teleport up-B. While having two different up-Bs could be interesting, I think in this case consistency is more important. There are very few cases where a B move's grounded and aerial variation are completely different concepts (ROB side B, arguably ganon neutral B), and those have at least some sense design wise, where in this does not.

**Comment by zombiejerky** [comment]
I love the weird psychics for Issac on that move actually its cool to have plus its something unique

**Comment by zombiejerky** [comment]
I think its the coolest move in the game to be honest. It a weird gravity boulder jump. I like it a lot

**Comment by cobalt-blue** [comment]
can I be the first to also just point out that an asset as large as the boulder just popping in out of nowhere looks really dopey and jank?

if i were being perfectly frank, I'd also just point out as someone who has palyed golden sun, I'm having trouble understanding where half of his attacks are coming from... or why he's so tall.

**Comment by UNOwen3** [comment]
Most of his sword attacks are cloned from other characters, and the psynergy attacks are all based on some Psynergy he can use in Golden Sun.

The up-tilt and d-smash are the Thorn series, F-smash is Blast, Up-smash wasn't complete, B is Ragnarok, Side-B is Move, Up-B is Teleport/Escape on ground and a somewhat liberal conception of Rockfall. Down-B wasn't complete either.

After I added some new models and animations, now Up-tilt is Bolt, Up-smash is Gaia, Down-B is Quake, aerial down-b is Helmsplitter/Flint(not finished yet). His grabs are Catch(grab), Slap(pummel), Force(F-throw), Carry/Lift(B-throw) and Pound(D-throw).

**Comment by cobalt-blue** [comment]
well that certainly helps i guess. though I think that his existing forward smash should be scrapped, and replaced with an attack that mirrors link's forward smash (first swing) as it is nearly Identical to isaac's regular attack animation from golden sun.

**Comment by IngaRasen** [comment]
I personally like Blast, but I do think that it should either have some kind of armor on it, or reduced startup. Right now, the only use that the move has are for hard reads.

**Comment by zombiejerky** [comment]
Armor might be cool

**Comment by bb010g** [comment]
Merging with #1
