### ISSUE TITLE
(NOT A BUG)  Squritle's Shiny

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#252]
All the other Pokemon have a shiny form in there alts but not Squritle. Is there still room for a shiny alt since there's a N64 Mode coming which might take some costimw

**Comment by ghost** [comment]
@Darquezze N64 Mode will use a separate directory and load the Clear Brawl costumes. In other words, there will be room to add a Shiny Squirtle.
