### ISSUE TITLE
(NOT A BUG)  Squritle's Shiny

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#253]
All the other Pokemon have a shiny form in there alts but not Squritle. Is there still room for a shiny alt since there's a N64 Mode coming which might take some costumes slots away. (PS Brawl did have a shiny for Squritle)

**Comment by ghost** [comment]
@Darquezze 
![screencapture1](https://cloud.githubusercontent.com/assets/16145986/11920093/afd5ea8c-a733-11e5-93bb-d26d62038e7b.png)
![screencapture2](https://cloud.githubusercontent.com/assets/16145986/11920094/afe3ba7c-a733-11e5-8b7b-2493eb602efd.png)

I made a more accurate Shiny Squirtle by combining textures from Brawl's green and blue textures. Comparison with default Squirtle, Shiny on top, Brawl on bottom.

**Comment by Darquezze** [comment]
Really Cool! (how many slots does Pikachu have left? I would say what it is but its out of the project's goals)

**Comment by ghost** [comment]
@Darquezze Pikachu has 3 left atm.

**Comment by Darquezze** [comment]
I was gonna say remove one of Pikachu's red alts to make space for 4 spaces left so u guys could add Pichu, I would say his special attacks can be charged for stronger attacks and his Smash attacks weaker than Pikachus and he's faster and takes no damage. But like I said, out of the projects goals (And if u were to add an announcer voice, just use the Pi and chu part of the announcer saying Pikachu) and probably most people working on this would disagree

**Comment by bb010g** [comment]
We're not adding Pichu. It's outside of the project scope, and would be a wasted slot anyways.

**Comment by Darquezze** [comment]
@bb010g Exactly what I said, but I never said as his own slot I said as alt for pikachubut like we both said Its outside of the project scope.

**Comment by JackpotSHUnited** [comment]
Squirtle's shiny color is represented by Shiny Blastoise.
