### ISSUE TITLE
Link's AI gets stuck on smash taunt

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#254]
Pretty self explanatory, when fighting a CPU playing as link, there is a chance that it will do a down taunt when it gets a kill, problem is the move is done fast enough that it triggers his ocarina smash taunt, which is where he gets stuck.

**Comment by ghost** [comment]
@vinegar97 AFAIK this can't be fixed at the moment.

**Comment by DarkLink1996** [comment]
Well, is it possible to make it so that the AI can't do the Ocarina taunt?

**Comment by ghost** [comment]
@DarkLink1996 I don't know if that's possible, although that may involve disabling Link's AI taunting altogether.

**Comment by UltraSyko** [comment]
This was a problem in previous versions of PM. Honestly, AI related issues should be pushed for last

**Comment by vinegar97** [comment]
I know this is VERY low priority right now, but if anyone wants to tackle this, might want to look at fox and falco's AI data, as they also have smash taunts that don't trigger when fighting thier CPU's.

**Comment by ghost** [comment]
There are something like 2 or 3 people in the entire community who have any competence with coding AI for this game.

I've tried my hand at AI coding previously and it is an incredible pain. I have serious doubts that any progress with AI related issues will be made by this project.

**Comment by vinegar97** [comment]
Yeah I do realise that, just thought i make the issue known just incase

**Comment by UltraSyko** [comment]
Someone in the Smash 3 Team has edited the AI

**Comment by LinkTahuterasuSpirit** [comment]
Link's ai can get out of the ocarina taunt  by himself, it's just a matter on if he desides to use a special attack B, it could be possible to program Links ai to press B not long after the down taunt, though it might be tricky
