### ISSUE TITLE
Finishing up ASL Stages + New Character Stages

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#256]
https://gist.github.com/bb010g/42ef6551b0df7dfb6eff

This stage list brings back classic Melee and Brawl stages, while also adding in balanced versions of previous stages. Along with this, it adds Sky Sanctuary and Venus Lighthouse for Knuckles and Isaac to have a home stage. All stages are PMDT quality, or super close to being so. Includes web addresses to the brawl vault entries.

Also, we can debate this list. Nothing is final.

**Comment by bb010g** [comment]
Could you just put the document up in Google Sheets?

**Comment by ghost** [comment]
I can tomorrow. Don't have access to the Excel file right now.

**Comment by ghost** [comment]
I vote in favor of the list. For Pictochat, I suggest having a ROB stage there, as ROB at least has the hardware connection to it. (he's an NES controller, Pictochat is a DS application and not a game).

**Comment by chickangamer** [comment]
I also vote in favor for everything purpa said

**Comment by ghost** [comment]
[Book1.xlsx](https://github.com/TheOriginalSINe/Project-M-CC/files/68059/Book1.xlsx)

Can someone upload this to sheets?

**Comment by ghost** [comment]
Don't really want to use my personal account.

**Comment by bb010g** [comment]
I'll put it in a Gist.

**Comment by JackpotSHUnited** [comment]
Pretty sure this is WAY outside of project goals. Where's the leaked stagelist that was mentioned in another thread?

**Comment by ghost** [comment]
@bb010g Okay

**Comment by ghost** [comment]
@JackpotSHUnited still waiting for the issue entry with the screenshots from the leak thread to be made.

**Comment by ghost** [comment]
@JackpotSHUnited PMDT wanted to finish the alternate stages, and I see where you're coming from, but we have to take some creative liberty.

**Comment by bringobrongo** [comment]
I support the list. It won't hurt much to do it and the N64 stages could be Z alts (we're doing that, right?) Also, like what Thunder said, we need to take creative liberty. It also isn't hard to change stages that we don't like.

**Comment by ghost** [comment]
@bringobrongo Yes, only z stages would be 64 stages so nothing is really hidden.

**Comment by JackpotSHUnited** [comment]
There seem to be a lot of stages that are being thrown in just for the sake of more stages, though. It'll make the build look unprofessional if the stages don't look like they're up to the PMDT's standards.

**Comment by ghost** [comment]
@JackpotSHUnited The stages I included are top quality. Haven't tested each and everyone, but have watched at least a video.

**Comment by chickangamer** [comment]
then we will edit the stages so they can be project m standards

**Comment by ghost** [comment]
@chickangamer Correct

**Comment by bb010g** [comment]
https://gist.github.com/bb010g/42ef6551b0df7dfb6eff

Note: This can be forked and all sorts of good stuff.

**Comment by ghost** [comment]
It's true, there was no condition that the new stages can't be edited for use here.

**Comment by ghost** [comment]
Updated my comment on the top.

**Comment by bb010g** [comment]
Ok, after a bunch of Discord discussion, changes this drastic are out of scope and are being tabled until at least February to give things more time to settle.

**Comment by JackpotSHUnited** [comment]
Even though obviously these are changes we won't be making anytime soon, here is my proposal:

https://gist.github.com/JackpotSHUnited/c6e01dfe06a6ac45ff5d

Not everything from this list needs to be implemented, but some changes might help with organization.

**Comment by bb010g** [comment]
Put those under #57.
