### ISSUE TITLE
Intro Screen Rename

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#258]
Currently, the intro screen right before loading says the game title is "Project M 3.61 Community Complete". However, this project's name doesn't include the PM version number in it.

Suggested fix: Changes that screen to say "Project M Community Completion"

**Comment by bb010g** [comment]
I'm kinda growing to like 3.61 CC. It quickly shows the base version of the characters.

**Comment by ghost** [comment]
@bb010g I like the name as well for that reason. Perhaps we should update the readmes and such with the name change instead.

**Comment by vinegar97** [comment]
i kinda view "project m-cc" as a short, quick way to make it obvious that you're talking about this build,
and "project m 3.61: cc" as the official name of it, just throwing my two cents.

**Comment by Nekudot** [comment]
I think including the 3.61 is ...stupid. The first release will include Lyn and Knuckles which aren't part of the "official" 3.61" release, and IIRC a lot of the content from that leak was buggy or included balance changes and was reverted to 3.6. This project isn't in any way part of the PMDT, so why should we follow their (wrong) version numbers?
So I agree that it should be changed to just PMCC, with a small v1 or something at first release. This project needs it's own identity, even if it's using a lot of the PM content.

**Comment by JackpotSHUnited** [comment]
How about Project M 3.99, since it's not quite 4.0 just yet?

**Comment by bb010g** [comment]
@Nekudot What content was reverted to 3.6?

**Comment by Nekudot** [comment]
@bb010g Sorry, that was wrong. That happened in the first few days and looking at the 3.6 Fighter revert folder and the few files included there I thought that was still the case, but, looking at the commits, all of them were changed to 3.61. 
My point still stands though, this isn't PM3.61, it's PMCC. If anything, it should be 3.7, but an unnoficial build like this shouldn't follow the official version numbers.
Also, I hope in the future this is what will be widely used and not other builds that will pop up everywhere once the new characters work properly, so having a distinct name is a plus.

**Comment by pharoahfawcett** [comment]
I second Nekudot

**Comment by andy-bond** [comment]
Just curious, but was a consensus reached here? In my opinion, we should not include the 3.61. 

Eventually, we plan on having a release build.. that will be PMCC 1.0. We will have to have a way of tracking our own versions... It would be confusing to have PM 3.61: CC 1.0.

Regardless, we need a decision to either close this issue or have someone look into fixing it. Thoughts?

**Comment by somealternateaccount** [comment]
Locations currently say 3.61. I don't really see an issue with this - the major concern would be further differentiation.

@TheOriginalSINe: comments?

**Comment by KymaeraK1ng** [comment]
It should be PMCC 3.61/3.7/3.99.

**Comment by LinkTahuterasuSpirit** [comment]
technically the community completion should be at like 1.0 sense it's not made pmdt just using everything planed for pm before they stopped development, and the community completion might add there own things when the're finish with what was left over by pmdt. in fact isn't retro mode a cc exclusive?

**Comment by bb010g** [comment]
My vote is Project M 3.61 Community Complete, abbreviated 3.61 CC. Once we get version numbers, those can be appended. The base is still 3.61, just with the CC set of patches. It would more reflect what I'm trying to figure out how we could smoothly move to, which is CC as project that makes a mod collection (essentially patches for the most part, in both how CC uses them and how they should be installable) and also happens to make a build with all their stuff in one convenient place. I should probably open an RFC about this to keep notes as I figure out logistics.

**Comment by LinkTahuterasuSpirit** [comment]
@bb010g yea that makes sence
