### ISSUE TITLE
Including New Stages confirmed by devs?

### ISSUE THREAD

**Issue by LoanSPW** [TheOriginalSINe/Project-M-CC#260]
According to Llama Juice (dev of PM), an HD version of Kongo Jungle was planned to be included in ver 4.0, so I was wondering if someone is going to make one for PMCC.
Source: https://www.reddit.com/r/SSBPM/comments/3i3ius/hd_melee_stages_in_the_next_update/
"Does this mean that we're done rehashing old stages? No, of course not. I'm still super excited to see Kongo Jungle HD, and I know you guys are too."

It could look like something like that: 
![kongojunglehd](https://cloud.githubusercontent.com/assets/16327543/11940017/fff6b968-a825-11e5-8d00-0bdd4e9988df.png)

Also that same developper said in a topic in Smashboards that Jungle Japes was set to be its alternate stage (the 64ver being put as an hidden alternate stage) and Green Greens was set to be put as an alternate stage for Dreamland HD, due to the team wanting to have all the stages from Brawl coming back (except 3, which are unpopular and hard to play on: Mushroomy Kingdom, 75m and Mario Bros.).

If we follow this statement, that means that Mario Circuit was set to come back!

So what do you think about this?

PS: Just my opinion: I remember that Peach's Castle (Melee) was found as an alt for Bowser's Castle in the files of 3.61. If Mario Circuit comes back, I think it would be better to put PC as an alt for it.

**Comment by bb010g** [comment]
This sort of discussion goes in #57, at least for now.

**Comment by ghost** [comment]
@LoanSPW Me, Theytah, and Mewtwo2000 made that Kongo Jungle! Thanks for showing it.

**Comment by LoanSPW** [comment]
Oh ok, that was in the "leak", so second fake!
By the way, awesome work!

**Comment by ghost** [comment]
@LoanSPW That may not be fake, actually. Theytah used parts of the Dreamland HD we worked on together in both his first attempt at Dreamland HD, and the revamp of his version that is in PM. In other words, they probably planned to use that as a base, although we know that they never had the time to do much of anything to it before shutdown happened.

**Comment by LoanSPW** [comment]
Oh that's interesting, thanks for the information! :)
