### ISSUE TITLE
Include new music that was confirmed...

### ISSUE THREAD

**Issue by LoanSPW** [TheOriginalSINe/Project-M-CC#261]
It was confirmed a while ago by the composer of the PM Menu theme, Phonetic Hero (who also composed Bad Mario),  that Battlefield and Final Destination versions of this theme were set to be made.

We could ask him to do/share these if you're ok, maybe he'll accept.

**Comment by bb010g** [comment]
Could you ask him?

**Comment by Kippy232** [comment]
Sounds cool

**Comment by LoanSPW** [comment]
The problem is that my english isn't that great so...
Maybe you could ask him via his Youtube channel.

And he talked about these new versions of the PM Theme on a comment of the video.

**Comment by aalbert360** [comment]
Final Destination - http://youtu.be/744wHNCAm9U
Battlefield - http://youtu.be/2laYCmQxg-A
Training Room - http://youtu.be/aRKwvAup7Qg

For Battlefield, I prefer to replace "Multi-Man Melee 1 (Melee)" because I like the other music. For Final Destination should replace either "Credits (Super Smash Bros.)" or "Giga Bowser (Melee)".

**Comment by ewmb7701** [comment]
Personally I don't really like these themes; they're not really intense enough for my tastes.

If we were to replace any music, it seems obvious to me we should replace the Brawl themes for those stages, as that's what the Project M menu theme did to the Brawl menu theme.

**Comment by Kippy232** [comment]
Replacing the Brawl theme seems like the most logical course of action. It'd be a great way to distance the project from the original Brawl. Also, most of the original themes are rather bullocks anyway.

**Comment by JackpotSHUnited** [comment]
We should not use fan remixes. Only use Phonetic Hero's tracks, if he even ever got around to making them.

**Comment by zombiejerky** [comment]
I like the training room alot

**Comment by zombiejerky** [comment]
I like the training room remix a lot.

**Comment by LinkTahuterasuSpirit** [comment]
@JackpotSHUnited what if he doesn't want to do it? besides there are some great fan remixes that can replace original brawl music

**Comment by bb010g** [comment]
Out of scope.
