### ISSUE TITLE
Awakening Roy Super Scope Lighting Issue

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#269]
![image](https://cloud.githubusercontent.com/assets/16145986/11969046/3b0eed9c-a8e2-11e5-828b-63031665d1fa.png)

When characters charge the Super Scope, they are supposed to turn completely yellow. On Awakening Roy, this oddly only happens to certain parts of his armor.

This only seems to happen on Bowser's Castle, tested in Dolphin.

**Comment by Darquezze** [comment]
Looks cool tho

**Comment by LinkTahuterasuSpirit** [comment]
@Darquezze yea looks cool, reminds me of the light armor in triforce heros

**Comment by bb010g** [comment]
@LinkTahuterasuSpirit If you have nothing substantial to add, please don't bump old issues.

**Comment by LinkTahuterasuSpirit** [comment]
@bb010g woops sorry

**Comment by bb010g** [comment]
Reopening until confirmation either way.
