### ISSUE TITLE
Isaac's neutral B is broken in Stamina mode.

### ISSUE THREAD

**Issue by AJ3450** [TheOriginalSINe/Project-M-CC#27]
If you have no blastzones in stamina mode and the sword does not land on the stage, Isaac is thrown all over the place and pretty much dies instantly.

**Comment by PKPenguin321** [comment]
hilarious

**Comment by PKPenguin321** [comment]
just tested this, can confirm it is hilarious

probably caused by isaac's firey sword thing counting as a part of him and not a true projectile
