### ISSUE TITLE
Knuckles, Lyn and Issac have no portraits in the Replay Room

### ISSUE THREAD

**Issue by UltraSyko** [TheOriginalSINe/Project-M-CC#273]
Super Minor but...hey
There's always room for perfection 
![00000000-361](https://cloud.githubusercontent.com/assets/16283463/12004732/6978f028-ab40-11e5-8096-b39403cf27ed.png)
![00000000-362](https://cloud.githubusercontent.com/assets/16283463/12004734/6def58f4-ab40-11e5-87c8-bb6e79bea1ce.png)
Knuckles = Roy
Issac = Sonic
Lyn = Snake

**Comment by Kippy232** [comment]
Is this tested with Wifi Set, and/or Full Set?

**Comment by UltraSyko** [comment]
Full Set

**Comment by somealternateaccount** [comment]
I don't think this is of really any priority, since replays don't work anyway on the full set. If it's implemented properly for Mewtwo and Roy, fixing this would be nice but doesn't really block us on anything.

**Comment by LinkTahuterasuSpirit** [comment]
@somealternateaccount true, this seems the be a last polish when everything else is said and done

**Comment by TheSmashBoy** [comment]
I actually fixed that.
