### ISSUE TITLE
Knuckles: Rolling to an edge makes you fall

### ISSUE THREAD

**Issue by mamimamis** [TheOriginalSINe/Project-M-CC#274]

**Comment by bb010g** [comment]
Can you make sure you're updated to master? This should have been fixed in #190.

**Comment by mamimamis** [comment]
I did update it

**Comment by mamimamis** [comment]
Do I have to use the text codeset? because im using the codes thats in codes not in text codesets, because I dont know how to use them :P.

**Comment by ghost** [comment]
Can we get a confirmation this is happening from anyone else?

I previously fixed this issue. It should no longer be present in the main build unless someone overwrote it.

**Comment by MatLax** [comment]
If OP is talking about dodge rolls I don't have any issues running the very latest version as of december 29th, 12pm EST

https://gfycat.com/EvergreenRaggedBlackwidowspider

If OP is talking about rolling with down+b then I don't see anything wrong...

**Comment by bb010g** [comment]
Closing. If @mamimamicuzpipi can provide reliable steps for reproduction on master, we'll reopen this.

**Comment by ghost** [comment]
Thanks @MatLax for testing this

**Comment by mamimamis** [comment]
Can someone help with the codeset because i dont know how to use the text ones
