### ISSUE TITLE
GameCube adapter not reading

### ISSUE THREAD

**Issue by darkralts** [TheOriginalSINe/Project-M-CC#276]
The GameCube adapter won't recognize GameCube controllers in project m.

**Comment by Kippy232** [comment]
Tested on what system (Wii, Wii U, or computer)? Tested with what set (Wifi or Full)?

**Comment by darkralts** [comment]
Wii u, official adapter, full set, homebrew

**Comment by somealternateaccount** [comment]
I don't believe this was ever working even in vanilla PM.

**Comment by Kippy232** [comment]
To my knowledge, that may be an issue that I'm not sure they ever fixed. Unfortunately, I don't have a Wii U to test this on.

**Comment by darkralts** [comment]
It works with melee through nintendont on wii u so maybe a code to activate
the gc adapter ports when pm is launched. Just some ideas.

**Comment by Kippy232** [comment]
A quick Googling yielded informative results: it doesn't work. 
https://www.reddit.com/r/SSBPM/comments/3b8z8e/launcher_updated_to_support_the_wii_u_gamecube

And, it seems Nintendon't supports GameCube games, but not Wii games. Sorry, pal :/
https://github.com/FIX94/Nintendont

**Comment by bb010g** [comment]
Known issue. This is probably going to be a won't fix, as PMDT couldn't even get the adapter to work in game. It can work on Homebrew (it does in the launcher), but trying to stick all of that on top of Brawl would be quite a feat. (Nintendont has the advantage here with Melee as it deals with all the incoming inputs and isn't written in ASM on top of another game.)

**Comment by MatLax** [comment]
To add to bb010g's comment, somebody from the PMDT confirmed on a Reddit AMA that he was the one who was working on implementing the Gamecube Controller Adapter compatibility and he never managed to get anywhere, if this problem ever gets resolved it would be by the hombebrew community and it would make the adapter compatible with any Wii games, for which the controller is an option, at the same time.

**Comment by somealternateaccount** [comment]
Closing this - the PMDT wasn't able to do it and if anybody would like to contribute code it would be nice if they could instead focus on some of the other issues as this one seems insurmountable.

**Comment by darkralts** [comment]
oh well... hopefully this will work as a side project after pm cc is actually completed as i only have a wii u ATM. i like pm far better than melee brawl and smash 4.
