### ISSUE TITLE
(Maybe a bug) Knuckles charging Down-B does no damage

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#279]
Unlike Sonic, Knuckles' Down-B does no damage when charging (not sure if a bug or not)

**Comment by Kippy232** [comment]
It seems reasonable for the charging animation to be just slightly stronger than Sonic's. In any case, it does seem odd that it does no damage.

**Comment by ghost** [comment]
@Darquezze It _may_ be intended, as Knuckles' version of the move is faster and stronger than Sonic's by some degree.

**Comment by ghost** [comment]
@Darquezze , I checked up on some things, and you were right. It's a bug. I'll try implementing some stat edited Sonic hitboxes for it.

**Comment by Darquezze** [comment]
@Rage17 I was thinking it wasn't because correct me if I'm wrong, in Brawl, charging down-B with Sonic did no damage and the PM Team may have wanted that.

**Comment by ghost** [comment]
@Darquezze It seems that Knuckles' PSA file has his charge point to the wrong spot while looking for the hitboxes(he looks for the same place Sonic does, despite Knuckles' file having it in a different place because of filesize differences).

**Comment by ghost** [comment]
This issue should get closed, the new Knuckles has a down b charge hitbox.
