### ISSUE TITLE
(Probably out of projects goals) The infamous Waluigi Mod made by Marioking64DS has been released

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#281]
MarioKing said he's will be using the Dev build for Waluigi and should we add him to CC when the PM version released? (But like I said probably out of the projects goals)

**Comment by Nekudot** [comment]
Not an issue. And that's not the point of the project at this time.
I don't believe there will be new characters included in the future either, selecting what character(s) should be included is gonna be a nightmare...

**Comment by cimpyhigh** [comment]
Yeah, this should be closed...

**Comment by Tac24** [comment]
indeed.... what the hell would one do with the CSS?

I think its on the individual to put the codeset and files in their own game, hopefully the creator will provide such files and explain where they go
