### ISSUE TITLE
Y alt for Norfair Crashes

### ISSUE THREAD

**Issue by remivamp** [TheOriginalSINe/Project-M-CC#282]
I was playing on the Y alt for norfair a while ago. Wario and Lucas in their default costumes and with no changes from PM. All was fine and dandy until the stage up and crashed on me when trying to separate for the third time the 2 platforms. Someone should fix ths

**Comment by bb010g** [comment]
IIRC the Norfair alts are going to be removed due to having no good reason to be there (they're old versions that were replaced due to balance).

**Comment by remivamp** [comment]
Oh. I just prefered to have the stages mirror and just didnt want to crash.

**Comment by ghost** [comment]
@bb010g this should get closed. We got the confirmation that the new alts are just Wiiztec's custom stuff.
