### ISSUE TITLE
Lyn holds items in a strange way

### ISSUE THREAD

**Issue by PatziPatzpatz** [TheOriginalSINe/Project-M-CC#283]
The Cracker Launcher
![img_0748](https://cloud.githubusercontent.com/assets/7726167/12079533/f466090c-b23c-11e5-94c0-18a64d0a179f.JPG)

And the 2 hammer items (both pictures are of the normal hammer but she holds the Golden Hammer in the same way)
![img_0749](https://cloud.githubusercontent.com/assets/7726167/12079534/f46a804a-b23c-11e5-9e56-59f2b989e7b4.JPG)
![img_0750](https://cloud.githubusercontent.com/assets/7726167/12079535/f46f76a4-b23c-11e5-8705-d024cc67f2fb.JPG)

**Comment by Kippy232** [comment]
Can most definitely confirm. You should see her with a barrel; using your face to bore a hole into it is not, in fact, the proper way to use it.
