### ISSUE TITLE
Sami: Up Special Wind box Glitch

### ISSUE THREAD

**Issue by DestinyHiro** [TheOriginalSINe/Project-M-CC#285]
When using two Sami's'  up specials next to one another, they go up and beyond the stage boundaries endlessly (unless canceled). This might have to do with the wind box on her Up Special.

**Comment by zombiejerky** [comment]
Its suppose to be a parachute so I can see why it does this

**Comment by Kippy232** [comment]
Also worth noting, it seems Sami's Up Special has no ending to it. She will simply float on indefinitely. Not sure if a bug, poor coding, or simply intended.

**Comment by zombiejerky** [comment]
I think sami is suppose to have a parachute
