### ISSUE TITLE
[RFC] 64 Costume Progress

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#292]
- [ ] Bowser: FS eyes
- [ ] Captain Falcon
- [ ] Charizard
- [ ] Diddy Kong: Some items
- [ ] Donkey Kong: FS eyes
- [ ] Falco
- [ ] Fox
- [ ] Ganondorf
- [ ] Ice Climbers
- [ ] Ike
- [ ] Isaac
- [ ] Ivysaur
- [ ] Jigglypuff
- [ ] King Dedede
- [ ] Kirby
- [ ] Knuckles
- [ ] Link
- [ ] Lucario
- [ ] Lucas
- [ ] Luigi: FS eyes
- [ ] Lyn
- [ ] Mario: FS eyes
- [ ] Marth
- [ ] Meta Knight
- [ ] Mewtwo
- [ ] Mr. Game & Watch
- [ ] Ness
- [ ] Olimar
- [ ] Peach: FS eyes, items
- [ ] Pikachu
- [ ] Pit
- [ ] R.O.B.
- [ ] Roy
- [ ] Sami
- [ ] Samus
- [ ] Sheik
- [ ] Snake
- [ ] Sonic
- [ ] Squirtle
- [ ] Toon Link
- [ ] Wario: Model almost done, textures, biker
- [ ] Wolf
- [ ] Yoshi
- [ ] Zelda
- [ ] Zero Suit Samus

CC: @StupidMarioFan1

**Comment by mamimamis** [comment]
I would like to see N64's DK :P

**Comment by ghost** [comment]
@bb010g Since 64 mode went "indie," this should be closed.
