### ISSUE TITLE
New Knuckles Costume Oddities

### ISSUE THREAD

**Issue by vinegar97** [TheOriginalSINe/Project-M-CC#296]
After the new leak's knuckles was committed, the character select portraits no longer match the actual costume they are paired with, as some of these were changed from the previous  version.

in addition to this, the new white costume's shoe texture seem to be shoddily made, and there are three new semi alts based on the chaotix that are not loaded, and the one based on espio has his gloves positioned slightly differently than the other costumes.

**Comment by PKSmashOmega** [comment]
The Chaotix costumes all look fine in-game. The only things missing are the CSPs, BPs and Stock Icons. After someone creates those (and 3 more costume slots) they should be ready for the build. (Also, +1 for the leak in #267). Edit: Picture
![chaotix knuckles](https://cloud.githubusercontent.com/assets/16218387/12210875/49584010-b6b1-11e5-9163-390f68020bce.png)

**Comment by Kippy232** [comment]
Can confirm. Gray CSP leads to Black Knuckles. Purple CSP leads to Maroon, Tribal-based(?) Knuckles (very cool btw). Gold/Yellow CSP leads to White Knuckles. 

@PKSmashOmega Very cool alts, I'd love to see them in-game soon

**Comment by pharoahfawcett** [comment]
wait, what new leak?

**Comment by vinegar97** [comment]
@pharoahfawcett from #288

**Comment by zombiejerky** [comment]
There based off  the Chaotix , these are great alts

**Comment by vinegar97** [comment]
![output_5dbt8k](https://cloud.githubusercontent.com/assets/16244042/12224246/daa701b8-b7fc-11e5-890e-78e5f5b1dd66.gif)

made a gif of all the alts we currently have to demonstrate espio's gloves and white knuckles' shoe weirdness

**Comment by Kippy232** [comment]
I'm not seeing the weirdness with white Knuckles' shoes. Could you explain more?

**Comment by vinegar97** [comment]
If you look closely, you'll notice that the area where the yellow and white meet has a weird transition, it's hard to explain if didn't look at the texture themselves, but trust me it's there.

Either way, a fix for the csps is being worked on by me, and the white shoes have been fixed by lnkthewolf over at discord.

**Comment by projectbrawl7** [comment]
Oooh, i want. Will these be released soon?

**Comment by bb010g** [comment]
Any updates?

**Comment by vinegar97** [comment]
@bb010g yes.
![output_zkptbi](https://cloud.githubusercontent.com/assets/16244042/12814060/420436d8-cb4d-11e5-8741-43def588af45.gif)

some changes might not be as obvious as others, but here are some highlights:

-updated tribal knux's shoe shine to the newer leak version, and also changed his socks to be a purple-ish blue, to complete the reference the costume has (gonna need opinions on that BTW).

-cleaned up the shoe texture for white knux (thanks to @LnktheWolf).

-fixed espio knux's gloves.

-added spec map for vector knux (thanks to @Rage17).

just gonna have to add the menu assets, review some stuff and it should be good to go.

full changelist is gonna be in the pull request when i make one.

**Comment by KymaeraK1ng** [comment]
BUT WHEN CAN I HAVE IT

**Comment by vinegar97** [comment]
Fixed in #351, closing
