### ISSUE TITLE
Knuckles: Up-B changed to Sonic's Up-B?

### ISSUE THREAD

**Issue by drewilliam** [TheOriginalSINe/Project-M-CC#297]
Wasn't sure where else to post this. Wondering why Knuckles Up-B was changed to be the same as Sonic's Up-B. It used to just be a shorter height version of Sonic's. I liked how it originally was, made the characters more unique. Knuckles' recovery may be bad the original way, but I didn't think it made him a terrible character. And with the glide and wall climb, he still had his own options. I also feel like a shorter Up-B could make it easier to combo with.

I know I can always change back to the original Knuckles leak, I'm just wondering what the community concencous is on the issue and how the change came to be. If any of you could point me to a discussion thread where I should have posted this, I would appreciate it.

**Comment by Kippy232** [comment]
I think this was changed unintentionally.

**Comment by chickangamer** [comment]
This was changed intentionally not a lot of people liked the up b that much

**Comment by Kippy232** [comment]
@chickandgamer it wasn't disliked so much as it was very inconsistent. The large issue was that when grounded it behaved exactly like Sonic's.

**Comment by bb010g** [comment]
Leaving as is for now.
