### ISSUE TITLE
Mewtwo crash

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#298]
Whenever I load a match with Mewtwo, CPU and Player, the game crashes.

**Comment by bb010g** [comment]
Does the match just have to have a Mewtwo in it, or are there other conditions?

**Comment by icecapman10** [comment]
Its Mewtwo and Kirby together.

**Comment by bb010g** [comment]
Works fine on my end. Try formatting your SD card and reinstalling.

**Comment by icecapman10** [comment]
I just formatted and reinstalled the game. It still crashes.

**Comment by somealternateaccount** [comment]
Please include a more detailed issue report: Which characters are playing, on what ports, mode, stage, etc. to facilitate testing.

**Comment by icecapman10** [comment]
It's only Mewtwo and Kirby, on all ports, all modes, and all stages.

**Comment by bb010g** [comment]
cc/ @PyotrLuzhin

**Comment by LnktheWolf** [comment]
@icecapman test it between roy and kirby to see if it's a clone issue

**Comment by DestinyHiro** [comment]
@LnktheWolf  I already tested with Roy it happens to him too, it involves their Hats; also Lyn and Knux have a similar effect which is that Kirby is stuck in the last frame when he stuck he can only move side to side at least in my build. It doesn't happen to Sami and Isaac apparently.

**Comment by SteveDevGit** [comment]
This happened to me as well with Mewtwo so I just avoided using him.

**Comment by icecapman10** [comment]
It's now where the stage loads, but when Kirby enters, the game crashes.
