### ISSUE TITLE
Lyn: Neutral B Animation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#30]
Animation while charging neutral B (bow and arrow) is unfinished. No string draw and stiff movement. Odd lighting effects near feet.

Suggested Fix: Model animation off of Link's with a Bow string animation, removed shining light effects, and add dust effect near feet.

**Comment by cobalt-blue** [comment]
if it's possible that the effort wants to be spent, animate her charging it like her critical hit animation from FE7.

https://www.youtube.com/watch?v=ra17w-NZMLM

as for use in the air, i'd suggest make it impossible to charge while she's airborne.

**Comment by ghost** [comment]
Having a new animation would be nice, but the frame data should remain unchanged

**Comment by cobalt-blue** [comment]
I'd suggest having a proper look at the move as a whole - the range, knockback and damage that thing can do is quite overbearing.

**Comment by ghost** [comment]
Eh, I wouldn't touch any of the new character movesets for now beyond bug fixing and cleaning animations. Frame data for the shouldn't be a priority, considering they will be purely for casual play.

**Comment by cobalt-blue** [comment]
fair call, you're completely right in that it is pretty low necessity right now.

my local scene has already come to the agreement that we might use this build for private tourneys if it ends up being balanced around P:M 3.6 so i guess I was getting ahead of myself there.

**Comment by ghost** [comment]
I was actually planning on using this build at private tournaments too, but we decided that the new characters shouldn't really be touched beyond bug fixes and maybe cleaner animations.

**Comment by bb010g** [comment]
[**@JekyllMD**](https://github.com/JekyllMD) commented on [Dec 4, 2015, 3:06 PM PST](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/issues/30#issuecomment-162106260):

> I was actually planning on using this build at private tournaments too, but we decided that the new characters shouldn't really be touched beyond bug fixes and maybe cleaner animations.

Where did we decide that? Link?

**Comment by ghost** [comment]
"We" being the small group including myself that would use this at our private tournaments. I wasn't saying that's what will happen to this project; I was merely pointing out one difference the people at my private tournaments have to cobalt-blue's. He would like to balance the new characters more, while I would rather leave them be.

**Comment by bb010g** [comment]
Ok, makes sense. In that case, you should be able to just stop updating once the polish is to your liking. We probably won't have balanced much by then.

**Comment by cobalt-blue** [comment]
really, having played around with them for a fair amount, they don't need much. hell, Wizztec stated he'd be fairly confident that in their current form the two would be healthy for the 3.6 meta (with a bit of bias towards knuckles). it's the big reason I'm following the work here, with just getting them stable and working being the first major goal and all.

**Comment by ghost** [comment]
No changes to frame data should be done unless it's a bug in effort to preserve PMDTS work as best as possible. Only notable exception being Lyn's down B as it was a none functioning move.

**Comment by bb010g** [comment]
This is a balancing issue. Lyn was not a finished character, and if her counter or bow draw time makes her unbalanced, it should be changed. Keep in mind that the PMDT was probably more interested in functionality before they put in the proper frame data for balance.

**Comment by ghost** [comment]
The point though is that this isn't a balance project. We have no idea how "balanced" the characters or moves are and honestly wouldn't be able to tell without the hundreds of hours of playtesting that usually goes into balancing these characters. The project is about taking the dev version and making it playable.

**Comment by bb010g** [comment]
I agree that this is about making the dev version playable, but I don't see why we shouldn't try to finish the new characters. Leave the others as they were (which probably means rolling back Samus according to [this](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/blob/8316e6449fead21aa61ec14ff56e0c2c01319d55/3.6.1%20Change%20List.txt)), but give the new characters some playtime, look at how they're doing, and balance carefully. Once the crashes are taken care of, we should be able to get people to test out the new characters. I've already seen quite a few people on /r/SSBPM and /r/smashbros talking about how they're picking up Knuckles as a secondary, _despite_ his current status.

**Comment by ghost** [comment]
Because, once again, this isn't a balance project.

This project will be complete when all 3.6 bugs are squashed and the cast, including lyn and knuckes, are completely playable.

If, after that, some people wanna take characters and do balance changes, that could be a new project. But as balance is extremely subjective, there are almost no balance changes that can be done on this project that everyone would agree on.

**Comment by Eltrion** [comment]
The Bow is blatantly overpowered though. I'm of the opinion an exception should be made and Lyn's Bow should be tapped back, roughly in line with Link's Bow. 

Everything else should be left alone though.

**Comment by ghost** [comment]
So I played around with the move for a while and now I will admit, the data is rather overbearing. Even to the point of being broken, similar to Lyn's Bair. This could justify adjustment to the frame data.

Tested on FD, uncharged does 7 damage at point blank and 13 at full stage length. Fully charged does 15 at point blank and 21 at full stage. For reference, Link's Bow does 5 damage uncharged, 15 damage fully charged, and damage doesn't scale with distance.

I think it can be balanced without altering the move's functionality or purpose, but just by tweaking the numbers. As I've said before, I think sticking as close to the PMDT's design is the best route for the project.

The issue seems to be, as in most cases, an imbalance between risk and reward/effort and payoff. It takes little effort/skill to land an off stage arrow and doing so can net a kill in too many cases, ie at low %'s

To balance this, I think mainly the move should be made harder to land, and to a lesser extent, the damage should be scaled back (it is a tad overbearing).
- The main change I'd suggest is making the arrows slower by a substantial %. The exact amount would require testing but ~15% sounds good as a back-of-the-napkin estimate. This makes landing the shot at long range more difficult and justifies the move's increasing power as shot distance increases.
- Add 3-5 frames of endlag to the move. This increases risk for players who use the move offstage in order to increase their chance of landing the shot. This also has the twofold effect of discouraging using the move to camp. With more endlag, grounded spam of the move is less safe, so players have more incentive to shorthop when using the move in order to cancel the endlag. The aerial version has a sharper downward angle and therefor has a much shorter range, making it less viable for camping.
- Finally, bring the damage down across the board by ~2%. That would change it to 5-11% uncharged and 13-19% at full charge. Again, the exact number would require some playtesting but I believe this would keep the move from gimping low % opponents. I don't think a substantial amount more than 2% would be needed as the other nerfs increase the difficulty/risk of the move and if a player manages to land an offstage shot with this they should be rewarded for it.

**Comment by ewmb7701** [comment]
@Azuran17 I was playing this build with my friends and we pretty much decided on those very same things you said.

**Comment by ghost** [comment]
I'll open a new issue specifically for changing the move properties

**Comment by bb010g** [comment]
#98 is the related issue.

**Comment by somealternateaccount** [comment]
This looks like it has been resolved due to Lyn's recent arrow changes? Needs to be checked for completeness.

**Comment by ghost** [comment]
EDIT: Whoops, this issue is specifically for the stiff animation Lyn has when charging bow shot. Balance discussion is happening in #98

**Comment by cobalt-blue** [comment]
what we need is the animation redone (it's obviously a placeholder currently), and I suggest to change it to her bow stance and animation from FE7. the attack should charge at the frame that mirrors the sprite highlighted with the red dot below.

![14093](https://cloud.githubusercontent.com/assets/16147993/11939163/bcf29e60-a867-11e5-9645-bc25c1748727.gif)

**Comment by bb010g** [comment]
Subsumed by #305
