### ISSUE TITLE
Knuckles fixes

### ISSUE THREAD

**Issue by cimpyhigh** [TheOriginalSINe/Project-M-CC#302]
I have no idea how to make a pull request, but here's a link for some Knuckles fixes. Includes victory animations and taunts. 
Here's the link: https://www.mediafire.com/?0i4jpk2b222slt0

**Comment by chickangamer** [comment]
the nuetral special could be changed its has a bug and the about to trip animation should be changed to the current one 

you should just build off the current one

**Comment by Kippy232** [comment]
@chickandgamer if Knuckle's Neutral Special has a bug, you should make an issue for it, if I understand correctly. 

@cimpyhigh what exactly are your changes?

**Comment by bb010g** [comment]
@cimpyhigh http://stackoverflow.com/a/14681796/1098906

If you need more help using Git, ask on the Discord or Gitter.
