### ISSUE TITLE
Sami Solo Mode Crash

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#304]
title

**Comment by Kippy232** [comment]
Can you describe the exact requirements for the crash?

**Comment by icecapman10** [comment]
On the character select in a solo mode, when I highlight Sami, the game crashes.

**Comment by Kippy232** [comment]
Did you make sure you downloaded the most recent version?

Are you loading Wifi Set, or the Full Set? Are you using Dolphin or Wii? Wii U?

**Comment by icecapman10** [comment]
I have the most recent version (yesterday). I have the Dev Resources on the card. I'm using a Wii U.

**Comment by Kippy232** [comment]
Okay, just asking for posterity. I'll test it out when I get a chance

**Comment by icecapman10** [comment]
Thanks

**Comment by Tac24** [comment]
sami wouldn't even work for me... reverted to old codeset

**Comment by GunBlazer** [comment]
Duplicate of #321

**Comment by PowerpointSmasher** [comment]
@Hemijack Lol how could this be a duplicate when it came first

**Comment by GunBlazer** [comment]
...that's what sleep deprivation does to you.
