### ISSUE TITLE
[RFC] Lyn: Animation Polish

### ISSUE THREAD

**Issue by ManlySpirit** [TheOriginalSINe/Project-M-CC#305]
Not entirely sure if this is within the scope of the project, but some of Lyn's animations are really wonky and unnatural, particularly her grounded Neutral B charge, and her Side Smash charge. The stance she takes when holding her sword or charging her bow is not very natural looking, and doesn't look like the sort of stance that could deliver the power necessary. Particularly, her foot placement is off. 

Her entire Up Smash animation is a little weird as well.

If you watch the original leak video from last year, you can notice that a lot of these animations were a lot more polished, and her stances in her Smash charges, as well as her Neutral B charge looked a lot more natural. I suppose this could serve as good reference.

Also, not entirely related to this particular issue, but something else I noticed from the old leak video is that Lyn had a voice clip for when she landed a critical hit with her Down B (Vantage).

One final thing I noticed, is her facial expression when she does her Down B... It's very uncanny.

I would imagine that this degree of polish would be further down the line, but I feel like it's worth mentioning now so it can be addressed in due time.

COLLABORATOR EDIT: Please use this post to discuss possible _complete animation reworks_ for Lyn's moveset.

**Comment by AJ3450** [comment]
Most of this is because of the fact that she is forced to sheathe her sword after each move. If someone was to make a new model with her holding a sword this would probably be easier.

**Comment by ManlySpirit** [comment]
I disagree, it has nothing to do with the sheathing of the sword at all.

It's more to do with the stance she takes in the opening frame of her animation. The "anticipatioj" stance she takes when charging her attacks is just not very natural-looking. Particularly with her smash charges, she needs to shift her weight toward her back leg, in a more defensive stance while charging her attacks.

I'll elaborate further tonight when I have access to the game so I can illustrate what I mean with photos.

Also, what you're suggesting would ruin the character. Not to mention, the majority of her animations are fine, she just needs a few polished up or changed here or there. Scrapping everything and redoing all her animations so she has her sword out at all times is not only going too far, but also going against the PMDT's vision with Lyn.

She's supposed to be a Iaijutsu character. The very principle of that sword style is quick strikes from a sheathed sword, only to resheath it again.

Not only is that true to her cannon in FE, but if you take that away from her, then there's little to separate her from Marth at that point, and not much point to her inclusion.

**Comment by ManlySpirit** [comment]
Alright, I took a bunch of photos. I apologize for the delay, I've been busy. Warning: long post incoming.

Also please excuse the low quality, I'm playing on a modded Wii, and had to use my phone camera (which is quite good - but taking photos of a screen never looks good). Regardless, I'll walk you through everything. There are 25 images total, each one detailing Key frames in her movements:

1 (Aerial Neutral B): This is the aerial bow charge. As you can see, the arrow isn't aligned with the Bow Properly. 
![lsilkqn](https://cloud.githubusercontent.com/assets/16632519/12271487/a9a5b3a6-b95b-11e5-839f-8e131e2aec43.jpg)

2 The second one is mostly fine, however, I would make some minor changes for a more natural pose. Her back leg needs to be unbent, and she needs to not lean back, as you're not supposed to lean back when pulling a bow (more on this later).

![cx08neh](https://cloud.githubusercontent.com/assets/16632519/12271430/571d75d8-b95b-11e5-9531-1405f46f8f35.jpg)

3 (A from the ledge): This is get ledge attack. Her sword diappears midway through the attack. It appears to be incomplete as her sheathed sword "teleports" to its usual location after diappearing.

![nnimjhm](https://cloud.githubusercontent.com/assets/16632519/12271500/bdc79d40-b95b-11e5-8c0b-c6fcf65567e9.jpg)

4 (fast walk animation): Mostly fine, however, as you can see, the hilt of her sword dislocates from the blade as she walks.

![f20h7ol](https://cloud.githubusercontent.com/assets/16632519/12271505/c5b68548-b95b-11e5-8c43-c277e60c31cb.jpg)

5 (Down Smash Charge): This is an awful pose. It needs to be completely redone. I would personally make her stand upright holding blade and sheath in front of her. Her upper half is mostly fine, her arms just need to hold her sword in front oher her. Her bottom half needs total fixing. Particularly with her legs. Again, upright, knees unbent, feet together. As she stabs sown, her forward leg needs to come up and stomp down as she stabs. 

![i5jjp4l](https://cloud.githubusercontent.com/assets/16632519/12271571/13ec8672-b95c-11e5-953a-67452abce18c.jpg)

6 (Down Smash - Backward): Mostly fine, however, her front leg seems to stretch out a little at the femur. That aside, good pose, very dynamic.

![xshecst](https://cloud.githubusercontent.com/assets/16632519/12271611/45cf769a-b95c-11e5-8621-eed6211c8aec.jpg)

7-8 (Up Smash Charge): Really good pose. I really like it. And it's got no flaws aside from some minor clipping with the sheath. However, there's a problem with how she holds her sword. This problem appears in a variety of her attacks, and I know it's been pointed out before.
![bwgwxt7](https://cloud.githubusercontent.com/assets/16632519/12271676/9cecabfa-b95c-11e5-956d-3912a6e5da52.jpg)
![bbdafau](https://cloud.githubusercontent.com/assets/16632519/12271687/aba60f74-b95c-11e5-8bed-a17f21dc3f9f.jpg)

9-10 (Side Smash Charge): 
![osvkerb](https://cloud.githubusercontent.com/assets/16632519/12271784/30db1f4a-b95d-11e5-8268-e68f0cc5502e.jpg)
![emu5ngp](https://cloud.githubusercontent.com/assets/16632519/12271787/32b9921a-b95d-11e5-86a3-801c770f9405.jpg)
This one is one of my major issues. There's something really awkward about how she holds her sword and the stance she takes, especially with her lower body. It's not exaggerated enough for the power she gives in her follow up movements. This is what they were going for:
![iaijutsu](https://cloud.githubusercontent.com/assets/16632519/12272169/4576b6ce-b95f-11e5-812f-5aa3a51a8edb.jpg)
![maxresdefault](https://cloud.githubusercontent.com/assets/16632519/12272170/48520b3c-b95f-11e5-88c8-873d7713eb6c.jpg)
![tumblr_mon9p5gg281r0wmx8o1_500](https://cloud.githubusercontent.com/assets/16632519/12272173/4b4f1eba-b95f-11e5-9585-de311d229fe3.jpg)

She needs to shift her weight backwards more, and turn her forward foot inward and spread her legs out more for a broader and more stable stance. In martial arts, this is called a "back stance." And she needs to turn her back torward her opponent a lot more, dipping in, the point is to conceal the weapon and draw the "drawing power" from the torque of rotating the torso as the arm extends outward The more curved in you are, the stronger the spin. This also reveals some of your back to your opponent, baiting them in. This is the point of this stance. The sheath of the sword is also meant to be perpendicular to her opponent. This needs to be a very exaggerated motion, especially for a smash attack, so she really needs a dynamic "charge animation" to give the move the visual power it needs. Otherwise it looks awkward. Here you can see a simiar stance and sword strike done in live action (starts at 1 minute):

https://www.youtube.com/watch?v=vpbM1ypUYP4

11-15 (Up B): 
![jqzuinu](https://cloud.githubusercontent.com/assets/16632519/12272422/ba1ea0d0-b960-11e5-81e4-69dfabe7c510.jpg)
![p00qtjy](https://cloud.githubusercontent.com/assets/16632519/12272421/ba1dc6a6-b960-11e5-82e9-dc0d9f5b4278.jpg)
![q1qpclu](https://cloud.githubusercontent.com/assets/16632519/12272420/ba1daa86-b960-11e5-963b-c02cc45550bc.jpg)
![rcfg4hf](https://cloud.githubusercontent.com/assets/16632519/12272419/ba1daebe-b960-11e5-96af-3ebf3a45c41c.jpg)
![ykgaclm](https://cloud.githubusercontent.com/assets/16632519/12272418/ba1d1f26-b960-11e5-829e-91aa48ea2169.jpg)
The pictures should speak for themselves. The issue here happens only at the peak of the move as she's trying to twist her body to come down. In motion it looks fine, especially since it's so fast. However, if you ever pause during at UpB, you'll see this, and it looks really bad. Especially since you're likely to pause right when this is happening, since these are the most active frames of the attack.

As for fixes, I don't know if they're easy or not. But it definitely needs to be fixed. The main things is definitely with her shoulder. Her non sword arm needs to be bent at the elbow, not the shoulder, but idk. It's a mess overall. I'd have to sit down and draw it to get hands on with the pose and stuff.

16 (Vantage - Strike):  I actually feel the stretched out limbs look fine due to the high speed motion. It can be taken in as visual distortion due to the speed of the movement, the green color, defintely helps. And I think that's what they were going for. However, there needs to be some blur to help communicate this. Likewise, there's a problem with her arm as she does this, it bends all weird. Also, as pointed out earlier, she needs to be gripping that sword.

![wuc9ejw](https://cloud.githubusercontent.com/assets/16632519/12272600/a118bdea-b961-11e5-84de-b8b7fdb64f05.jpg)

17-18 (Vantage - fail/charge and Side Tilt - resheath): The issue here is mostly with her expression. I get what they were going for, but it looks really strange (almost uncanny), it looks more like she's grimacing than what's appropriate for the situation. Eyes closed is fine, but here eyebrows need to not be so burrowed. She needs to have a more "calm" look to her with her eyebrows up a little more.

![wq8ke77](https://cloud.githubusercontent.com/assets/16632519/12272934/4603169c-b963-11e5-85a5-f4a2dbfe36fa.jpg)
![lhmtebh](https://cloud.githubusercontent.com/assets/16632519/12272966/739c7d5a-b963-11e5-8e1a-7e55e970f0ae.jpg)

19 (Side Tilt - Resheath): Great pose. Great motion. However, there's a slight clipping error with her dress.

![vh4tpmf](https://cloud.githubusercontent.com/assets/16632519/12272990/956a48fe-b963-11e5-8a78-43125d046ee9.jpg)

20-21 (Side B - finish): This move looks phenomenal, only one minor change I'd make if possible. It's with her face. Her looking forward like that makes her look very uncanny. She needs to at least roll her eyes to her side so she's looking behind her.

![v229uzq](https://cloud.githubusercontent.com/assets/16632519/12273071/1c7265f2-b964-11e5-98e2-31f9fee4b732.jpg)
![hjpdytp](https://cloud.githubusercontent.com/assets/16632519/12273076/1f89d40a-b964-11e5-9da7-472e65854651.jpg)

22
![eudofkm](https://cloud.githubusercontent.com/assets/16632519/12273150/89f24afc-b964-11e5-8cc5-b315b2f3a9e3.jpg)
(Up Air): This move is just awful. Her pose is incredibly awkward-looking, and it even looks bad in motion. There isn't enough movement to the blade to merit the power it has either. I get the premise of the move, but it needs to be a lot more exaggerated, like so:

![ggac_baiken_jp](https://cloud.githubusercontent.com/assets/16632519/12273160/99523c96-b964-11e5-9594-3765f0a6570a.png)

Very similar pose. Just flip Baiken's body. Lyn's body needs to be in this exact position, but with a sword where Baiken's extended hand is. This doesn't require much change, as both movements are very similar, but it needs some adjustments nonetheless. Knee up, left leg bent backward, arm FULLY extended to give the move more curve, and most importantly, LOOKING UP at where she strikes (this is a fundamental  principle in Martial Arts - look before you strike). The biggest issues with Lyn's pose are the lack of exaggeration, the awkward placement of her legs and where she's looking. 

23 (Grab): This is a different issue altogether, but still.
![chi2hal](https://cloud.githubusercontent.com/assets/16632519/12273435/18e1e2c6-b966-11e5-8be5-9633ecceb478.jpg)

24 (Neutral B - Bow Charge):
![3xy3pck](https://cloud.githubusercontent.com/assets/16632519/12273460/36e8bb0a-b966-11e5-8b22-1bfffb5b8a4c.jpg)

This is not the proper stance for a bow, and it looks really, really bad. It's another one of my major gripes. For one, it's not even the right stance in her cannon:
https://www.youtube.com/watch?v=ra17w-NZMLM

She needs to shift her weight back, knees straight, back straight, narrow stance. You can lean her back a little like in the clip I posted, but definintely not forward. What she has now just flat out looks terrible... This is the proper bow stance:

![man_draw_bow](https://cloud.githubusercontent.com/assets/16632519/12273565/dd9f96e4-b966-11e5-8e03-bb4eb0c2303d.jpg)
![1385483627195 cached](https://cloud.githubusercontent.com/assets/16632519/12273567/e1ee6b62-b966-11e5-8acb-ed1bb3811a90.jpg)

25 (Neutral Air): 
![amgkgrg](https://cloud.githubusercontent.com/assets/16632519/12273274/4165c39e-b965-11e5-862e-09b695ec388d.jpg)
Pose is mostly fine. However, here arm seems to be a little too stretched out. On a personal note, I don't like this move because too many characters have this "spin in place" Nair. Personally, I'd go for something very different (a circular 720 rotation -front flip - with her sword above her head), but that's going against the PMDT's original vision. That said, they have changed moves on characters in the past. Still, it's mere suggestion, nothing more).

Some final things. These are mere suggestions, but I would also make three more changes to her animations in addition to no. 25.

For one, her Dair motion is way too similar to Marth. Considering the style of the character, I feel something like this is way more appropriate and fitting for her:

![ggac_baiken_jh](https://cloud.githubusercontent.com/assets/16632519/12273621/3d7ca642-b967-11e5-8dbf-67c1f02cf111.png)

The move can retain the same exact properties, and hit boxes, and everything else, however, I'd change her animation to resemble this a lot more than what she has now. Just a personal suggestion, nothing major though.

Two however, I do feel is much more important. Her Jab is AWFUL. For one, it's a funky looking animation, and the delay frames after she does her kick are terrible, making her jab totally useless. I'm not entirely sure what they were thinking, perhaps it was a placeholder and it's unfinished, but it's bad. Moreover, I feel that the punch-kick flat out does not suit a "samurai character" like her, and feel like her hitting with the hilt of the sword, and then the sheath, like so:

![175px-ggac_baiken_5p](https://cloud.githubusercontent.com/assets/16632519/12273726/bef43e4c-b967-11e5-843c-3e98bf218bb8.png)
![bbcs_jin_2a](https://cloud.githubusercontent.com/assets/16632519/12273729/c19b84b6-b967-11e5-8ac8-43c5b81c3523.png)
She doesn't have to take those poses, but they are mere examples. I think they're quick enough moves to be jabs, and to be very fluid together (plus, I already posted a clip where we see the sheath of the sword be used as a weapon with this very fighting style). Most importantly however, I think this move needs to allow for follow ups, like the side and down tilts. Going from a sheath second jab, to a stab or a slash seems fitting and fluid.

Finally, her Up Smash and Up Tilt need to be cswapped with each other (she can keep the same USmash Charge animation though). For one, her USmash as it is now, is a very awkward move, that wouldn't seem like it would properly hurt someone as much as it does if she's just gonna strangely poke the air. I think such a move is much more fitting her to be her UTilt. And her USmash should be her current two hit Utilt move. Especially since that move is a critical hit animation in FE, it makes perfect sense for that to be the more damaging and powerful move.

That's my suggestion. Swap her Utilt and USmash for each other, keep everything else the same, barring the knockback and damage properties. I feel that'd be the easiest solution.

And that's basically it. I feel that aside from these issues, the rest of Lyn's motions and animations are really good. Her arials and tilts are all very solid, and her resheathing animation works well too. Lyn also has the benefit that she moves so damn fast, that it's really hard to catch any flaws she might have with her movements, which also helps with the resheathing, making it a non-issue. 

Again, most of these are nit picks, but some are major flaws that do need to be worked on. Her major issues are mostly that her poses for some moves are just not dynamic or exaggerated enough. A fundamental principle of animation IS exagerration, so she needs to have that worked on, otherwise she winds up looking awkward and uncanny. Particularly her Smash Charges, the Up B, her Neutral B, and swapping her Utilt and USmash. All those are the major issues that need to be polished. Aside from that, she's great. She's very fluid, and looks and feels great as she moves.

I'm willing to help out by drawing her animations as they should be to help out the animators with all these issues. I'd animate them myself, but for one, idk how to work the software, and two, I don't have a working computer anyway. Regardless, I am an artist, and I can contribute with what I can to give her much better and more fluid movements and poses.

Cheers.

**Comment by Large-Leader** [comment]
Hey ManlySpirit. I have the old concepts for Lyn that you posted up a long time ago on kcmm. I'll be making my personal version of Lyn that follows that direction you wanted to take for Lyn (tbh, I was and still am floored by your art). While pmcc might not take my edits, I'm more than willing to work on my own version (new model, textures, and all). 

If you want to converse further, you can pm me on Kitty corp meow mix, where I'm one of the local moderators for the Attacks and Animations section (I go by Large Leader).

I look forward to hearing more from you.

**Comment by Grangach** [comment]
I think this is within the scope of the project. Lyn wasn't a completed character, even though she already functions extremely well. The PMDT would have taken her to a whole other level of polish and I think it would be okay to follow in that. Some of your suggestions have to do with character balance so those might not be on the table, even though I agree with most of them.

**Comment by bb010g** [comment]
These are perfectly within scope, as Lyn's animations aren't as high quality as everything else. I know someone's working on a Lyn jab series adjustment.

**Comment by ManlySpirit** [comment]
@Large-Leader 
Oh yeah man, all the way. I'd me more than happy to help with things. I actually still have that moveset lying around, however, I'd change a few things in it now, mostly give her more sword moves over the Melee attacks I had given her. 

Fun fact: The Lyn created by the PMDT is heavily inspired by my moveset, as I sent to them as soon as the clone engine was revealed, and told them they were free to use it hoping it would inspire them:

![pic](https://cloud.githubusercontent.com/assets/16632519/12307713/5715231a-ba41-11e5-8459-9baaafbf2b33.jpg)

Turns out it worked since we did get Lyn after all, and a lot of her moves take after my ideas. For example, her Side B and Vantage are both based off the Side B I gave Lyn in my moveset. ;)

> She pushes the ground with her front foot and vanishes appearing a certain distance from her starting location. It has much less range than Fox's Illusion, but it is an effective killing move. She only attacks if she catches an opponent with it, so outside of that, it's an OK recovery move as it can also be used in mid-air. It has landing lag on both occasion, but double if she attacks, and the knockback only happens when she sheathes her sword having a delayed effect, so she DOES leave herself exposed to attack for a bit, but you have to be quick. It does 13% damage if it hits, and opponents are sent flying 

Anyway man, I'll PM you on KCMM this weekend and we can talk things over.

**Comment by somealternateaccount** [comment]
There are a large number of open issues relating to Lyn's animations: #11, #22, #24, #25, #30, #31, #32, #33, #34, #35, #52, #54, #65, #79, #106, #120, #124, #125, #131, #191, #200, #201, #202, #204, #205, and #283. An issue of this size is mostly untenable to work with - it's hard to properly keep track of what is getting done and where, unless a single skilled animator would like to take up this job, so I'm going to rework this into a "Lyn Animation Redo RFC" or something similar, so we can open up for comments about potential animation fixes for Lyn. Your notes will be visible as references in those issues, so people wishing to update Lyn's animations may see your recommendations there.

I would, however, like to remind those reading this that merely discussing issues does not fix them.

**Comment by bb010g** [comment]
Checkboxes are great for this sort of thing. I'm all for merging those into this issue and then tackling extra discussion in pull requests to keep things manageable.

**Comment by TheSmashBoy** [comment]
Commenting to keep tab on this. Request to re-open this issue for Lyn animation discussion. I have made a few changes to her animations and PSA's to align to Manly's proposals as close as possible. Will provide details soon enough.

**Comment by bb010g** [comment]
This has been moved to Project-M-CC/lyn#7, which is open.

**Comment by TheSmashBoy** [comment]
@bb010g Yeah, but we have better reference here and his pictures aren't included in here as well.
