### ISSUE TITLE
Issac: Neutral B bug in Training

### ISSUE THREAD

**Issue by bubbabeck51** [TheOriginalSINe/Project-M-CC#306]
I was in training mode as Issac and was trying out his moves against a computer, but when I changed the computer from stop to attack, Issac's neutral b caused him to teleport around the stage and when I turned the computer back to stop it worked again.

**Comment by ghost** [comment]
@bb010g Another duplicate issue.

**Comment by bb010g** [comment]
Duplicate of #159.
