### ISSUE TITLE
does the "new" knuckles seem like a copy of an older leak?

### ISSUE THREAD

**Issue by Tac24** [TheOriginalSINe/Project-M-CC#307]
check out the taunts for example...I'm sticking with the initial build for now

**Comment by ghost** [comment]
@Tac24 The taunts and win animations(and generally anything miss from) the previous Knuckles were ones that we added in, and will return shortly.

**Comment by Tac24** [comment]
How do we know that this kux is "newer and better" overall? Wasn't the one
we've been working on just as goodñ

**Comment by ghost** [comment]
@Tac24 this version of knuckles had a number of bugs that we were working on fixed, missing animations added, and previous animations improved upon. All heavily implying that this version is newer.

Closing.

**Comment by bb010g** [comment]
It's not a copy of an older leak. See the change list on #288.
