### ISSUE TITLE
Is there a netplay builder for this? 

### ISSUE THREAD

**Issue by SzionBlue** [TheOriginalSINe/Project-M-CC#308]
I tried to netplay build with the 3.6 buildder and i got nothing..

**Comment by Kippy232** [comment]
I really feel like this may be a compatibility issue, of sorts, with the builder and this iteration. It's possible there would simply have to be another builder for this one, like the builders for 3.5 and 3.6.

**Comment by bb010g** [comment]
Not yet. This will probably come after a 1.0 release.
