### ISSUE TITLE
All leaked clones have Mario's Wii Remote sound

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#309]
Title

**Comment by icecapman10** [comment]
I've noticed this, too.

**Comment by pharoahfawcett** [comment]
do roy and mewtwo have their own sounds?

**Comment by ghost** [comment]
@pharoahfawcett Mewtwo has his Pokemon Red/Blue/Yellow cry, while Roy has a generic metal clank sound. I know where Mewtwo's is, but have no idea where Roy's odd one is.

**Comment by MadoKage** [comment]
For Knuckles we should try this sound, Its a unused sound from Sonic 06 which I figured since most of his sounds are from that game

https://tcrf.net/index.php?title=File%3AKnucklesClearS.ogg

**Comment by ithunderHD** [comment]
After all we could use the sounds for knux it sounds like it would go in great and hate the Mario sound on all the character that are not Mario

**Comment by LinkTahuterasuSpirit** [comment]
@Rage17 really? roy should have his down taunt voice clip for wii remote sound
