### ISSUE TITLE
Lyn: F-Smash Return Animation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#31]
The last few frames of Lyn's F-Smash animation (after her hop backwards) are odd and choppy. Makes her look like she is sliding backwards.

Suggested Fix: Looks like this animation was never completed. After the jump, feet should be animated so Lyn looks like she is stepping back into position, not sliding back.

**Comment by PKPenguin321** [comment]
I've looked at this frame-by-frame, she does in fact take a step back, but the problem is that shortly after the hitboxes of her f-smash disappear, her feet both jump back very very quickly and then proceed to step back.

**Comment by ghost** [comment]
Frame 51 to 52 of fsmash. Her planted leg slides back.

**Comment by bb010g** [comment]
Subsumed by #305
