### ISSUE TITLE
Lyn: Thrown animation reaches offscreen

### ISSUE THREAD

**Issue by TheGag96** [TheOriginalSINe/Project-M-CC#310]
Heya, I was playing around just now, and when I up-throw Lyn with Sonic (Smash 3 model, though I don't think this matters), the off-screen indicator will come up for a split second as she's being thrown.

[Gfycat](http://gfycat.com/BlankOrnateBoutu)

I'm not sure if this is know, but I figured it's worth documenting.

**Comment by Kippy232** [comment]
Try to replicate this without any models that aren't part of this project. Otherwise, as far as we know, the issue may very well be the addons that you're using.

That aside, are you using a Wii, Wii U, or Dolphin? Wifi Set, or Full Set? Dev Rources? Etc, etc.

**Comment by TheGag96** [comment]
Yep, still happens with regular models. Done on Dolphin (that's how I recorded the footage in such high quality), full set, more or less a straight clone of mater from the commit "Merge pull request #293 from PyotrLuzhin/master" 3 days ago.

**Comment by bb010g** [comment]
Can confirm. Doesn't happen with every throw, but more than just Sonic uthrow cause it. Just vanilla CC.
