### ISSUE TITLE
Melee's Battlefield has no sound.

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#311]
title

**Comment by cimpyhigh** [comment]
Put an empty .gct with this code on it:
http://smashboards.com/threads/brawl-freezes-when-going-to-battlefield-in-my-music.356375/
Should work now.

**Comment by icecapman10** [comment]
It's when I play on it. The music is gone.

**Comment by cimpyhigh** [comment]
Yeah, it does that too. Just take my advice, it will fix it

**Comment by icecapman10** [comment]
What do I name it?

**Comment by cimpyhigh** [comment]
I'll make a file for you tomorrow and you can just throw it on your SD card. Your on Wii right?

**Comment by cimpyhigh** [comment]
Put this one on your SD card:
https://www.mediafire.com/?3jgk0jc0ts2m474
NOTE: Will load Vbrawl. Play one match and it should work.

**Comment by bb010g** [comment]
@cimpyhigh So this was just a corrupted save file, not a CC problem?

**Comment by cimpyhigh** [comment]
@bb010g I'm pretty sure, but no 100% confirmation until @icecapman10 tells us if it works

**Comment by bb010g** [comment]
Closing for now at least. We can reopen if he still has an issue.

**Comment by cimpyhigh** [comment]
@bb010g I don't have the problem, so I think it's just a corrupted file. Happened to me a while back.

**Comment by icecapman10** [comment]
It worked

**Comment by cimpyhigh** [comment]
A bit late, but thanks anyway.
