### ISSUE TITLE
Lyn's Super Jump

### ISSUE THREAD

**Issue by mhps-m** [TheOriginalSINe/Project-M-CC#312]
With Turbo Mode On, if you hit your opponent while using Up-B and use F-Air at the right time, Lyn will go VERY high in the air, going off-screen.

**Comment by ghost** [comment]
This sounds similar to Ike's momentum glitch in turbo mode. The momentum from up b is kept if you cancel it properly.

**Comment by mhps-m** [comment]
Didn't know about Ike's glitch until now. Maybe these glitches are related some way?

**Comment by ghost** [comment]
Yeah the momentum carries over the same I guess. It isn't really a glitch though, its just that you're cancelling the move before it stops your momentum.

**Comment by mhps-m** [comment]
oh
