### ISSUE TITLE
Giga-spider-demon bowser freakout

### ISSUE THREAD

**Issue by lazzeretto** [TheOriginalSINe/Project-M-CC#313]
Using the full codeset and a softmodded wii. I downloaded the CC version that was available on new years eve. I selected retro mode with giga bowser on green hill zone (I dont know if that is important) and he was so messed up. his mouth and face were disconnected. He had floating hands like ray-man and floating feet and a weird messed up shell and legs and arms and everything. Everything was disconnected and out of place. He couldnt really move without telepoting backwards. He looked and moved in a very glitched out way. I am assuming that this is a rigging problem but he is incredibly broken in retro mode all together.

**Comment by ManlySpirit** [comment]
I think Retro Mode is still incomplete. I remember trying it with Ike, and he was invisible because he has no model. So I'm certain Bowser is a similar issue.

Anyway, pics? I wanna see it.

**Comment by icecapman10** [comment]
I've played around with N64 mode and saw that, too. I find it funny.

**Comment by lazzeretto** [comment]
@ManlySpirit Yes, I noticed. I will add a picture tomorrow
@icecapman10  It is really funny, but that night it was terrifying.

**Comment by lazzeretto** [comment]
[giga-glitch.zip](https://github.com/TheOriginalSINe/Project-M-CC/files/91314/giga-glitch.zip)
These are the pictures in the zip. There are 3 pictures of different angles. Sorry about the semi-low quality. I had to take the pictures with my phone because I couldn't convert bin files on my Chromebook..

**Comment by somealternateaccount** [comment]
Closing for now - this is part of N64 mode, which will likely fix this bug on its own path to completion.

**Comment by bb010g** [comment]
I think it is fixed in the current working set of models.
