### ISSUE TITLE
Samus' weapon change taunt takes much longer.

### ISSUE THREAD

**Issue by jweezy64** [TheOriginalSINe/Project-M-CC#314]
Was this intentional?

**Comment by bb010g** [comment]
Yes. This is in 3.61.

**Comment by jweezy64** [comment]
You sure? I had been playing an earlier community build of 3.61 and it
wasn't that slow.

**Comment by jweezy64** [comment]
Also, that change wasn't listed in the 3.61 changelist.

**Comment by bb010g** [comment]
It wasn't in the changelist, but PMDT has forgot to do things in the changelist before. It's what's in Halloween, and the 3.61 Stable build, so it's pretty much 3.61. It's better for continuity to just keep it that way. Could you link the build you were playing?

**Comment by Grangach** [comment]
I thought 3.61 wasn't a balance build?

**Comment by bb010g** [comment]
It's in there. It looks like they meant to put in a code with it too to fix the speed, so this may be a bug we could fix.

**Comment by Grangach** [comment]
I think that would probably be smart.
