### ISSUE TITLE
How do I open Retro Mode?

### ISSUE THREAD

**Issue by mamimamis** [TheOriginalSINe/Project-M-CC#317]
Title.

**Comment by ghost** [comment]
It's in special brawl where invisible mode used to be.

This is not what issues are for, ask this sort of thing in the "help" section of Discord next time.

Closing.

**Comment by PhoxFyre** [comment]
download [this](https://github.com/kalebsanders007/Project-M-CC) and go to special brawl

**Comment by bb010g** [comment]
@kalebsanders007 How long until that's ready to PR?

**Comment by bb010g** [comment]
How long until you can provide a sane, testable PR with those changes (whatever they are)?

**Comment by PhoxFyre** [comment]
i dunno
plus i have no clue how to rebase

and its just the beta. purpa, pyotr, and others are working on the full thing.

**Comment by PhoxFyre** [comment]
plus this is pretty much my semi-custom build
