### ISSUE TITLE
Sami Up-B Forever

### ISSUE THREAD

**Issue by Hex97** [TheOriginalSINe/Project-M-CC#318]
First issue I found, so I thought I'd mention it. I was playing against a Sami AI, knocked her off stage and naturally it Up-B'd up, up, up and right off stage. Past the blast zone and did not stop. This continued for about 3 min. or so until I reset the match.

**Comment by darkralts** [comment]
wut... that sounds crazy. so its like infinite up b? sami sounds op now.. hopefully someone smart with codes unlike me can fix this

**Comment by DestinyHiro** [comment]
I brought this up two weeks prior it has to do with the wind box on it, which will be taken care of later.

**Comment by darkralts** [comment]
:D
