### ISSUE TITLE
"Success" is "Issac" instead and more

### ISSUE THREAD

**Issue by VideoGameHero95** [TheOriginalSINe/Project-M-CC#320]
So I was messing around with Multi-Man Smash when I came across a few issues. For one, there was a large white streak on the screen, and if you kill all the Alloys and a clone of your character is still there, the line disappears. I don't know what the issue is but I'm sure you can fix it.

Second issue is when you complete Multi-man Smash or an Event etc, usually the announcer would say success. In this case however, "Success" is replaced with "Issac". Basic problem but I was just pointing it out.

All the issues so far are shown off here: https://youtu.be/9uZRvnRwcj0

Another issue I wanted to mention is that if you win as Giga Bowser in a normal match, "Sami" will be shown as his name. That's seen in this image: http://imgur.com/lRKd6mU

I am a huge fan of this project so far and I would like to see it grow.

**Comment by PowerpointSmasher** [comment]
This can't really be fixed because Isaac's announcer has to replace something.

**Comment by VideoGameHero95** [comment]
I see. Sucks a bit but whatever I guess.

**Comment by bb010g** [comment]
We can always try to find a better clip to overwrite.

**Comment by TheGag96** [comment]
What did Mewtwo and Roy's calls replace?

**Comment by VideoGameHero95** [comment]
Since the PMDT had full control over everything, they probably added the clips no problem. The problem here is that we aren't the PMDT. We can't add in anything, just replace and include what may have been hidden. Maybe at least. Honestly not sure.

**Comment by Nekudot** [comment]
In previous versions, Mewtwo replaced Fighthing Alloy Team. I don't know if that's still true for the dev build or not.
Tourney mode is inaccessible atm, so that could be used. But yeah, until an alternate soundbank code is created, something else has to be replaced

**Comment by cimpyhigh** [comment]
I agree, let's replace tourney mode. That would be easiest, considering tourney will most likely never be playable again, unless some awesome coding takes place.

**Comment by PKPenguin321** [comment]
> Since the PMDT had full control over everything, they probably added the clips no problem. The problem here is that we aren't the PMDT

This is an absolutely silly line of thought. The PMDT were not wizards that could just do whatever they wanted to. The only thing that separates you or me or anybody from them is experience with the project.

**Comment by LinkTahuterasuSpirit** [comment]
@TheGag96 i don't know about mewtwo but Roy replaces pokemon trainer

**Comment by cimpyhigh** [comment]
Mewtwo replaces the alloys.

**Comment by LinkTahuterasuSpirit** [comment]
@cimpyhigh mewtwos announcer call replaced the alloys?

**Comment by cimpyhigh** [comment]
Yeah, or at least in older versions.
