### ISSUE TITLE
Classic Mode Freeze + Cosmetic Extras

### ISSUE THREAD

**Issue by GunBlazer** [TheOriginalSINe/Project-M-CC#321]
Attempting to hover over Isaac and Sami's icons on the CSS in Classic Mode freezes the game.

Also, Isaac and Sami use Bowser's logo during All-Star and Stadium Modes.

**Comment by ithunderHD** [comment]
We could fix this by looking in the codeset

**Comment by ithunderHD** [comment]
I'll check using brawlbox

**Comment by ithunderHD** [comment]
I'll check what's going on

**Comment by ghost** [comment]
@PyotrLuzhin is working on this(also tagged as a reminder of sorts).
