### ISSUE TITLE
Isaac Glitch

### ISSUE THREAD

**Issue by PowerpointSmasher** [TheOriginalSINe/Project-M-CC#322]
So I was playing with Isaac and this happened:
![photo](https://cloud.githubusercontent.com/assets/16510463/12527770/064ab01a-c150-11e5-9e59-af0745b8e6e0.JPG)
I don't even know how I did it. And it happened multiple times before.

**Comment by phurgawtin** [comment]
That's happened to me a few times. I find it most often happens with Neutral B or Fsmash, and if I had to guess, I wouldn't be surprised if it only happens on certain stages.

You get stuck in the front of the camera, and even airdodging won't kill you. L+R+A+Start ftw.

**Comment by DestinyHiro** [comment]
This was covered long ago, we do have a fix but we haven't set it up yet since Isaac himself isn't presentable yet.

**Comment by ghost** [comment]
@bb010g This issue should be closed (it's a dupe of at least one other issue).

**Comment by bb010g** [comment]
@Rage17 Could you link it? I couldn't find one.

**Comment by ghost** [comment]
@bb010g I found them, issues #19 and #159 .
