### ISSUE TITLE
about stages for new characters

### ISSUE THREAD

**Issue by ithunderHD** [TheOriginalSINe/Project-M-CC#326]
I was thinking that we could get sky sanctuary,Venus lighthouse for Knuckles and Isaac I found a really cool sky sanctuary zone stage that goes over frigate orpheon. So I was thinking we could put that stage and for Venus light house we use the stage expansion tool for that. Extra we could put peach's castle melee from  3.5 as a hidden alternate stage for bowser castle.

Links
Sky sanctuary zone:https://m.youtube.com/results?q=sky%20sanctuary%20zone%20%20v2%20ssbb%20stage&sm=3

Stage expansion tool:http://forums.kc-mm.com/Gallery/BrawlView.php?Number=23654
Venus light House:http://forums.kc-mm.com/Gallery/BrawlView.php?ByUserID=32098

**Comment by bb010g** [comment]
This should go in #57 when it's not tabled anymore.
