### ISSUE TITLE
[RFC] Switch to Brawlex+PM?

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#327]
- Allows for end users to add extra characters
- Not necessary for our scope
- Potential stability issues

Personally I think it would be worth it, although if the stability issues are too bad I can understand not doing it. This would NOT be so that we can add more than the forbidden 4, just to make it easier for the end user to add their own content.

**Comment by DestinyHiro** [comment]
While a good idea; I think we should have a set up version of the forbidden 4 for Bex+PM instead that way it's seen as an add on rather an entire build.

**Comment by LnktheWolf** [comment]
Agreed with @destintyhiro . It should be a separate download from the main build, especially because as far as I know there are some issues currently still that need fixed

**Comment by bb010g** [comment]
I think @PyotrLuzhin has fixed most of the issues with BrawlEx, but we'd probably still want to run a testing build alongside the PM clone engine main build for a while.

**Comment by cimpyhigh** [comment]
@DestinyHiro I agree with you. That makes the most sense to me.

**Comment by KymaeraK1ng** [comment]
Seems reasonable.

**Comment by GamingMaster777** [comment]
if it uses brawlex then it could its own soundbank instead of using the bosses's sounds

**Comment by bb010g** [comment]
Subsumed by #384.

**Comment by bb010g** [comment]
Subsumed by #398.
