### ISSUE TITLE
Isaac and Sami's voices

### ISSUE THREAD

**Issue by RikiDVX** [TheOriginalSINe/Project-M-CC#328]
Isaac and Sami need their soundbanks set up with new voices.

**Comment by ithunderHD** [comment]
Well
we could get sound banks from other PSAs of isaac
For sami get a generic female voice of snake
We could rina Chan to do one for sami
http://forums.kc-mm.com/Gallery/BrawlView.php?ByUserID=11571

**Comment by ithunderHD** [comment]
we could get sound banks from other PSAs of isaac

**Comment by ithunderHD** [comment]
For sami get a generic female voice of snake

**Comment by ithunderHD** [comment]
We could rina Chan to do one for sami

**Comment by ithunderHD** [comment]
http://forums.kc-mm.com/Gallery/BrawlView.php?ByUserID=11571

**Comment by DestinyHiro** [comment]
Well the Temporary Voice of Sami, Lauren Bailey (Saints Row with bits of Chun-Li), is nearly set in place, I just need the list of grunts locations to set it up, which Purpa/Rage needs to give me. As for Isaac I've got Kitsu's voice set on my personal build, but I'm planning on using Riki's submission of for VA.

**Comment by bb010g** [comment]
(@ithunderHD Please keep from double posting in a short period of time. You can just edit your first post of the batch, or wait a bit longer before submitting.)

**Comment by cimpyhigh** [comment]
Is there a place to hear Riki's submission? I might work on trying to add those sfx in, if I can find the time.
