### ISSUE TITLE
Isaac is in Random

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#333]
I think this qualifies as cruel and unusual punishment. I haven't seen Sami show up, but I wouldn't be surprised.

cc/ @PyotrLuzhin

**Comment by Kippy232** [comment]
Worth noting is that Isaac seems to be bugged. Gameplay with him at all for any longer than, I think, two minutes or so, causes to screen to glitch out, as shown in issue https://github.com/Project-M-CC/Project-M-CC/issues/322

**Comment by ghost** [comment]
@Kippy232 It only seems to be caused by his forward smash and neutral special, rather than a time based thing.

**Comment by LnktheWolf** [comment]
I haven't seen Sami, so I don't think she's in, but I've seen Isaac multiple times. So I don't think we really have to worry about Sami being in currently.

**Comment by robosteven** [comment]
Isaac causes weird grab bugs too. Like, teleporting himself and whoever he's grabbing all over the place weird.

This might be from an outdated build though.

**Comment by darkralts** [comment]
i think its because isaac is actually in the roster while sami is not.
