### ISSUE TITLE
(Probably out of Projects Goals) Tourney Mode

### ISSUE THREAD

**Issue by PowerpointSmasher** [TheOriginalSINe/Project-M-CC#336]
Is it possible to fix Tourney Mode? Because when I select it, it goes to Rotation. I know the PMDT had trouble with this, but was wondering if it can get fixed?

**Comment by RikiDVX** [comment]
If I remember correctly, they intentionally rerouted to Rotation because lots of characters would crash in Tourney mode.

Found this: https://www.reddit.com/r/SSBPM/comments/3hed10/tournament_mode_in_36/

**Comment by ithunderHD** [comment]
This should get closed because tourney mode is never going to be playable

**Comment by bb010g** [comment]
Never is a strong word. The PMDT probably didn't sink much time into it because it's not that good of a feature. You'd want a double elim w/ clone & separated characters, and even then it's inconvenient for an actual tourney because you can't change anything.

**Comment by RikiDVX** [comment]
I think this should be closed. It's not really on the table for this project.

**Comment by Kippy232** [comment]
This seems like a side project in and of itself. Fixing Tournament Mode would take time and resources that shouldn't be expended yet, if at all within the scope of PMCC. In any case, this should be closed, I think.

**Comment by ithunderHD** [comment]
Or we could replace tourney mode with new crazy mode it seems that PMDT where going to do that  anyway but probably didn't  get around to it.

**Comment by Kippy232** [comment]
@ithunderHD without evidence of such a mode, that, too, seems out of this project's goals.
