### ISSUE TITLE
Isaac's Shadow in Flatzone 2

### ISSUE THREAD

**Issue by PowerpointSmasher** [TheOriginalSINe/Project-M-CC#339]
![image](https://cloud.githubusercontent.com/assets/16510463/12863126/63a876f2-cc40-11e5-8df2-fa4464bc69c8.jpg)
Isaac's shadow is off.

**Comment by RikiDVX** [comment]
His shadow is pretty bad on all stages too.

**Comment by ghost** [comment]
Noting, for anyone who hasn't noticed yet, Isaac currently reuses Ike's shadow models. This includes the separate sword shadow shown above.
