### ISSUE TITLE
Alternate costumes should have team colors

### ISSUE THREAD

**Issue by RikiDVX** [TheOriginalSINe/Project-M-CC#341]
The PMDT had begun to implement team colors for every alt. There are a few alts left who do not have team colors. (Jet Set Sonic, Armor Zard, Big Boss, etc) Would implementing those team colors be possible? I don't think it's outside of the scope of this project, but what do you guys think?

**Comment by ghost** [comment]
@RikiDVX I'll close this now, since alternate team colors have already been confirmed as a plan of ours(which has a bit of work started on it already).
