### ISSUE TITLE
SFX ISAAC again

### ISSUE THREAD

**Issue by Fandesupersmash** [TheOriginalSINe/Project-M-CC#342]
but sfx folder should leave a file as an example " 232 " containing those sounds D:

**Comment by PowerpointSmasher** [comment]
Ask this on the Discord instead of an issue

**Comment by Fandesupersmash** [comment]
How do I do that ?
I'm new xD

**Comment by PowerpointSmasher** [comment]
Go to readme and click on chatdiscord

**Comment by Fandesupersmash** [comment]
where?

**Comment by PowerpointSmasher** [comment]
First page.

**Comment by Fandesupersmash** [comment]
I do not Dx

**Comment by Fandesupersmash** [comment]
excuse my stupidity xD

**Comment by PowerpointSmasher** [comment]
![image](https://cloud.githubusercontent.com/assets/16510463/12870772/134855d2-cd22-11e5-815f-15400c4e764c.jpg)
Hope this clears thing up

**Comment by Fandesupersmash** [comment]
and after that I do?

**Comment by PowerpointSmasher** [comment]
Click on chatdiscord than accept invite

**Comment by Fandesupersmash** [comment]
D:?

**Comment by Fandesupersmash** [comment]
it succeeds : D

**Comment by RikiDVX** [comment]
This question was resolved by LnktheWolf in the discord chat. Closing.
