### ISSUE TITLE
Lyn: Various Issues

### ISSUE THREAD

**Issue by KymaeraK1ng** [TheOriginalSINe/Project-M-CC#345]
-Some of her sounds come out a frame early. Really minor.
--Grab
--FTilt
--Uptilt 2 (1 frame late)
--BAir
--Dash attack (3 frames early)
--FSpecial (5 frames before I frames)
--DSpecial (4 Frames before detection bubble)
--USpecial (1 frame before larger smoke effect)
-DSmash doesn't hit opponents on the ledge (add a hitbox to the tip of her sword)
--Her charging animation looks awful and has no movement at all

**Comment by ghost** [comment]
These belong in individual entries. Look through the existing issues. If something isn't covered yet(by a specific issue, or a general one like the animation issues), then create a new one, not before.

**Comment by KymaeraK1ng** [comment]
The reason for this is because a lot of the issues that have been brought up in the past are not exactly specific. I figured that compiling specifics would make them easier to fix. If this is the case, please reopen the thread(I can't use this website at all).

**Comment by bb010g** [comment]
I don't think the sound problems have their own issue, and the jab series is being worked on right now. The fsmash invisibility is intentional. Animations are covered in #305.

**Comment by KymaeraK1ng** [comment]
Ok. Is that better?

**Comment by bb010g** [comment]
Just make a new issue for the sound issues.

**Comment by DestinyHiro** [comment]
I'll mark these down for with the Lyn changes I'm working on.
