### ISSUE TITLE
New Sounds for Knuckles

### ISSUE THREAD

**Issue by MadoKage** [TheOriginalSINe/Project-M-CC#347]
I'm pretty new here

I know this isn't a issue but, I 'm sharing my variety of sounds from most of the games that has Knuckles

http://www.mediafire.com/download/gj2f090blbl95cf/Sounds.zip

There is more I'm gonna share

**Comment by MadoKage** [comment]
A bit more sounds

http://www.mediafire.com/download/zu988540loisqv5/Sound_2.zip

**Comment by ghost** [comment]
With the new PR, Knuckles got his SFX issues fixed mostly, and has no more room for additional sounds. Closing this for now.

**Comment by bb010g** [comment]
@Rage17 What sound fixes are left? Mostly fixed is still not fixed.

**Comment by ghost** [comment]
@bb010g , his star KO sound atm reuses another clip(as Knuckles currently has no room for more), and @vinegar97 is putting together a PR that has fixes for a looping issue on the down taunt clip(which is reused for a win clip for the space reason). Going forward, we plan to make a shared Sonic/Knuckles soundbank for him to have more room for sounds.
