### ISSUE TITLE
New Stock Icons for Knuckles

### ISSUE THREAD

**Issue by MadoKage** [TheOriginalSINe/Project-M-CC#348]
I'm making new Stock Icons for knuckles although the costumes in #296 are not done yet

When they get done I'll post the rest

Here is a preview of it
http://i.imgur.com/lehsYCq.png (Original Size)
http://i.imgur.com/SfikIQW.png (Enlarged)

**Comment by MadoKage** [comment]
I might as well post them

Stocks are done and redid them a little to have less washed out colors

sc_selcharacter only shows 6 icons while the costumes shows 9 so I name them as a guess to where they might go

http://www.mediafire.com/download/whz243kw1fzma2r/Stocks.zip

**Comment by Kippy232** [comment]
These look good. Now, we just need someone to make a pull request for these to get them shipped alongside the extra costumes and portraits.

**Comment by vinegar97** [comment]
![stockred](https://cloud.githubusercontent.com/assets/16244042/12970366/f9ac353c-d09e-11e5-887d-95bfd72e63b4.png)![stocktribe](https://cloud.githubusercontent.com/assets/16244042/12970363/f952d41a-d09e-11e5-90c8-472c0d987d86.png)![stockgreen](https://cloud.githubusercontent.com/assets/16244042/12970365/f9a8ba92-d09e-11e5-9c18-76b218e54abb.png)![stockblue](https://cloud.githubusercontent.com/assets/16244042/12970364/f9a1e8f2-d09e-11e5-8595-c4f4b3cb9783.png)
we already have stock icons made, though, they just need to be commited.
i'll be making a PR to fix various issues for knuckles, so i'd like to know which ones people prefer we use.
JSYK, the current ones are edited from sonic advance, so they don't really mesh well with the rest for the icons.

**Comment by ithunderHD** [comment]
Wow those nice but who going to make the pull request. vingar 97 I like urs better, personal I don't like sonic advanced stock icons

**Comment by MadoKage** [comment]
Definitely better then mine IMO, I was wondering if those costumes will have their own stock icons so I made mine temporary until some proper ones come by.

also good work on fixing the costumes and the stock icons

**Comment by Kippy232** [comment]
So it's settled, then? Since @vinegar97's stock icons are more fitting, we'll use those?

My only question is when those varying Knuckles fixes will me shipped.

**Comment by vinegar97** [comment]
i guess we'll use my edited stocks then, sorry to burst your bubble, @MadoKage.
@Kippy232 soon.

**Comment by LnktheWolf** [comment]
I agree with using Vin's stocks on the fact that they fit better among the others as well as they look really good anyway. You gonna PR them when you PR the costume slot expansion @vinegar97 ?

**Comment by vinegar97** [comment]
yes, that's the plan

**Comment by MadoKage** [comment]
@vinegar97 its all good

Now we wait for the PR

**Comment by ghost** [comment]
The PR got made (with stocks included), so i'm closing this.

**Comment by vinegar97** [comment]
for future reference, the fix is in #351
