### ISSUE TITLE
the build without sami

### ISSUE THREAD

**Issue by zero1998** [TheOriginalSINe/Project-M-CC#349]
how can you remove her form the ccs

**Comment by bb010g** [comment]
You'd have to adjust the CSS codes to something like they were before. This build will not be removing her or making a version without just her on the CSS, however, because she is a WIP and is being tested actively. Also, removing her messes with the CSS layout, and that's annoying to remake well.

**Comment by PowerpointSmasher** [comment]
This is not what issues are for. Issues are for problems/bugs in the main build. If you have questions ask it on the Discord.
