### ISSUE TITLE
Knuckle's victory animation has looping SFX

### ISSUE THREAD

**Issue by Yohan1044** [TheOriginalSINe/Project-M-CC#352]
Hold "X" after winning with Knuckles to trigger the desired victory pose.Listen to him recite his down taunt SFX in an endless loop.

Also, Grabbing Knuckles doesn't stop the sfx of his taunts. His side and up taunts will finish their sfx
If you grab Knuckles during his down taunt, his sfx enters a loop that doesn't stop til he's thrown.

**Comment by ghost** [comment]
Yohan knows this from the talks on Discord already, but to anyone else who reads this, a PR with a fix for this and other issues is being compiled at the moment.
