### ISSUE TITLE
Lyn's expressions need to be edited further

### ISSUE THREAD

**Issue by DestinyHiro** [TheOriginalSINe/Project-M-CC#353]
Lyn's expressions need to be edited more so she would fit better with the cast; such as blinking on her wait stances and more aggressive facial expressions with some mouth movement when hitting. (I'll edit this comment later but I plan to make a checklist on all of her animations, and I will start editing a few of the animations with said expressions when ever I get the chance)

**Comment by vinegar97** [comment]
Quick update, taken from discord:

https://images-2.discordapp.net/.eJwVxlEOgyAMANC7cAAqKB16Bu-wEGxQo5bQ-mGW3X3Z-3ofc7fDTGZVrTIBLJtkbosV5ZYK2cJcDkp1E5v5hKSa8nrSpQLO996PfvDoQtcFFxH-wQExjK8YsUcXYX6ud25E9bF7Leb7A23vI94.3e9WD6GLjbUvxV0_kI5nEd9bM2M.jpg?format=webp&width=640&height=480

This happens on the end of her up throw.
True terror.

**Comment by ghost** [comment]
Noting that Lyn's expressions are improperly fitted to her head.
