### ISSUE TITLE
Knuckles TurnRunBrake lacks a proper turn in the animation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#357]
Title. All other TurnRunBrakes have a proper turn in them after the "skid" portion, so that they properly link back into the run animation.

**Comment by bb010g** [comment]
Is this fixed in the upcoming PR?

**Comment by ghost** [comment]
AFAIK it might've been fixed in the second leak actually. The iin transition from run exists on the GitHub now at least.
