### ISSUE TITLE
Revert to 3.6 CSPs

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#359]
This can't be done for clones, but it can be done for everyone else.

As for replacements, @davidvkimball has offered the use of the Legacy CSPs when they're done, and Nanobuds is planning to release his new set at some point.

**Comment by KymaeraK1ng** [comment]
... Why? The new ones look great.

**Comment by vinegar97** [comment]
they were made by nanobuds, so they'll be removed per his request.

**Comment by cimpyhigh** [comment]
So does that mean that Nano's CSPs won't be included in the final build?

**Comment by vinegar97** [comment]
most likely.

**Comment by bb010g** [comment]
Also, they're just not finished yet.

**Comment by LnktheWolf** [comment]
They also clash with the ones that are still 3.6, so they should be put back to 3.6 so they match in style, and then when we get all new CSPs that we replace those for every character including the forbidden four.

**Comment by davidvkimball** [comment]
I know I'm not part of a team anymore, but honestly the reasoning for not using them should only be that they're **unfinished**. You can't use "nanobuds requested removal" as a basis for a decision to keep them out of the build, since the entire PMDT has requested that this project no occur in the first place.

**Comment by Tac24** [comment]
use something like this https://www.youtube.com/watch?v=VYSJEqVT1Ig&feature=youtu.be

SJS always had some killer ones... loved his old lucario/MK... use SJS's for characters that are missing the CSPS

be sure to update battle portrait too!

**Comment by KymaeraK1ng** [comment]
Those fit in pretty well tbh. There's pretty much no reason not to...

**Comment by LnktheWolf** [comment]
Part of the goals is to use what we have, and if we need to make stuff of our own, then we should or get permission of pulling from the vault. 

Thank you @davidvkimball for reiterating what i said in a different way. Currently the nanobuds csps that are included in the leaks are not complete. Therefore we need to find a suitable replacement, which we're likely only to get if weveryone make our own, complete package to make sure they all match in style.

SJS's csps, while good quality, as I remember them, don't really have the same style as the ones included in the leaks, therefore we shouldn't use them to fill in gaps, especially when we'd have to make our own knuckles, lyn, isaac, and sami anyway. If we can get permission from SJS, then we can use them, though we'd still have the situation of having to make the knuckles, lyn, isaac, and sami csps ourselves. Plus, we also have people wanting to make csps, so let them try it out.

And if we can make great csps ourselves and the style matches and everything, then why not? The pmdt didn't strive for and provide "good enough," so we should also strive for excellence.

**Comment by Kippy232** [comment]
@LnktheWolf That was honestly poetic, in a sense. Agreed.

**Comment by KymaeraK1ng** [comment]
As long as we have PM unique CSPs and BPs, fine by me.
