### ISSUE TITLE
Lyn: Up B Ledge Grab Box

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#36]
After performing her Up B, Lyn's Ledge Grab Box does not appear until 11 frames after her downward momentum begins. This makes it impossible to sweetspot the ledge and is not consistent with the rest of the cast (most character's ledge grab box appears on or before the first frame they begin to experience downward momentum).

Additionally, he ledge grab box size is not consistent throughout the endlag of the move.

Suggested Fix: Make Lyn's Ledge Grab Box active 14 frames earlier (her hang time after Up B and before falling). Make the ledge grab box large for the first 5 frames (so that it extends behind Lyn and allows her to grab the ledge behind her if she sweetspots it) and regular sized after that.

**Comment by ghost** [comment]
For anyone working on this: After further testing and using characters like Marth as a reference, I suggest exactly 14 frames earlier for consistency with cast.

**Comment by somealternateaccount** [comment]
Lyn's up-b and side-b should be tested to ensure that her ledgegrab boxes come out on the first frame she falls during her up-b and side-b, and not before. Following that, this issue may be closed.

**Comment by ghost** [comment]
I haven't tested recently but when I made the changes I believe it may have come out during the hangtime of the move, but she would only grab ledge as she began falling.

I think the other FE recoveries work in a similar fashion. Will test soon and follow up.

**Comment by ghost** [comment]
Tested. Grab box comes out during hang time but characters cannot grab ledge unless they have downward momentum. Works as intended, closing.
