### ISSUE TITLE
Sami Crash

### ISSUE THREAD

**Issue by PowerpointSmasher** [TheOriginalSINe/Project-M-CC#360]
On the main CSS, whenever I go over Knuckles and then Sami it crashes.

**Comment by MadoKage** [comment]
If your talking about it crashing in Classic Mode its already a issue in #304

**Comment by PowerpointSmasher** [comment]
No I'm talking about regular Smash

**Comment by DestinyHiro** [comment]
Could someone else confirm this issue? And try to do the same thing with Lyn just incase.

**Comment by GunBlazer** [comment]
Played with all 4 newcomers last night. Doesn't happen to me.

**Comment by Yohan1044** [comment]
Not an issue for me, Dolphin w/ Gecko or Wii Hackless.

**Comment by MadoKage** [comment]
Only crashed on Classic Mode

**Comment by PowerpointSmasher** [comment]
I fixed this issue. Turns out it was the custom Isaac csps that I had. Closing.
