### ISSUE TITLE
Add released ZSS redesign

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#361]
http://forums.kc-mm.com/Gallery/BrawlView.php?Number=210947

**Comment by ithunderHD** [comment]
These would look  really good in v1.0 ,who going to make the pull request

**Comment by vinegar97** [comment]
Nanobuds requested not to use it, we should respect his wishes

**Comment by bb010g** [comment]
Nanobuds doesn't approve of the existence of this entire project and its goals. We're based on 3.61 leak content. The costumes were released for public uses and builds, and we are a build at the end of the day. I'm fine with not using the incomplete version of his CSPs that he's planning to release publicly, but this is a different matter.

**Comment by cimpyhigh** [comment]
The PMDT requested for their content not to be used... Just saying, if we wanted to respect everyone's wishes, this project wouldn't even exist.
