### ISSUE TITLE
Knuckles and Lyn Ledge boxes are weird and need to be fixed

### ISSUE THREAD

**Issue by SiLLyDJ** [TheOriginalSINe/Project-M-CC#362]
http://puu.sh/ndaYQ/958e9752fc.mp4

**Comment by SiLLyDJ** [comment]
Why Sami Label??

**Comment by Kippy232** [comment]
Could you show Lyn's ledge boxes as well? I'm not too great with ledge grab boxes, but I'm sure the extra information could help someone who is.

**Comment by SiLLyDJ** [comment]
http://puu.sh/nlvun/8a4cc0dc14.mp4
