### ISSUE TITLE
Fix ZSS redesign

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#364]
After discussion on the Discord, we've decided due to the community creation status of the new ZSS redesign that we'll just fix up the leak model. According to @Rage17, all we need is a "lag fix and a mat revamp for the AO map to work better".

**Comment by GunBlazer** [comment]
So the one that was released will not be used? Does this also apply to Headband Jigglypuff?

**Comment by bb010g** [comment]
Released headband Jigglypuff is identical to the leak.
