### ISSUE TITLE
Kirby and roy

### ISSUE THREAD

**Issue by EdinmavarThe3rd** [TheOriginalSINe/Project-M-CC#367]
If Kirby and Roy are in the same match and Kirby absorbs Roy the Kirby uses neutral B (Flare Blade) the game will crash

**Comment by chickangamer** [comment]
Do you have any videos of it

**Comment by EdinmavarThe3rd** [comment]
No I don't I guess i could make a quick video of it if it would help

**Comment by EdinmavarThe3rd** [comment]
I can't get it to work sorry...

**Comment by EdinmavarThe3rd** [comment]
I mean my recording software
