### ISSUE TITLE
Kirby's Roy hat ability

### ISSUE THREAD

**Issue by EdinmavarThe3rd** [TheOriginalSINe/Project-M-CC#368]
If Kirby and Roy are in the same match and Kirby absorbs Roy the Kirby uses neutral B (Flare Blade) the game will crash

**Comment by LnktheWolf** [comment]
Does this happen for mewtwo too? Are you sure you're using the correct codeset and fighter .pac's?

**Comment by EdinmavarThe3rd** [comment]
If Kirby and mewtwo are in the same fight the game will crash witch is an issue already I'm using the correct everything so it's a bug that will have to be fixed

**Comment by ishmael205** [comment]
Checked for myself. I get error messages in Dolphin when using it, but it resumes after closing the error balloon.
However, it does come up every time the copy ability is used.

**Comment by bb010g** [comment]
What are the error messages?
