### ISSUE TITLE
Knuckles loses his grab range when he jump cancel grabs

### ISSUE THREAD

**Issue by SiLLyDJ** [TheOriginalSINe/Project-M-CC#369]
http://puu.sh/nekcO/7a482d0eef.jpg

How it looks normally: http://puu.sh/neklP/b0f6086203.jpg

**Comment by bb010g** [comment]
Is the second one his dash grab? What does his standing grab look like? JC grab is just a standing grab.

**Comment by SiLLyDJ** [comment]
nope they're bothe standing grab, it just screws up when you try to jump cancel it

**Comment by ghost** [comment]
@SiLLyDJ does it actually grab properly despite those? Debug mode does show some things improperly.

**Comment by SiLLyDJ** [comment]
@Rage17 Nope.
