### ISSUE TITLE
Lyn: Side-B Ledge Grab Box

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#37]
After performing aerial Side B, Lyn's Ledge Grab Box does not appear until 5 frames after downward momentum begins. Causes strange ledge interactions and is not consistent with the cast (other characters that have a Side B recovery move, such as Wario and Ike, have their Ledge Grab Box appear on or before the first frame of downward momentum).

Suggested Fix: Make Lyn's Ledge Grab Box active either 5 or 6 frames earlier (hang time before downward momentum)

**Comment by thesmashking25** [comment]
Thedudemonn on YouTube has an updated Lyn psa

**Comment by ghost** [comment]
For anyone working on this: After further testing, I suggest exactly 8 frames earlier for consistency with cast.

**Comment by somealternateaccount** [comment]
See #36.

**Comment by bb010g** [comment]
This just needed testing, and IIRC people on the Discord found it to work well.
