### ISSUE TITLE
All CSS icons treated as Mario (Special Versus-All Star)

### ISSUE THREAD

**Issue by Yohan1044** [TheOriginalSINe/Project-M-CC#370]
I'm having trouble nailing down the triggers this, but:

Sometimes when entering Versus mode for the first time, no matter what character (or pattern of characters), you select on the CSS for humans and CPUs, everyone gets Mario.

An example process the recreate:
0) Launch PM
1) Start and cancel a regular versus match
2) Go to Special Versus and turn on All Star Mode
3) Select whomever
4) Play as default Mario

Also, the icon used for Random (within All-Star versus), is now Isaac.

[Only tested on PMCC rev 185 on Dolphin w/ Gecko]

**Comment by Tac24** [comment]
strange no issues on this with the Wii\

however i will say that for me- when the my character dies and a new clone engine character loads in all star mode it sometimes may not respawn... reseting freezes the game... not sure what triggers this
