### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by EdinmavarThe3rd** [TheOriginalSINe/Project-M-CC#371]
Will sami and isaac be worked on further because in my opinion they shouldn't we should keep the roster without them and just keep the solid built characters I.e knuckles,Lyn,mewtwo and roy

**Comment by LnktheWolf** [comment]
They're being worked on because they're in the dev build, but they aren't high priority. Knux and Lyn are higher priority.

**Comment by PowerpointSmasher** [comment]
Please ask questions on the Discord instead of an issue. Issue's are for problems in the main build, not questions.
