### ISSUE TITLE
Project M Spy Texurtes?

### ISSUE THREAD

**Issue by Ninjaman11** [TheOriginalSINe/Project-M-CC#377]
for PM there are spy files which are for invisable mode,but for the retro mode that modders are making,it replaces invisable mode,my question is,who do you turn the regalur n64 smash texutres for characthers into spy files for retro mode?

**Comment by Kippy232** [comment]
If I understand your question correctly, you want to know how to change invisible models into retro models. This is a question, not an issue, and should be asked on the Discord. This should be closed.

**Comment by Ninjaman11** [comment]
yeah,but im new here and dont know where the comment button is.

**Comment by Kippy232** [comment]
That's fine; sometimes other people do the same thing.
On the hub page for this git (https://github.com/Project-M-CC/Project-M-CC), scroll down to where it says "Project-M-CC" in large bold letters. Right below the title are three small buttons; one for Gitter, another for Discord, and a third one for a Waffle.io. Click on the Discord button, type in a username, and click continue. From there you should be able to ask any questions you want.

@bb010g I think this should be closed now.

**Comment by PowerpointSmasher** [comment]
We should add to the readme that if you have question, don't ask on it on a issue, ask it on the discord

**Comment by Kippy232** [comment]
That seems like the most logical course of action. I'm not good with GitHub to that degree though so I'll leave it up to one of the collaborators.
