### ISSUE TITLE
Just to be sure, what was the consensus on uptilt/ftilt getting an extra hit?

### ISSUE THREAD

**Issue by SzionBlue** [TheOriginalSINe/Project-M-CC#379]
I remember asking about knux fully charge fsmash losing the explosion and y'all were like "no" and then u did, so now im asking about the uptilt/ftilt that had 1 more hit each in the leaked build videos long ago....are you SURE you're not gonna put that back in? cuz it seeeeems somewhat necessary..

**Comment by PowerpointSmasher** [comment]
Ask questions on the discord, not an issue.

**Comment by bb010g** [comment]
It's not getting adjusted right now from the newer leaks, both of which had it removed.
