### ISSUE TITLE
non-standerinsed css portraits

### ISSUE THREAD

**Issue by LinkTahuterasuSpirit** [TheOriginalSINe/Project-M-CC#380]
some characters do not have standerised portraits, like fox having a brawl pose and a melee pose and roys awakening alt have a new pose, the way i see it there are two ways to fix this. use the project m poses, or make brand new ones. its up to you guys on what you want to do. this is a low priority issue really, just a final polish thing

**Comment by cimpyhigh** [comment]
Yeah, everyone is aware of this.

**Comment by LinkTahuterasuSpirit** [comment]
@cimpyhigh i know, just wanted to address it sense it hasn't been brought up before

**Comment by cimpyhigh** [comment]
It's referenced in issue #359.

**Comment by LinkTahuterasuSpirit** [comment]
woops, sorry forgot about that post

**Comment by bb010g** [comment]
Closing as duplicate.
