### ISSUE TITLE
roy's final smash broken (instant kill no mater what)

### ISSUE THREAD

**Issue by LinkTahuterasuSpirit** [TheOriginalSINe/Project-M-CC#381]
when project m gave roy a final smash, for one thing some people stated it doesn't fit with the rest of the game, and also the knock-back on given when hit by it is op, hitting someone at 0% damage will bring it up to 80% damage witch is ok, but the knock-back makes this move instant kill no mater what. no other final smash can kill an opponent at 0%. as for how to fix it at least fix the knock-back for now, as for replacing it with a different final smash it's probably undesirable at the moment to do that. i guess this is a low priority issue or at least a medium priority issue. it at least needs to be fixed at some point

**Comment by cimpyhigh** [comment]
It's always been like that, not that huge of a deal.

**Comment by LinkTahuterasuSpirit** [comment]
@cimpyhigh for tournaments yea, but still i think the knock-back should be fixed

**Comment by PowerpointSmasher** [comment]
Well the PMDT wanted Roy's final smash to be like that

**Comment by LinkTahuterasuSpirit** [comment]
@PowerpointSmasher as in instant kill no mater what

**Comment by JackpotSHUnited** [comment]
Marth's final smash has been an instant kill since Brawl.

**Comment by LinkTahuterasuSpirit** [comment]
@JackpotSHUnited really? i've been able to survive marth's final smash before

**Comment by bb010g** [comment]
We're not balancing any 3.61 characters.
