### ISSUE TITLE
new announcer?

### ISSUE THREAD

**Issue by LinkTahuterasuSpirit** [TheOriginalSINe/Project-M-CC#382]
so with there being as you guys call them 'the forbidden 4' are you guys going to make a brand new announcer so that all the announcer clips are by the same guy? if so what will he sound like? i'd prefer it sounding more like the slightly more energetic 3.6 beta announcer then the more gruff 3.6 final announcer.

**Comment by robosteven** [comment]
I've been thinking about doing an announcer voiceover for some time. If PMCC would be interested, I could do voice calls for every character for the sake of consistency if you'd want.

**Comment by LinkTahuterasuSpirit** [comment]
@robosteven yea i think we should have a consistent announcer for the game, i'd try it myself but my voice isn't that good when lisening to my youtube videos, and trying to edit it to sound like how my voice sounds like to me probably wouldn't work

**Comment by bb010g** [comment]
We really don't need a new announcer. We need proper calls for some characters. If anyone wants to make their own pack with extra calls for the newcomers, feel free.
