### ISSUE TITLE
Special Versus All Star Mode randoms

### ISSUE THREAD

**Issue by Psydian** [TheOriginalSINe/Project-M-CC#385]
Selecting Random in Special Versus All Star mode never picks Knuckles or Lyn (or Isaac or Sami).  Knuckles, Lyn, and Isaac can be chosen by Random in regular mode

Edit: Also note that the character icons at the bottom by the percentages always show as Isaac's head if you pick random

**Comment by Psydian** [comment]
Also note that the character icons at the bottom by the percentages always show as Isaac's head if you pick random

**Comment by LinkTahuterasuSpirit** [comment]
that's because isaac's stock icon replaces the random stock icon. and it probably can't be changed at the moment
