### ISSUE TITLE
Special Versus All Star stock steal issue

### ISSUE THREAD

**Issue by Psydian** [TheOriginalSINe/Project-M-CC#386]
In special versus All Star, if you are playing teams and you try to take a stock from your teammate who has 3 lives left (I believe this works for any number 3 and up), it will show that the stock is taken and the taker will revive, but when the person whose stock got taken dies, they will respawn again with 2 stocks (instead of 1).

Quick sum-up: Taking a life in teams from a person with 3 or more stocks doesn't actually work, their next death will not reflect the life stolen

**Comment by PowerpointSmasher** [comment]
This is not an issue. It's something called Share Stock. It's been in Smash since Smash 64
