### ISSUE TITLE
How to use custom stages?

### ISSUE THREAD

**Issue by darkralts** [TheOriginalSINe/Project-M-CC#389]
Not an issue but couldnt find a help section.

**Comment by bb010g** [comment]
Could you give some more information on what you've tried and what you want to accomplish? [We can't help you if we don't know what you need.](http://www.catb.org/esr/faqs/smart-questions.html)

**Comment by PowerpointSmasher** [comment]
Ask questions on the discord.

**Comment by bb010g** [comment]
@PowerpointSmasher Not all questions need to be asked there. This is something that could benefit from being stored for future use.
