### ISSUE TITLE
Wi-Fi Codeset

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#39]
Once a merged codeset is created, a Wi-fi codeset should be created:

Message from oxMugetsuxo on Reddit: Ive spoken to wiiztec and he said you simply need the wiimifi patcher code from the previous wifi codesets and then to remove Lightshield and roll buffers from the latest

**Comment by oXMugetsuoXo** [comment]
Not sure if this matters but I rememeber in earlier PM builds wifi sets didnt have stage striking. I dunno the reasoning behind it but just saying it just in case it helps in some way.

On a side note  In 3.6 there was a wifi stage/character costume slot problem that caused many of the online stages to desync. There also was a problem with alternate stages being loaded without the user actually holding "L".  I know priority is releasing the wifi set itself before taking on any bugs that come with it but figured Id throw that out there.

**Comment by ewmb7701** [comment]
Wifi codeset added. Needs testing. Closing issue.
