### ISSUE TITLE
The new characters do only one damage to Master Hand

### ISSUE THREAD

**Issue by icecapman10** [TheOriginalSINe/Project-M-CC#391]
title

**Comment by GunBlazer** [comment]
If by that you mean "1% damage", it does not happen on my end.

**Comment by cimpyhigh** [comment]
Could you be more specific?

**Comment by icecapman10** [comment]
Every time I hit Master Hand with Knuckles or Lyn, it only does one HP damage

**Comment by zero1998** [comment]
i have also seen this  why is that
