### ISSUE TITLE
N64 Models: The Answer is here.

### ISSUE THREAD

**Issue by SmashLegacy12345** [TheOriginalSINe/Project-M-CC#392]
Hey guys! I can't stay here for long. I just found a Smash Bros. Mod that has N64 Models inserted into it. Smash Bros. Legacy has it all! Watch the trailer here: https://www.youtube.com/watch?v=VJpBg0-Uo4Y

I only made my account to share with you the news. All responses, and questions can go to the creator of the Mod himself. Have a good day! Abandoning account now...

**Comment by bb010g** [comment]
We do know about Legacy. @davidvkimball hangs out here and on the Discord from time to time. :) Anyhow, just mentioning that Legacy has a 64 mode doesn't help much. I'd imagine it's built on replacing `Spy` models, as we were doing, but that AFAIK still has problems with drawing with shields (the models are drawn over, not under). (That may be fixed, but I haven't downloaded the build yet to check and it was ambiguous in the release video.) (**Ninja edit:** It is based on Spy.) Our current plan is to team up with the 64 Mode project @PyotrLuzhin is leading, or, in the case of obligations with former PMDT getting in the way, to find a method to be able to patch a CC build with 64 Mode, keeping the formal build clean but allowing the user to make their own, private build with ease. Also, it may be beneficial to provide a guide to patch builds like Legacy with CC changes (3.61 CC new chars, animations, and movesets) to allow greater adoption of the pure content, what this build is at its core about, without requiring awkward discussions between build creators and content creators that may not want to have their content associated with such a..._messy_ batch of content at present.
