### ISSUE TITLE
Permanent PM brick?

### ISSUE THREAD

**Issue by bb010g** [TheOriginalSINe/Project-M-CC#394]
From [a bug report on Reddit](https://www.reddit.com/r/SSBPMCE/comments/4d2fzz/cc_broke_my_wii/d1ofc08):

> Well it goes black whenever I load PM, and I couldn't fix that whether I reformatted, deleted my save, or got a new build, and Nano said it was CC corrupting something in my Wii

**Comment by robosteven** [comment]
Does it affect anything else aside from SD card access?

**Comment by darkralts** [comment]
did you try both methods? hackless and homebrew? i haven't had this happen to me, the worst i get is music distortion or a crash.

**Comment by bb010g** [comment]
@darkralts That sounds like a problem with fragmentation on your SD card.

**Comment by PhoxFyre** [comment]
Has this been fixed @bb010g ?

**Comment by bb010g** [comment]
Should be fixed with implementation of #398.
