### ISSUE TITLE
Removing access to incomplete characters (highly unimportant)

### ISSUE THREAD

**Issue by metaknight120** [TheOriginalSINe/Project-M-CC#395]
I'm just using this build to play the game for myself and with a friend, I wanted to remove Isaac and Sami from both the Character Select Screen and the random button. When I tried to do this with Mewtwo2000's CSS editor it worked for the CSS, but when I picked random it worked for a few matches but crashed as soon as it tried to load a random character in one my matches. I haven't added any costumes so there's no way that caused problems. my only bets are that things somehow screwed up by picking Ganondorf (who I installed a PSA for) or it tried to load one of the characters I tried to remove access to. Oddly, I made no changes to Isaac and Sami, and Dorf worked when I picked him manually. This happened on Pokemon Stadium 2, I'm not sure if it's the most recent build.

**Comment by PhoxFyre** [comment]
use the pm 3.6 version that comes with it, or you can remove it yourself.
