### ISSUE TITLE
Knuckles Item Dash

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#397]
For unknown reasons, Knuckles' item dashes propel him forward at an extreme speed, easily outrunning Sonic's normal run(the fastest run in the game). To replicate, use Knuckles, and try dashing while holding a Cracker Launcher.

**Comment by toonjoey** [comment]
I knew Knuckles was some kinda Jedi master. lol

But really, someone should check the code to see why this happens. I'm guessing that Knuckles seems to have some kind of corrupt speed code. Normally, the code sets characters to be the same/slower speed with an item like a Cracker Launcher. When the game checks Knuckles' code it makes mistakes in the "speed" of the character, and causes it to become sanic. lol
