### ISSUE TITLE
Knuckles: Down Throw punches don't hit ROB

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#40]
Knuckles Down-Throw does not work on ROB

Suggested Fix: Re-position ROB when he is grabbed.

**Comment by andy-bond** [comment]
While playing with a friend, I noticed that Sonic's Down-Throw also puts ROB underneath the floor of the stage. Happened on Smashville if that matters.

**Comment by ghost** [comment]
This not only affects Rob, but a number of other characters as well. I'll test exactly who is affected sometime soon and post my results.

**Comment by robosteven** [comment]
Should change the title back to what it was originally, down-throw only whiffs the punches on ROB and ROB alone.

Just tested this with every other character, Isaac and Sami included, all worked but ROB.

**Comment by ghost** [comment]
Fixed by doubling the size of the hitboxes.

**Comment by bb010g** [comment]
@Rage17 Has that been pushed, or does it still need to be put in?
