### ISSUE TITLE
Knuckles Goes Into Freefall Animation Out of Up-b

### ISSUE THREAD

**Issue by robosteven** [TheOriginalSINe/Project-M-CC#400]
Turns out the freefall isn't the issue, it's the ending of the Up-b and airdodge animations linking into the freefall stance. Airdodge is Sonic's, which isn't used to the new freefall animation, and the end of up-b has the same problem. This seems like an easy enough fix, I'll probably end up giving it a shot but someone feel free to beat me to it if I can't figure it out.

Specifically, it's frames 30 to 31 of the up-b itself, and 49 to 50 of the airdodge. More frames need to be adjusted aside from those ones obviously, but this is just for clarification.

**Comment by ghost** [comment]
Fixed in the upcoming PR, because of the decision to revert special fall to the Sonic one.
