### ISSUE TITLE
Knuckles' F-smash Explosion

### ISSUE THREAD

**Issue by Mirax96** [TheOriginalSINe/Project-M-CC#403]
This is really low priority but Knuckles' fully charged F-Smash explosion should be like it was in the original leaked build (AKA bigger), it is based on the "Deep Impact" from Sonic Battle and in the present version of PMCC it's less similar.

Description from the game: "The user performs a punch which is so powerful that it causes friction with the air, creating a small explosion."

See here at 5:02 https://www.youtube.com/watch?v=rXfs7-7SKTo

**Comment by bb010g** [comment]
The present version is from the latest available Knuckles leak from the PMDT, and will be kept as such until _much_ later if balance requires.

**Comment by ghost** [comment]
Noting that this was presumably changed to avoid a fully charged smash attack having a significantly larger hitbox than the uncharged version. Before it gets cited as excuses for this, Bowser's F-smash explosion does not make the attack bigger. It merely places a small graphic on his head, while the attack itself already uses Bowser's entire front side. Also, while Lucas's Offense Up version of Up Smash is bigger than the normal versions, bear in mind the obvious: the idea there is pushing the Smash attack even further than charging it normally.

**Comment by Mirax96** [comment]
Well, yeah, I'm just talking about the loyal graphic, I understand that the hitbox has to stay like this
