### ISSUE TITLE
Mewtwo and Roy metal voice

### ISSUE THREAD

**Issue by GamingMaster777** [TheOriginalSINe/Project-M-CC#404]
both of these extra characters have their voices when they become metal

**Comment by LinkTahuterasuSpirit** [comment]
are you sure? project M fixed that in 3.5

**Comment by GamingMaster777** [comment]
iirc they can talk

**Comment by GamingMaster777** [comment]
btw idk will rainbow mode be added like legacy

**Comment by Yohan1044** [comment]
For the record,
Roy is fully voiced when metal in all of PM3.6, PMCC_commit193, and in PMEX_0.4

Unrelated to the titled issue. The rainbow costumes overwrite the dark costumes used within the subspace emissary. The ability to do "Rainbow" mode in Legacy is a combination of overwriting these dark costumes and a GCT code (aka. load dark costumes when a button combination is held at the character select screen). This GCT code is included in PMEX_0.4 and 0.5's codeset.
Including this code opens up some issues... as many characters do not have Dark costumes (Toon Link, Jigglypuff, Wolf, Sonic, ZeroSuitSamus, Warioman, Roy, Mewtwo, all newcomers). Furthermore, Peach and Snake require entry files for their dark costumes to prevent crash at match start. Dark costumes exist for some of these missing characters.
That was a long tangent.

**Comment by GamingMaster777** [comment]
it suddenly came to mind after ur comment cuz i was wondering if it would be nice to add it. personaly, im sure the pmdt might add it it wood be nice if they did

**Comment by LinkTahuterasuSpirit** [comment]
strange, Roy and Mewtwo never spoke in Metal form for me ever sense 3.5

**Comment by ghost** [comment]
@LinkTahuterasuSpirit @Yohan1044 there was a fan made fix for the metals, which is probably why you didn't hear their voices.

**Comment by LinkTahuterasuSpirit** [comment]
@Rage17 that might be the case though, i dont recall getting that fix before. well if the metals have voices in this build then it would need to be fixed at some point
