### ISSUE TITLE
why won't the new characters come up on the character select screen?

### ISSUE THREAD

**Issue by Soulwillin1997** [TheOriginalSINe/Project-M-CC#405]
I need help trying to get the character slots to come up so that I can play as them. please help me!! :(

**Comment by GunBlazer** [comment]
Have you downloaded the latest PMCC revision? They should be out automatically.

**Comment by bb010g** [comment]
Works on my end. If you can provide reliable steps to reproduce from a clean SD and reinstall, we'll take a further look.
