### ISSUE TITLE
New portraits for Lyn, Sami and Isaac.

### ISSUE THREAD

**Issue by ManlySpirit** [TheOriginalSINe/Project-M-CC#407]
They're done in Smash 4 style. Here's Lyn:

![lyn smash render-3](https://cloud.githubusercontent.com/assets/16632519/15131713/b9a6739a-1652-11e6-8af8-6ff2054c7fe7.jpg)

Recolors incoming tomorrow. Isaac and Sami by Monday (?). I won't be doing one for Knuckles since he has plenty of good CGs floating around, and the one he has in PM is nice. The other three have really ugly portraits though, and desperately needed some decent art. I tried to achieve the quality of the Smash 4 portraits, since I'm keeping Smash 4 modding in the future in mind. On that note, I also plan on making better 3D models for those three characters in the near future, since again, the ones in the leak are of rather amateurish quality. My intention with Lyn is to have her match the style and quality of this portrait you see here.

Also, I made a post a while back on the quality of Lyn's animations. If no one is handling those, I'd like to tackle them myself since I recently got Maya installed on my new tablet. I've been outta the loop since I haven't been keeping up with things lately though, so I'm not sure if someone else has or is working on them.
Anway, feel free to use this and the future ones I'll be posting, just be sure to credit me though, since I'm seeking exposure. 

Cheers :D

**Comment by bb010g** [comment]
That's a really nice painting! It'll do nicely while we work on fixing the costume and getting proper renders in.

If you want to start tackling Lyn's animations, feel free. AFAIK @thecoolguy27 hasn't really been working on Lyn, so you wouldn't be duplicating work.

**Comment by ManlySpirit** [comment]
Cool, then I'll get to making an HD model for Lyn as well as fixing her animations once I do the other two portraits. This is mostly for practice for me anyway, so tsawlgewd. Those other two will take a while longer though, since I got a couple other things in the pipeline as well.

**Comment by ManlySpirit** [comment]
![lyn smash recolors](https://cloud.githubusercontent.com/assets/16632519/15148075/f2609316-16c3-11e6-892a-972026e4b412.jpg)

Recolors, working on Isaac now.

**Comment by ghost** [comment]
@ManlySpirit I really would recommend joining the Discord/Gitter if you haven't already. Discord's essentially where development happens until things are ready for a pull request.

**Comment by ManlySpirit** [comment]
I think I just sent in the code for request. I'm not too keen on how to use Discord, but if it didn't go through my username there is the same as here.

I'd really like to form a part of this group, with Smash 4 modding kicking up I have ton of ideas I think we could all work on in order to make something truly awesome.

Anyway, here's Sami and Isaac. 

![isami](https://cloud.githubusercontent.com/assets/16632519/15225367/73dd1e4e-187e-11e6-9afc-70532fc87e90.jpg)

I'm thinking I'm gonna stop here for now with these two, for one, since a full render is a lot of work (Lyn took like 30 hours), and it's just wasted effort when the best way to get a CG look is to render a CG, so I'll just get to working on those models and detailing them to this style.

But also, I'm gonna stop halfway with these two cause I really like the style and the look of them. I'm actually considering doing the whole roster in this style. You guys may or may not use it for PM as you see fit, but what I think would be cool would be to see a whole roster for a WiiU project with ports in this style, I feel the lineart adds a lot of personality to things. Also, these take much less time to do (Sami and Isaac both took about 5 hours combined).

What do you guys think? Would you be interested in something like that? Not for PMCC, but for a future WiiU project?

Anyway, add me to discord and we'll talk. In the meantime I'm gonna get started on modeling these three and then onto the animations.

**Comment by ghost** [comment]
@ManlySpirit 
![image](https://cloud.githubusercontent.com/assets/16145986/15227338/b81e0818-1854-11e6-979c-931929173446.png) Have you been able to get to this screen?

**Comment by LinkTahuterasuSpirit** [comment]
man are those model renders? or HD Digital Art for Lyn? it looks amasing, when i start working on a Smash pack idea ive had for awhile i would love to have you're help on the portraits

**Comment by ManlySpirit** [comment]
@LinkTahuterasuSpirit

Thanks man. Yeah, on Lyn it's a digital painting. Idk if I'll make more since Lyn did take me like 30 hours, but I will gladly give a hand with doing custom CSPs in the artstyle I have for Isaac and Sami.

**Comment by seijinshu** [comment]
I personally think that if we were to use the CSPs above for Lyn, we should just remake her model to match them. I really like the Lyn CSPs, and if we re-made the model to match them, it would be nice.

**Comment by LinkTahuterasuSpirit** [comment]
@ManlySpirit ok so how would i contact you?

**Comment by TheSmashBoy** [comment]
I love the portraits. Particularly Lyn's. I'm looking forward for Awakening Lyn, but aside that. Great stuff @ManlySpirit, keep up the good work.
