### ISSUE TITLE
Isaac CSPs, Knuckles Animation touch ups and helping out with the team.

### ISSUE THREAD

**Issue by MazeDIs** [TheOriginalSINe/Project-M-CC#408]
I'd like to help with the PMCC 3.61 Dev Team. Here's what I offer:

CSP Work:
![menselchrfaceb 1121](https://cloud.githubusercontent.com/assets/18184901/15461086/a496230a-2085-11e6-9c0e-e230cddd0932.png)
![menselchrfaceb 1122](https://cloud.githubusercontent.com/assets/18184901/15461089/b1a9657a-2085-11e6-9a76-5bd9666771c0.png)
![menselchrfaceb 1123](https://cloud.githubusercontent.com/assets/18184901/15461091/b7e2a7bc-2085-11e6-8a8e-95cd7c4b4110.png)
![menselchrfaceb 1124](https://cloud.githubusercontent.com/assets/18184901/15461092/bb8956a4-2085-11e6-8323-a422d74cafa3.png)
![menselchrfaceb 1125](https://cloud.githubusercontent.com/assets/18184901/15461093/bdceab94-2085-11e6-9272-0f6c266a10af.png)
![menselchrfaceb 1126](https://cloud.githubusercontent.com/assets/18184901/15461095/bfcc7980-2085-11e6-9201-69676040a4a0.png)
![menselchrchrface 112](https://cloud.githubusercontent.com/assets/18184901/15461098/c61fdade-2085-11e6-9e71-efcc65f388c5.png)

Knuckles Animation Touches:
https://www.mediafire.com/?kq1uq9xc4xkcu38

Animation and CSS Cosmetics is my strongsuit i guess. I just want to help moreso than anything.

**Comment by LinkTahuterasuSpirit** [comment]
no offence, but i think the Issac CSS portraits could be a bit better than that, this is at least an improvement to the Dev Builds CSS but it doesn't seem like it fits with smash to me, and Issac just has a blank stare in those portraits. again i'm not trying to offend you in any way, im just giving you constructive criticism, the ones shown here arnt terrible by any means i'm just saying you could probably do better

**Comment by MazeDIs** [comment]
I actually agree with you. They were there moreseo as a quick replacement to the bland dark and etionless ones that cane in the Dev build. I'll get around to making better ones soon

**Comment by LinkTahuterasuSpirit** [comment]
ok
