### ISSUE TITLE
Trying to pick Sami crashes the game.

### ISSUE THREAD

**Issue by Delta-Kuro** [TheOriginalSINe/Project-M-CC#409]
I've noticed that whenever I (or anyone else) tries to choose Sami, it simply crashes the game. Although it may just be me, I wanted to make sure.

**Comment by cimpyhigh** [comment]
Think it's just you. I've never had the issue

**Comment by bb010g** [comment]
What are you playing on?

**Comment by Delta-Kuro** [comment]
Wii.

**Comment by bb010g** [comment]
Try reformatting your SD card.
