### ISSUE TITLE
Sheik/Zelda: Stock icons don't change

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#41]
If Sheik changes into Zelda mid-match, stock icons are not updated.

Suggested Fix:
Find out what is causing it and fix it.

**Comment by ghost** [comment]
This was an issue I believe even PMDT couldn't figure out. It may have to do with the stock icons being loaded at the beginning of the match and not getting updated in the middle of a match. I have no idea how to force the game to constantly update stock icons though.

**Comment by KymaeraK1ng** [comment]
Hmm. Someone could still try to fix it.

**Comment by bb010g** [comment]
Should be fixed when we switch over to PMEX, or not. Either way, out of scope.
