### ISSUE TITLE
Is there a way to add stages to the CC?

### ISSUE THREAD

**Issue by Delta-Kuro** [TheOriginalSINe/Project-M-CC#410]
I already have the extra slots in, but I need to know how to actually add the stages in. I have the .PAC files and the PNGs, but both programs I've used give no actual way to add them. Do you just put the .pac files into the stage/melee folder?

**Comment by Delta-Kuro** [comment]
Nevermind about the extra slots, adding those removed the extra characters. Does anyone know how to add (not replace) stages to the CC?

**Comment by ithunderHD** [comment]
Yes u do put them in the melee/stage folder

**Comment by ithunderHD** [comment]
And the only way you'll get to add stages is by adding a alternate stage to stage already in the game otherwise u gonna have to replace a stage

**Comment by Delta-Kuro** [comment]
Well, in that case, does anyone know how to make this work with the CC?

http://smashboards.com/threads/stage-expansion-template-for-pm-3-6-final-four-versions.345936/

When I installed it, as earlier stated, it removes all of the extra content of the CC.

**Comment by Delta-Kuro** [comment]
Well, I found the manual codes to install, but it causes the screen to glitch and have all of the extra slots become hannenbow. Progress? Either way, I'll keep everyone updated in case I find a way to add stages to the selection screen (that way I can actually become a contributor to this project instead of just wasting everyone else's time. lel)

**Comment by ithunderHD** [comment]
Oh that won't work because it's not updated to 3.61\cc,infact they haven't really updated in a while so...

**Comment by ithunderHD** [comment]
OK but I recommend just going for alternate custom stage slots

**Comment by Delta-Kuro** [comment]
Although that may work, I want to be able to give them their own slots, and their own music (30% of the reason being that we need Pepsi Man.)

**Comment by Delta-Kuro** [comment]
If anyone has any suggestions on how to get this working, however, I would be happy to listen.

**Comment by LinkTahuterasuSpirit** [comment]
the music thing has been something ive been trying to figure out too, once i'm done with school for the year i plan on finding out how to edit the song lists on the stages, though as far as i know alt stages can only have the same music as the original. as for adding new stage slots one thing we could do is ask the creater of the PM stage expansion to make a version of it the works with 3.61/CC. other than that i dont see any way to get it working.

**Comment by Delta-Kuro** [comment]
Well, either way, I'm going to see if there's anything I can do aside from requesting for him to update it (which I just did).

**Comment by LinkTahuterasuSpirit** [comment]
well good luck man, i know from experience that things like this can be hard but not intirly imposible

**Comment by Delta-Kuro** [comment]
Well, I've made progress: I've modified the GCT to contain the stage expansion (+12) codes instead of the standard stage selection codes, and the characters from the CC are still available and work. From here, the next steps seem much more obvious, so I believe I'll be able to succeed. Obviously, if I complete it, I'll post the files here.

**Comment by ithunderHD** [comment]
OK and nice job

**Comment by Yohan1044** [comment]
Liberty Erie's Stage Expansion Template works perfectly fine with PMCC and is installed and customized exactly the same as one would do for vPM3.6.

However, this a personal customization outside the scope of PMCC project. Talks of adding and rearranging the stages happened months ago, and the conclusion is that PMCC will keep the default stagelist. This ticket should be closed.

**Comment by bb010g** [comment]
Closing, but feel free to keep discussing this here. The build is somewhat deprecated though, and will be removed in its current incarnation upon the switch to PMEX.
