### ISSUE TITLE
An idea for the future of Project M.

### ISSUE THREAD

**Issue by Delta-Kuro** [TheOriginalSINe/Project-M-CC#411]
I've noticed that over the course of development on the CC, there has been a major argument on whether or not to add new content or to just complete what the former PMDev team had been working on for the past six years. As such, I believe a compromise is in order: complete the CC, ending it at version 3.61, and then begin a new project based on the CC at version 3.7, with some sort of name referencing Project M, but not completely calling it a continuation; an example name being something along the lines of "Project N". It would allow for the original Project M to be completed, while allowing us to be more creative after the fact. Of course, there are Pros and Cons to this:

+Allows for more freedom of what to do with the project
+Most likely more publicity
+Allowing the Legacy to live on
+stopping the argument between the two sides

-Would take more time to update
-Would always be compared to the original Project M, having to live up to the expectations of it constantly
-Would probably have to eventually spend money for our own website/domain

And, of course, things that may be a pro or a con, depending on your belief:

+/- Trailers
+/- YouTube channel
+/- We get to make the April Fools' Jokes

Although it may not be my place to give this idea/make this suggestion, I believe that it needed to be said. Thank you for reading this wall of text.

**Comment by LinkTahuterasuSpirit** [comment]
i kinda like that idea, though i think the renamed version should be called Project S (Project Smash) to make it more original, what do you think?

**Comment by Delta-Kuro** [comment]
That would probably work. I was simply using "Project N" as an example name. Project S actually sounds better, to be honest.

**Comment by LinkTahuterasuSpirit** [comment]
cool

**Comment by Delta-Kuro** [comment]
Well, after seeing the news on all of the new leaked content, I say we wait until 3.8 to create our own project. XD

**Comment by bb010g** [comment]
Official project stance: Any future project working to continue in full capacity in a manner similar to the efforts of the old PMDT will not be affiliated with PMCC.

Personal opinion: Watch out for legal troubles if you decide to go through with this.
