### ISSUE TITLE
there's some more leaked content that wasn't in the build that I found online

### ISSUE THREAD

**Issue by ithunderHD** [TheOriginalSINe/Project-M-CC#412]
Go check it out https://gamingreinvented.com/news/new-project-m-content-leaked-v/ I haven't herd about in leaks in long time and this is the latest one

**Comment by LinkTahuterasuSpirit** [comment]
wow im impressed by just how much stuff there is here

**Comment by Delta-Kuro** [comment]
Well, it seems like Project S is going to wait until the CC is at 3.8, then. XD

**Comment by Delta-Kuro** [comment]
So, are we going to be working on this for the CC, or will this not be considered?

**Comment by ithunderHD** [comment]
I guess yea but what happen to everybody that was working this project  they suddenly stop make pull request and things

**Comment by ithunderHD** [comment]
But the only thing we puting in from these leaks is the fox moveset edits

**Comment by Delta-Kuro** [comment]
I personally think that we need the maps, menu, and character updates. After all, our goal is to complete what they started, right? Plus, adding in costumes shouldn't be too difficult. Let's make sure to get Project M to its true completion. I'll see if there's anything I can do for the extra stage slot addition, considering that's what I'm already working on.

**Comment by ithunderHD** [comment]
Agreed, Yes we do need the maps,menus,fox,and everything else but we can scratch out using pichu/D1

**Comment by ithunderHD** [comment]
Are u going to start working on it soon Delta kuro

**Comment by ghost** [comment]
Hey guys! I'm new. I believe i can help you out. Here is the zip with everything in it.

Link: https://drive.google.com/file/d/0Bzl-36ud20HTZ3NSSjV6RGhTUmc/view

**Comment by ithunderHD** [comment]
Thanks ghostly33 for the download with everything in it that was a big help

**Comment by ghost** [comment]
You're welcome.

**Comment by Delta-Kuro** [comment]
Also, about the question for the stages, I already have the +12 expansion in progress. If we need more slots, tell me and I'll see if I can get it working. By the way, thanks Ghost.

**Comment by ithunderHD** [comment]
Do u have custom templates yet?,for stage selection

**Comment by ithunderHD** [comment]
And Delta kuro I think we only need 12 more stages so your on the right track

**Comment by Delta-Kuro** [comment]
Alright, then. I'll probably get it done within the next few days.

**Comment by bb010g** [comment]
As stated in #398, the goal of CC is to finish the newcomers, not continue the whole of PM development. These are neat, but not in scope.

**Comment by shitaki** [comment]
I'm sorry bb010g to open up an old thread. I'm Falynn44 from the Riot chat. 
But @ithunderHD I wanted to ask you if you still have a copy of these leaks because I would like to try to integrate Bowser fireball leak over the current Bowser natural. But the MEGA links are offline and ghost's Google Drive link is offline too unfortunately. I would really appreciate it if you could help if possible. Thank you and have a nice day!

**Comment by MazeDIs** [comment]
So these leaks are officially offline like everything else?
