### ISSUE TITLE
New Project M Leaked Content

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#414]
New info was leaked. Apparently, Project M has even more leaked content.

You can use this link:  https://drive.google.com/file/d/0Bzl-36ud20HTZ3NSSjV6RGhTUmc/view

I have a couple suggestions. 

**Why don't we just use these in the pack:**
D1
Fox
Fireball Bowser
Melee Transition Data

**What will NOT be used:**
Pichu (Consideration)
Pig Ganon
Bumblebee Ness for Jiang
Main Menu
NEW - LIMITER
ported maps
Concept Art (Obviously)

You should consider it when you guys are done patching the characters.
If not, then i understand.

**Comment by ithunderHD** [comment]
Agreed

**Comment by TheSmashBoy** [comment]
I would look forward for those content.

**Comment by MazeDIs** [comment]
Does anyone have an extra build of this floating around? I'd love to test this with some of the characters i've worked on for my winter build release (full actual quality movesets)
