### ISSUE TITLE
Isaac Item attacks

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#416]
Isaac has item animations, but his jab and side smash with "stick" items have improper hitboxes. "Stick" items being beam swords, home run bats, lip's stick, and fans.

**Comment by toonjoey** [comment]
I'm sure it's about the "Isaac uses Ike resources" thing, but we'll need to look into this. I've never modded anything related to Brawl, just Mario 64, Toontown, and Paper Mario.
