### ISSUE TITLE
{Project M CC} What's going on? No News? No Updates to the game or characters lately?

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#419]
Everyone's wondering what's going on right now.

Are you guys working on something important?
Because you haven't updated anything yet, except for Knuckles.
Are you finishing the characters? Fixing the crashes? Transferring everything to Project M EX?

Or are you using the concept art Project M used for the new updated leak?
Which many people here tried to give to you guys.

You know, this one: https-//drive.google.com/file/d/0Bzl-36ud20HTZ3NSSjV6RGhTUmc/view

Another update for the characters seems appropriate now. For Knux, Lyn or Isaac.

**Comment by Kippy232** [comment]
I've been wondering, too. I've seen nothing lately aside from now-dated Knuckles fixes.

**Comment by TheSmashBoy** [comment]
Hi guys. I'm new and recently signed. I have been using your build for quite sometime and think this issue deserves some attention. I also am wondering if you guys are still working on the characters. Or are still deciding whether or not to integrate PMBEx. This project has an excellent premise and we can't let it die. We have to do better than the former team. Show them this project is not something Nintendo can take down. This project has a lot of potential and feel you guys should continue it.

 Just thought I laid that out.

**Comment by TheSmashBoy** [comment]
@ghost @Kippy232 I recently got informed about the status of this project. The project still continues. However, bb010g is still trying to figure out how to get PMEX working in a manner as to facilitate transferring the leaked fours into PMEX template. There are also continuing, hard work on getting the characters polished and bug fixed (particularly Lyn and Knuckles who are near completion). So they are still very busy. Hope this helps.

**Comment by bb010g** [comment]
New character repos are open. See https://www.reddit.com/r/SSBPMCE/comments/4uvxgl/project_m_community_complete_coming_to_a_pmex/ for a current news type thing and #398 for a roadmap.
