### ISSUE TITLE
Kirby's neutral B and the new characters

### ISSUE THREAD

**Issue by poiuyyuiop** [TheOriginalSINe/Project-M-CC#42]
When kirby use his neutral B on lyn and "stole" her power, there's no kirby alt and when you try to use the n-b , the character freeze.
Didn't try this on the other 2 but it should be the same

**Comment by ewmb7701** [comment]
This issue seems half-fixed; Kirby no longer crashes the game, but the new clone characters do not have ability hats.

**Comment by ghost** [comment]
I'll create new issues for adding kirby hats for Knuckles and Lyn

**Comment by bb010g** [comment]
Related issues are #117 & #118.
