### ISSUE TITLE
Sami and Isaac freeze game in multiplayer

### ISSUE THREAD

**Issue by TheSmashBoy** [TheOriginalSINe/Project-M-CC#422]
Not sure if you guys know but, particularly Sami, when I played with my friends on one-one, whenever they pick Sami, the game just freezes. Once it was the case when Sami and Isaac where matched up on any stage except Final Destination or Battlefield. Now it seems like just picking Sami freezes the game. Literally, it's a problem. On my personal tournaments, Sami became from FD/BF exclusive to outright banned because of this glitch. Any ideas how this is happening. Isaac occasionally freezes the game upon choosing him in multiplayer but not as significantly as Sami. Any ideas what exactly is causing this?

**Comment by Darquezze** [comment]
Wierd on mine, PM characters were missing files so I redownload them, but Issac never freezes game for me
