### ISSUE TITLE
This build's test Results. (The Info you need before you setup PM EX.

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#428]
Mewtwo and Roy can't pair up with Kirby on any stage.
It crashes the game everytime we do so.

I tested this Sami Build with a new idle pose, and it worked!
https://github.com/Project-M-CC/Project-M-CC/pull/334

Surprisingly, it didn't crash the game at all. It nerfed and gave sami a few new moves that i think you should both try out, and edit yourselves.

Knux and Sami Paired with kirby is Unstable.
When inhaled and swallowed, kirby freezes in place.
The only way to unfreeze him is to... of course...  punch him.

Giga Bowser is known as Sami. That needs to be patched.

When on the character select screen, when you pair up "Random" with any other Character, it freezes both before, and after you go to the stage select screen.

Lyn, Issac, and Knux need new victory animations, final smashes, and clapping animations.

Other obscure animations need revamping too.

Most of the Project M 3.6 characters need to be worked on, too. 
Including Dr. Mario and his Pills.
https://www.dropbox.com/s/dvik29nv4z1a38g/FitMario.pac?dl=0

**Comment by ghost** [comment]
All the details that you need is right here.
If you want to merge the "Sami" files, then please do so.

**Comment by bb010g** [comment]
First thing: I can't talk to you if you're a ghost. Don't smegging delete your account after a little bit; I need to talk to you most of the time.

I can't merge anything in in good faith without a full changelog, or at least description of what's new. "Nerfs" isn't good enough.
