### ISSUE TITLE
Isaac: Up Smash

### ISSUE THREAD

**Issue by thesmashking25** [TheOriginalSINe/Project-M-CC#43]
I believe Isaac's U-Smash is supposed to have another element to it. Maybe something similar to Pikachu's down-b?

**Comment by thesmashking25** [comment]
This move is most likely incomplete.

**Comment by PKPenguin321** [comment]
I noticed this as well and considered reporting it. From the looks of it, the current hitboxes on his body are supposed to throw an enemy upwards into something, likely a ball of fire or bits of debris like in this image:
![Isaac usmash](http://vignette1.wikia.nocookie.net/goldensun/images/b/be/IsaacPromo.jpg/revision/latest?cb=20080305060055)

**Comment by thesmashking25** [comment]
@PKPenguin321 maybe we can find an older PSA?

**Comment by bb010g** [comment]
@PKPenguin321 Makes sense; his range seems to be pretty weird with it right now.

@thesmashking25 This move probably wasn't finished, and this is the most finished we'll see of it. We may just have to make this move ourselves.
