### ISSUE TITLE
I heard about N64 Mode.

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#434]
My formal account name is "n64man", and I saw a video on Youtube that shows progress on N64 Mode.
 Here it is:
https://www.youtube.com/watch?v=2i0d_NSvGvc&spfreload=10

I also have 2 questions abou this:

1. Are you guys working  on this with him?
If so, explain it in full detail.

2. Are you separately working on this?
Specifically N64 Mode and The Characters separately?

THX. (And sorry for ditching my account.)

**Comment by bb010g** [comment]
We can't have a conversation if you delete your account immediately.
