### ISSUE TITLE
ISO BUILDER black screen

### ISSUE THREAD

**Issue by ricc4rdotregna** [TheOriginalSINe/Project-M-CC#436]
Everytime I create an iso with iso builder of pm cc and i try the game on my wii, the screen goes totally black. My wii is modded. I use wbfs and usbs to play the games. Can somebody help me?

**Comment by ghost** [comment]
You don't have to build an iso, that's outdated. Just enable ocarina codes in the usb loader and set up your sd card as if you were using a disc.

**Comment by ricc4rdotregna** [comment]
Does this works also for smash infinite or pm ex?

**Comment by ghost** [comment]
It works for TE:X, so I would assume so

**Comment by ricc4rdotregna** [comment]
All right. I put everything in my sd card, i put ssbb ntsc on my hard drive and it still doesn't run pm cc. It runs ssbb normal but everytime i go to do a normal match, it shows me that there are more character slots, like there are two sonics on the roster and when i open the match menunit freezes the screen. What i missed? Also my wii is pal if this could help

**Comment by bb010g** [comment]
What loader are you using? This version of CC works fine when loaded just like normal PM 3.6 in Configurable USB Loader.

**Comment by PatziPatzpatz** [comment]
Tested it, I built an ISO with BrawlBuilder and it worked (with Wiiflow)

**Comment by bb010g** [comment]
Closing this for now due to @ricc4rdotregna not replying.
