### ISSUE TITLE
Issac causing glitches

### ISSUE THREAD

**Issue by Jackknife18846** [TheOriginalSINe/Project-M-CC#437]
I was playing CC as Issac and whenever I use a lot of smash attacks Issac (I can only assume) Grows massive and stretches so it leaves half the screen a massive blob of yellow and I main Issac, so that happens pretty frequently.  Also (this isn't a problem) could you add a custom voice for Issac?  I can't stand his toon link voice, and his entry would be fine if you removed the cartoon explosion effect from it.  Thanks!

**Comment by bb010g** [comment]
Isaac is horribly buggy right now. If you could open an issue for a custom voice at [Project-M-CC/isaac](https://github.com/Project-M-CC/isaac/issues), that would be appreciated.
