### ISSUE TITLE
URGENT: Mewtwo vs. Kirby freezes the game

### ISSUE THREAD

**Issue by bungholemaster** [TheOriginalSINe/Project-M-CC#44]

**Comment by MrGameCrazy** [comment]
Just saw that happen on my end. I wonder what's causing that issue.

**Comment by MiRIr** [comment]
I just tested and found that no other character has this issue.

I imagine Kirby's Mewtwo ability was removed/altered/moved by accident. Hopefully this will be a relatively easy fix.

**Comment by ewmb7701** [comment]
I believe this is something wrong with the Kirby Mewtwo movset.

**Comment by jgd124** [comment]
I'm guessing the simplest resolution would be simply to revert Kirby to his 3.6 moveset.

Unless, that is, we want to commit to creating a balanced Kirby copy-ability moveset.

**Comment by bb010g** [comment]
:+1: for reverting Kirby back to 3.6. We can work with new character interactions later.

**Comment by ewmb7701** [comment]
This got fixed when we reverted to 3.6. Closing issue.
