### ISSUE TITLE
Snake is missing special box taunt movements from Halloween build

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#45]
Title. The announced abilities for Snake to endlessly stay in his box and crawl in it are in the Halloween build, but not in our GitHub one.

**Comment by thesmashking25** [comment]
When was this announced

**Comment by ghost** [comment]
Not announced, but definitely a feature that someone pointed out on reddit. It exists in the Halloween build.

https://www.reddit.com/r/SSBPM/comments/3v61mb/my_one_wish_for_36g/

**Comment by jojmaht** [comment]
Reminder to close this issue when #64 is merged.

**Comment by ewmb7701** [comment]
Issue resolved during 3.6.1 update. Closing issue.
