### ISSUE TITLE
Bowser's Castle Stage Icon Error

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#46]
The regular and alternate versions of the Bowser's Castle stage icon are not in the right places. Please switch them around to reflect the actual version of the stages as shown in the video below. 

https://www.youtube.com/watch?v=O7pPKC3uJiw

Note: The first time I chose the stage is the regular version and the second time I chose the stage is the alternate version.

**Comment by ghost** [comment]
I actually swapped the preview banner with the one from the Halloween build to show the legal version as the main stage, but I have yet to figure out how to create a pull request. It's definitely fixed though.

**Comment by MrGameCrazy** [comment]
Thanks for the info.

**Comment by bb010g** [comment]
@JekyllMD GitHub has a guide [here](https://help.github.com/articles/creating-a-pull-request/) on pull requests and a Git cheatsheet [here](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf). Also, the [Git book](http://git-scm.com/doc) is a good resource.

**Comment by ewmb7701** [comment]
Fixed this issue. Closing.

**Comment by bb010g** [comment]
Is this fixed as in banner fixed, or fixed as in reverted to 3.6? (I'm personally for banner fixed, because it allows for nicer random.)

**Comment by ewmb7701** [comment]
Fixed as in "I switched the legal stage to the default stage and updated the stage previews to reflect that".

**Comment by JCOnyx** [comment]
Cool, this is the one thing that shouldn't have been reverted back to the 3.6 standard.  Multiple PMDT members said that the competitive version was supposed to be the main stage for the full release but they messed up and forgot to switch it around.
