### ISSUE TITLE
Fairy Wing Jiggs Crash

### ISSUE THREAD

**Issue by Hellraz0r** [TheOriginalSINe/Project-M-CC#47]
Picking Jiggs's fairy wing costume crashes the game when loading into battle.

**Comment by ghost** [comment]
For me this does not happen. Tested in Dolphin with Jigglypuff versus Mario on Final Destination.

**Comment by AJ3450** [comment]
This happens on the netplay build too. Long time known bug with the skin. Only seems to happen in dolphin.

**Comment by ewmb7701** [comment]
I suggest that we ignore this until a fixed can be determined.

**Comment by ghost** [comment]
I updated my earlier comment to specify that I tested it in Dolphin.

**Comment by Hellraz0r** [comment]
Weird. What are your Dolphin settings? Direct3D or OpenGL? Per Pixel lighting on/off? It has something to do with vertex shading.

**Comment by bb010g** [comment]
Also, what build?

**Comment by ghost** [comment]
OpenGL, per pixel lighting off. Dolphin 4.0-6492.

**Comment by Hellraz0r** [comment]
Hm. Crashes on both OpenGL and Direct3D for me, on Dolphin netplay build 7840 (Smashladder standard).

**Comment by ghost** [comment]
The PM build I used was this dev build completion, and not a Dolphin netplay build.

**Comment by bb010g** [comment]
I believe he's saying that he used build 7840, the preferred SmashLadder build for netplay purposes. He was testing this PM build.

**Comment by Hellraz0r** [comment]
Yeah. Dolphin 4.0-7840 is the standard for netplay on Smashladder. I use it for the Wii U adapter native support. Interesting discrepancy though.

**Comment by bb010g** [comment]
4.0-8299 on Windows 10 with Direct3D gives a VertexShaderGen issue. Doesn't crash Dolphin, but it's unplayable and will crash if you tell it to not ignore.

Checked over on #dolphin-dev and they know about the issue and already have it on FifoCI to see if a PR fixes it. I'll keep an eye out for when it's fixed there, but we can't do anything. Request for closure.

**Comment by ewmb7701** [comment]
Closing issue, it's out of our hands.
