### ISSUE TITLE
Lyn: Bair lacks landing lag

### ISSUE THREAD

**Issue by theroy734** [TheOriginalSINe/Project-M-CC#48]
Lyn's bair does not currently have any landing lag. http://www.gfycat.com/PlaintiveCrispAmazondolphin
I suggest adding somewhere between 20-23 (not L-canceled) frames of lag as a starting point.

**Comment by ghost** [comment]
I feel that bug fixes should be complete before we even consider balancing the new characters to our liking

**Comment by ghost** [comment]
an aerial completely lacking landing lag is kind of an important issue. How much landing lag it should have is where the balancing issue comes in.

**Comment by ghost** [comment]
We should still give bug fixes priority though

**Comment by bb010g** [comment]
I kinda want to see how this plays out with no landing lag for a while. If it works alright, we'll know to not give it much.

**Comment by ghost** [comment]
Her not having landing lag for a move is a large enough issue to be considered a bug. Like if the hitboxes of a move werent connected to the animation. This obviously wasnt a balance design choice on PMDTs part. Especially seeing as her bair is one of her main kill moves.

**Comment by JCOnyx** [comment]
If we're going to be giving her Bair a landing animation, I'd recommend looking into ZSS's frame data on her Bair because they share a pretty similar function and the 2 are pretty similar design wise.

**Comment by ewmb7701** [comment]
I agree that her bair should be given some kind of landing lag. Clearly it needs some.

(Also, IMO, Lyn is OP. But that's just me)

**Comment by ghost** [comment]
ZSS bair is not disjoint, has less range, and less knockback. It has 16 frames of landing lag. 

The two most similar moves I can think of are Ike and Roy's bairs. They have 19 and 23 frames of endlag respectively.

Lyn's fair, dair, and uair have 14, 17, and 19 frames of landing lag respectively. Her bair has more knockback than the rest of the moves but less active frames.

 I think @theroy734 s estimate of 20 to 23 frames was a good ballpark.

**Comment by ghost** [comment]
Further research: Lyn's Bair does 18 damage sweetspotted. This is more than any of the other aerial swordsman attacks. It also kills at a slightly lower % than Roy's sweetspotted Bair.

I suggest 23 frames, the upper end of the landing lag assessment, would be the best bet.

**Comment by ghost** [comment]
someone on the Discord chat was able to give the move actual landing lag.

**Comment by ghost** [comment]
Yea I'm pretty sure that's Hobbes working on a lot of her moves right now. Unless you mean someone else?

**Comment by ghost** [comment]
I meant Hobbes, yeah.

**Comment by bb010g** [comment]
3f2e31c changed:

> Bair:
> No longer is autocancelable at any frame
> Landing lag: 20 > 23
> hitbox 1/2/3 damage 18% > 16%

Credit to @ArtfulHobbes.

**Comment by somealternateaccount** [comment]
Pretty sure this has been resolved following the recent Lyn changes. Testing should take place to ensure that her back-air has the proper amount of landing lag with and without L-cancelling.

**Comment by ghost** [comment]
Tested. Was changed to 23 frames and I think it was 11 frames L canceled. Damage was reduced to 16 and KBG was compensated to kill at the same % as it did before the damage nerf.

Closing.
