### ISSUE TITLE
Question: Should all movesets and stages be reverted to 3.6?

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#49]
The more that I think about it, the more sense that it makes that we should revert all movesets and stages to 3.6 (barring bugfixes like Link and Yoshi). My reasoning for this is as follows: 
- We don't have the official patch notes
- The 3.6 meta is worth preserving
- The patch will be more accepted by the community
- 3.6 was relatively bug free

All art and cosmetics, will, of course, be kept. I was just wondering what the general feelings about this were.

**Comment by jgd124** [comment]
I'd be about that. 

If I recall correctly, it was pretty much the general consensus aside from the occasional Bowser main.

For me personally, it would be a bit nicer because I still want to play at my local weekly without getting all confused.

**Comment by Hellraz0r** [comment]
I think it's a fine thing to do. I was really confused when I saw Roy's old bair. It'd feel more consistent to have this be essentially bugfixed 3.6 + characters and shinies.

**Comment by ewmb7701** [comment]
I think that more concise patch notes can be created, that it needs to be reverted to 3.6. Afterwards we can make an alternate version for those that want it.

**Comment by JCOnyx** [comment]
I'm all for just bugfixes and cosmetics to the 3.6 cast.  But I'm assuming you're planning on keeping the new characters?  Otherwise this would just be another 3.6CE.

**Comment by jgd124** [comment]
^What's wrong with having the characters now? Isn't that one of the explicit goals of the project?

**Comment by bb010g** [comment]
LGTM. It's a huge plus for us to have the same meta as 3.6 proper, just with bug fixes, art, & Knuckles.

**Comment by oXMugetsuoXo** [comment]
Reverting back seems like the best route to go. Would save some time from trying to find every characters changes and would look better presented to the community. As long as the new characters stay and yoshi/link have their bugs fixed im all for it.

**Comment by ewmb7701** [comment]
Reverted back to 3.6, closing issue.
