### ISSUE TITLE
Lyn: Down Special

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#5]
Lyn's down special does nothing currently
Clearly it was intended to be a counter

Suggested Fix:
Copying Marth's counter onto Lyn and tweaking the knockback and damage

**Comment by jojmaht** [comment]
The inactive frames should be shortened too.

**Comment by ghost** [comment]
Wouldn't it be best to just keep Marth's KB and damage? Either that or average the counter's KB and damage of all the other FE characters.

**Comment by jojmaht** [comment]
If we were to keep it that long, maybe we could actually make it more powerful. High risk, high reward.

**Comment by ewmb7701** [comment]
Someone already fixed it and gave me permission to upload it. Closing the issue. 

Re-balancing will be done later. I really do like the idea of making it short but strong, as it fits into Lyn's quickdraw style.

**Comment by JCOnyx** [comment]
https://www.youtube.com/watch?v=wf7F9W0cW20

Looks like Kitsu released a fix that reverts Vantage back to it's leaked video form.  I'm going to test it now, but I think the only issue is how powerful it is.  In the leaked video a grounded sweatspot did 16 damage, but it looks to be doing 24 in this video.  Just a minor thing really and doesn't have to be changed right away.

**Comment by ewmb7701** [comment]
Cool, thanks for the headsup. I'm gonna test it with my friends right now. Might implement it in the next build.

**Comment by bb010g** [comment]
I like the red trails on strong attacks Kitsu put in there too. It's a nice touch.

**Comment by JCOnyx** [comment]
Works like a charm on my end, the weird sword trail problems in the taunts don't exist with this version either.  Still think the damage could be toned down a bit, especially since you can follow up after the stun on a successful sweatspot on occasion.  16 like the leaked trailer sounds good, but anywhere from 14-18 sounds reasonable.
