### ISSUE TITLE
Stock Icons

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#50]
The way PM works is that is has copies of the set of stock icons in multiple places. In this build, just about all of them except the one in sc_selcharacter are out of date and have incorrect textures for Knuckles, Lyn, Awakening Roy, ZSS, and possibly a few others. These copies are in the info_(filename) files, and StockFaceTex.brres.

**Comment by JCOnyx** [comment]
They're also in the STGRESULT.pac as well.  Not sure if those have been updated.

**Comment by ghost** [comment]
Assuming that the new characters all point to the correct stocks, the only stock that's missing from STGRESULT is PED Suit Samus' one, which will only be necessary once we figure out how to add a costume slot for the costume to be usable.

**Comment by ewmb7701** [comment]
I updated them in STGRESULT.PAC. When I did it was a sloppy fix, I'm working on that soon.

**Comment by ewmb7701** [comment]
I looked through the files, and it seems like the info_X.pac files from 3.6 don't even use stock faces. I did update the the StockFaceTex.brres files though. I want to commit the changes, but I'd like confirmation that they actually matter.

**Comment by jgd124** [comment]
Re-posting a possible fix from another thread. http://smashboards.com/threads/knuckles-lyn-and-isaac-stock-icons.425088/

This is the most current download for his fix: https://www.mediafire.com/?5mc3fsgda1s91e3

Known issue: Classic mode icons do not redirect properly.

**Comment by ewmb7701** [comment]
I messaged that user and asked him if he'd like to contribute his stock icons to the project. I also made a post on Smashboards about the project in general.

Edit: Wow they immediately removed the topic. What a bunch of butthurt dbags.

**Comment by bb010g** [comment]
/u/applesandgrapes put together a Sami stock icon [here](https://www.reddit.com/r/SSBPMCE/comments/3vlqtt/everything_sami_needs_for_the_css/cxosc3i) for general use.

**Comment by jgd124** [comment]
@TheOriginalSINe  Wow. That was quick. Fear, fear, fear.

**Comment by ewmb7701** [comment]
@jgd124 Yeah it was Strong Bad the deleted it. He said "only explicitly user created content" yet probably locked the exact same thread we're talking about with the stock icons, even though it had "exclusively created content". 

Also @bb010g, I don't think we should worry about Sami for now. We first have to figure out how the Clone Engine works and then add Sami into her own slot, if we were even going to add her. Still though, it's good to have options for the future.

**Comment by ghost** [comment]
Hello, I sent an Imgur link with stock icons I made for Knuckles and Lyn to the SSBPMCC subreddit and  bb010g recommended I post these here.

http://imgur.com/a/RHYMW

I hope this helps you.

**Comment by skinnyfoetusboy** [comment]
@ghost Your imgur link redirects to 404.

**Comment by ewmb7701** [comment]
@ghost That link is a 404. Mind re-uploading them?

**Comment by ewmb7701** [comment]
Stock icons operating fine, closing the issue.

**Comment by bb010g** [comment]
@TheOriginalSINe For future reference, @ghost is the account displayed when someone deletes their account. Although the Octocat ghost is pretty neat looking.
