### ISSUE TITLE
Super Knuckles missing

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#55]
When he uses his Final Smash, Knuckles becomes Super Sonic. I made a functional fix for it, but i'd need someone else's help to give it it's distinct glow.

**Comment by archedmaid** [comment]
A suggestion, if possible would it be better to make his Final Smash some thing similar to Wario Man?

**Comment by ghost** [comment]
From a technical standpoint it's impossible (as of now) to convert it into a transformation with a full moveset.

**Comment by ghost** [comment]
This was implemented with the Knuckles fixes, but still could use it's glow. Maybe this issue should be closed.

**Comment by ewmb7701** [comment]
Closing issue, although Hyper Knuckles needs a few fixes before he's "complete".
