### ISSUE TITLE
Previously Resolved Bugs

### ISSUE THREAD

**Issue by jgd124** [TheOriginalSINe/Project-M-CC#56]
Since we're reverting back to 3.6 versions of certain characters and stages, I thought I should post a list of the relevant known bugs from narpaz_sword's old bugfix threads.

Perhaps when most of this is said and done, we can split these up into different issues, but for now, this is a reference.

MOST RELEVANT-
- Ice Climbers getting hit with Diddy's peanut during side-b causes free-fall (unresolved at time of DEV Build) 
  [http://smashboards.com/threads/ice-climbers-diddy-peanut.410372/]
- Captain Falcon: Grounded Falcon Kick hitbox error 
  [http://smashboards.com/threads/captain-falcon-falcon-kick-hitbox-error.407662/]
  [Apparently the damage or knockback numbers were 11,12,13 when they should not have been? I recall one of the DT in the thread saying that it was a "clerical error" when they input the numbers into 3.6]
- Olimar's Yellow Pikmin Up-Smash Hitbox is lower than Red Blue & White's
  [http://smashboards.com/threads/pm3-6-olimars-red-flower-usmash-is-smaller-than-leaf-bud.420497/]
  [I also saw a few bugs related to his grab? I can't even remember what they were.]
- Bowser Ledge-grab teleport glitch
  [http://smashboards.com/threads/pm3-6-bowser-teleport-glitch-when-grabbing-ledge.414476/]
  [https://youtu.be/VjqxZL697Rk?t=2m12s]
  [https://www.reddit.com/r/SSBPM/comments/3oa4kt/exploring_the_ledge_glitch_instant_release_bug/]
- Charizard doesn't get his glide back under certain conditions
  [http://smashboards.com/threads/charizard-doesnt-get-his-glide-back-in-certain-conditions.364174/]
  [ I can't even remember all of which conditions. The two that I know were "After he performs one in the air or if he lands with SideB". Was almost definitely solved for the Halloween Build that's for sure. This was an earlier post in 3.6's lifespan and they found a fix near-immediately.]
- ~~Many errors related to Bowser's Castle Comp.'s floor~~ (Resolved using 3.61 version of Bowser's Comp.)
  [http://smashboards.com/threads/pm3-6-ganon-can-fall-through-the-floor-on-competitive-bowsers-castle-after-respawning.421166/]
  [https://www.reddit.com/r/SSBPM/comments/3pleir/bug_a_ganon_in_the_player_2_spawn_position_can/]
- ~~Link's grab issue.~~ [Resolved using Link v. 3.6.1]
  [https://www.reddit.com/r/SSBPM/comments/3hetol/links_broken_grab/]
- Yoshi's Shield Unresponsive After Rolling [May be resolved as we are using Yoshi v. 3.6.1]
  [https://www.reddit.com/r/SSBPM/comments/3v5mgn/a_plea_for_closure/cxkkg95]
- Yoshi's Unshieldpokable Shield is Shieldpokable [May be resolved using Yoshi v. 3.6.1]
  [https://www.reddit.com/r/SSBPM/comments/3v5mgn/a_plea_for_closure/cxkkg95]

LESS RELEVANT
-  Wolf Freezes after being hit by Roy's Final Smash
  [http://smashboards.com/threads/pm-3-6b-frozen-wolf-after-roy-final-smash.410159/]
  [https://www.youtube.com/watch?v=MNXdzENOqvY]
  [One of the DT in the thread noted that the mechanics of this glitch were very similar to the timer issues of 3.02.]
- Yoshi's Island (Brawl) can force grab releases (A long-standing issue.)
- Visual errors with some costumes on Delphino Plaza (A long-standing issue.)
- Most in game items act as Links Hylian Shield vs projectiles.(A long-standing issue.)
- Various stock icon issues in both all-star and classic modes. 
- All-star mode results show the incorrect result when both players die as match ends. 

EDIT: FUCK. I SHOULD HAVE TAKEN SNAPSHOTS. They just killed the bug report threads right after I made this so the Smashboards links go nowhere. Looks like you're just going to have to trust me as this is now the last collected record of most of the major 3.6 bugs.

**Comment by oXMugetsuoXo** [comment]
The ice climbers thing i reported myself. Ive found out its not diddys peanut. If one of them is hit during side B the problem occurs.

**Comment by Jeelix** [comment]
It's a great thing you made this post before the they got deleted. This is a good list of bugs to work on. It sucks that the original posts were deleted, but at least there is this.

**Comment by jgd124** [comment]
@oXMugetsuoXo Is it if they're hit by anything or just by a solid projectile?

**Comment by oXMugetsuoXo** [comment]
Sorry im not sure. Think its just when one climber is hit and not the other. Have a friend coming over to play soon I will try to reenact it.

**Comment by jgd124** [comment]
Re: Bowser's ledge glitch. Narpas_sword just said that it this glitch affects:
- 3.6 Metaknight when he hits ledge out of side-b.
- 3.6 Bowser when in tumble animation.
  [https://www.reddit.com/r/SSBPM/comments/3vp4f6/i_feel_so_bad_for_link_mains/cxpjf5c]

Perhaps it would be good to see if either of the updated versions of those characters have a fix for that implemented.

**Comment by bb010g** [comment]
That thread also showed Yoshi had some issues too.

**Comment by jgd124** [comment]
Bowser's Castle Competitive confirmed resolved in issue thread
https://github.com/TheOriginalSINe/Project-M-CC/issues/100 .

**Comment by ghost** [comment]
For some character bugs (Yoshi for example) we really need to be careful about just using their entire 3.6.1 moveset.

 As we are using 3.6 as a base and trying to preserve the meta with this build, we don't want to include any balance changes that may have been in 3.6.1

If at all possible, in the event of a bugged move, only that move should be copied over from the 3.6.1 build

**Comment by jgd124** [comment]
@Azuran17 I am in 100% agreement.

However, afaik we still have no frame-data comparison on Yoshi, Link or any other character from versions 3.6 to 3.6.1 so we don't know exactly what was changed. This is the easy temporary fix until your way is implemented.

**Comment by ghost** [comment]
@jgd124 the 3.61 changelog leaked like 10 minutes ago :p so that solves that

**Comment by jgd124** [comment]
@azuran17 Can I get a link to that? 

EDIT: It's right here: https://dl.dropboxusercontent.com/u/143448524/3.61%20Changelist.zip

**Comment by somealternateaccount** [comment]
Pretty sure this has been resolved. Ideally a diff would occur between the 3.61 and 3.6 files to ensure that all of the files are in the right place.

**Comment by jgd124** [comment]
Yup. Just rechecked. Most of these were fixed. A couple of these are inherent problems in Brawl's engine.

Closing the thread.
