### ISSUE TITLE
Announcer: Knuckles

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#6]
Knuckles's announcer says "stage clear"

Suggested Fix:
Modify the announcer call offset to point to an unused clip and replace it

**Comment by zombiejerky** [comment]
How about knuckles theme pumpkin hill zone loop theme replacing sonic boom

**Comment by bb010g** [comment]
We are not doing music changes.

**Comment by ghost** [comment]
Knuckles has an announcer call now, although it may be changed moving forward. Should I close this issue?

**Comment by bb010g** [comment]
Did we fix it so the actual Stage Clear isn't Knuckles?

**Comment by ghost** [comment]
No, and IIRC that clip never gets used to begin with.

**Comment by ghost** [comment]
I'm pretty sure the one we have will not be the final version, so we still need to somehow create a new call. I suggest leaving it open.

**Comment by treyenma** [comment]
I'd be happy to record some announcer calls for the newer characters and the older ones sometime, if someone else knows how to set them to appropriate .sawnd files.

**Comment by Awsoman62** [comment]
It's complete

**Comment by ghost** [comment]
@treyenma I know how to set them to the appropriate sound files, and some others on the Discord chat do. As far as trying out to be an announcer goes, show us what you've got there.

**Comment by Awsoman62** [comment]
Isn't it already complete?

**Comment by cimpyhigh** [comment]
Shouldn't this be closed?
