### ISSUE TITLE
3.61 Snake

### ISSUE THREAD

**Issue by Eltrion** [TheOriginalSINe/Project-M-CC#61]
Are there any significant balance Differences that would prevent the use of 3.61 snake?

If not is it possible to use 3.61 snake for the walking box taunt? Or is it a code set issue?

**Comment by ghost** [comment]
I think right now, none of us know what nerds or buffs are present in 3.61, so we're sticking to 3.6 to keep all characters the same

**Comment by Eltrion** [comment]
Alright, fair enough. Is walking box snake re-implementation within the scope of this project?

**Comment by ghost** [comment]
That it is. we're just trying to avoid tossing in unknown balance changes along with it.

**Comment by Eltrion** [comment]
Okay. I suppose this should be in the Release milestone then.

**Comment by ewmb7701** [comment]
I can't seem to get the walking box taunt to work. Has anyone gotten it to work on their setup? Is it present in the codeset?

**Comment by ghost** [comment]
it's just in the FitSnake(PSA file0 and FitSnakeMotionEtc(animation file) fromm the Halloween build. i just copy-pasted those two into our completion build and it worked fine.

**Comment by ghost** [comment]
As a note, here's how it works. Down taunt starts it, and staying still just has snake sit in the box forever, but moving left or right while in it has him move, while using up taunt(I think) removes the box.

**Comment by ewmb7701** [comment]
Oh okay. If that's the case then we just need to open up his moveset in PSA and copy and paste the codeset over from the Halloween Build into the 3.6 one.

**Comment by Eltrion** [comment]
Keep in mind you move left or right using the DPad, not the Thumstick.

**Comment by Bngmn** [comment]
Can anyone upload the files to make snake use his walking taunt move. Please!:)

**Comment by ewmb7701** [comment]
This issue was resolved. Closing.
