### ISSUE TITLE
Shiny Pokemon are missing sparkle effects on entrance

### ISSUE THREAD

**Issue by UieSolverofThings** [TheOriginalSINe/Project-M-CC#62]
In the halloween build, the shiny alts for all of the Pokemon characters had special sparkle effects when entering the stage. These were lost when back-porting to 3.6

Solution: Pointed out in #57 , the sparkles seem to be GFX calls in the moveset. Re-adding them shouldn't prove too difficult.

Working on my own fix now.

**Comment by bb010g** [comment]
Request for closure. This should be fixed with the switch to a 3.61 base.

**Comment by ewmb7701** [comment]
Resolved in update, closing.
