### ISSUE TITLE
Lyn: F Smash Hitboxes

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#66]
For the duration of the move, Lyn's Hitboxes lag behind her sword animation. This puts them too far in or out of the Z Axis on certain frames and makes the move unreliable.

Suggested Fix: adjust hitboxes so they follow lyn's sword for the duration on the move.

**Comment by JackCandles** [comment]
Would this proposed change make is so she no longer whiffs on F-smash when standing close to an opponent? LIke, is that why it misses in that case? Definitely annoying. Seems like a few of her moves have this weird Z Axis problem.

**Comment by ghost** [comment]
@JackCandles I'll have to test again to confirm but I don't think so. There are a few frames of dashing forward before any hitboxes even come out, so that may just be what the move is like.

**Comment by ghost** [comment]
@JackCandles Just confirmed, the wiffs are just the nature of the move, the hitboxes appear after she dashes. Unrelated to misplaced hitboxes. It just requires proper spacing.

**Comment by JackCandles** [comment]
@Azuran17 Cool, thanks. I certainly don't mind a move that requires good spacing, as long as it's not a bug I can live with it :)

**Comment by ewmb7701** [comment]
Determined to not be  bug, closing.

**Comment by ghost** [comment]
@TheOriginalSINe this is still a bug and should be reopened. The hitboxes don't match the animation.

Jack was asking if her wiffing FSmash at close range was a bug, which it is not. It's just how the range of the move works.

**Comment by ewmb7701** [comment]
My bad, sorry. I misunderstood the issue.

**Comment by ghost** [comment]
Further investigation suggest this design was intentional. The positioning of the hitboxes seem to be done to "shorten" the active frames of the move. Closing.
