### ISSUE TITLE
Lyn: Up Tilt Hitboxes

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#67]
There are no hitboxes on the spin portion of the move between the first and second hit. Unsure if this is intentional or not, but the two hits don't often reliably link. This may be the cause.

Suggested fix: Add weak hitboxes to spin portion of move that send opponent forward.

**Comment by SzionBlue** [comment]
Same, I thought there would be 3 hits..

**Comment by somealternateaccount** [comment]
Comments in the discord suggested that this may have been added. Testing needed to verify no change has yet been made, and discussion should take place as to whether or not there should be a change.

**Comment by SzionBlue** [comment]
I played yesterday on campus with the boys, none of us saw a 3rd hit or a spinning multihit or any change of any sort

**Comment by ghost** [comment]
No changes have been made as of yet.

**Comment by ghost** [comment]
In the spirit on avoiding any unnecessary balance changes, this will be considered intentional design and left alone. Closing.

**Comment by bb010g** [comment]
I think the fact that the sword spins with no hitboxes and doesn't link is enough to take it as possibly a problem. We know Lyn already had problems (bair, arrow, Vantage).

**Comment by Grangach** [comment]
i agree it could use a third hit for the spin.

**Comment by KymaeraK1ng** [comment]
Yeah, a third hit would be better.

**Comment by DestinyHiro** [comment]
I'm surprised nobody brought this up again, I guess I'll work on it with the rest of my Edits to Lyn (2.6 jab, extended frames on F-air, etc.).
