### ISSUE TITLE
Lyn: Second Jab Hitbox

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#68]
Lyn's second jab (the kick) animation isn't covered by hitboxes. This may be due to the move being WIP as evident from the choppy animation.

Suggested Fix: extend the current hitboxes to cover lyn's foot.

**Comment by JackCandles** [comment]
+1 to that. As soon as I pulled up Debug Mode with Lyn that kick hitbox really stood out. I think it's actually shorter than the punch hitbox.

**Comment by ghost** [comment]
@JackCandles it is :lollipop:

**Comment by aFracture** [comment]
What are peoples' thoughts on using the 2.6 build's jab? Off the top of my head I can't think of any other attack move that she does that doesn't user her sword (besides Neutral-B, obviously). So her jab string being a punch-kick doesn't feel right. The 2.6 jab is a double sword slash, which fits better with her overall moveset.

**Comment by ghost** [comment]
Well on one hand, using those would save time and effort on fixing the current jab hitboxes and animations. On the other hand, PMDT scrapped the old jab for a reason, even if we don't know what it is. Undecided on this.

**Comment by JCOnyx** [comment]
Can anyone post a gif of 2.6 jab?  Hopefully with debug on so we can see the hitboxes.

**Comment by bb010g** [comment]
@DestinyHiro I know you were working on this before you had to take time off, but could you get your current work uploaded somewhere or at least passed off to someone else so this can be finished?
