### ISSUE TITLE
Announcer: Lyn

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#7]
Lyn's announcer is silent

Suggested Fix:
If the announcer call offset is set to a silent clip, replace the silent clip
Modify the announcer call offset to point to an unused clip and replace it

**Comment by YunSF** [comment]
Are you planning on using just a separate announcer for lyn, knuckles, and Isaac, or redo all the the other characters too for consistency?

**Comment by ewmb7701** [comment]
I think I'm going to have to redo all of the announcer files for consistency.

**Comment by ghost** [comment]
How many unused clips are there available? It would be nice to make Isaac and Knuckles have proper announcer calls.

Also, how are you going about making the new announcer clips?

**Comment by jojmaht** [comment]
I'd suggest we take submissions and then sort it out via some kind of a vote. Or better yet, ask the current PM announcer.

**Comment by ewmb7701** [comment]
I've had a few people message me about being the announcer. We could take auditions and see who the best is. And I did consider contacting the official announcer, but I hadn't gotten to that yet. That would probably be the easiest thing.

**Comment by bb010g** [comment]
[**@skinnyfoetusboy**](https://github.com/skinnyfoetusboy) commented on [Dec 3, 2015, 3:31 PM PST](https://github.com/TheOriginalSINe/Project-M-Dev-Build-Completion/issues/7#issuecomment-161823253):

> I'd suggest we take submissions and then sort it out via some kind of a vote. Or better yet, ask the current PM announcer.

:+1: for getting the current announcer. He wasn't PMDT, so he should be fine. I'm pretty sure he's Blakinola. You can contact him on [Reddit](https://www.reddit.com/user/blakinola) or [his website](http://www.blakinola.com/contact/).

**Comment by ghost** [comment]
kane junglebluth murray. I emailed him.

**Comment by bb010g** [comment]
The previous poster's account is now deleted, and I couldn't find a "Kane Junglebluth Murray" anywhere online. Does anyone know who the PM announcer is?

**Comment by bb010g** [comment]
Sorry for the double post. Turns out that they misspelled his name: Kane Jungbluth-Murry. He's on [YouTube](https://www.youtube.com/channel/UCgAAWCTQoOvjYZNgxo_6fiA) & [Google+](https://plus.google.com/104688761023001740857). I'll contact him tonight.

**Comment by bb010g** [comment]
Found his email address and sent him an email. Hopefully he responds to that.

**Comment by JackpotSHUnited** [comment]
There's always the Project Monolith guy if the 3.6 announcer doesn't do it.

**Comment by ghost** [comment]
So we have announcer clips for Knuckles and Lyn now, although it's possible that they'll be replaced in the future. Should I close this issue?

**Comment by bb010g** [comment]
I wouldn't until we get a response from Kane.

**Comment by ghost** [comment]
Any response from Kane? The current announcer sounds acceptable in the event that we aren't able to get new lines recorded.

**Comment by ghost** [comment]
So we've had no word back from Kane AFAIK. Hope you guys pardon the poke, but permission to close the announcer sfx issue entries?
