### ISSUE TITLE
Lyn: Black Costume Skin Tone

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#70]
On Lyn's black costume, her upper body skin tone is much darker than her leg skin tone.

Suggested Fix: lighten her upper body skin tone to match the color of her legs and all other costume's skin tones.

**Comment by oXMugetsuoXo** [comment]
I actually enjoy using that Lyn. Maybe we can match her legs with her upper body instead for this specific costume?

**Comment by Kosyne** [comment]
I'm pretty sure the dark skin on the upper body is intentional for that costume. It matches too well with the outfit and accents to be an accident. If anything, the legs should probably be darkened.

**Comment by ghost** [comment]
Her skin tone should not change from costume to costume, especially if they aren't alts. The inconsistency doesn't portray polish.

The likely explanation is whoever was making the costume color darker and black accidentally applied the change for more than just the dress.

**Comment by Kosyne** [comment]
Consistency does not imply polish. Plenty of alts have the odd one out (Falco's one dark one, olimar's dark skin, daisy/peach, etc etc).

Anyway, the coloration seemed too deliberate to be an accident, so I decided to look into the texture files. Looking at the texture in question 'LynFace', you can see a visible outline of where the color adjustment effect is applied (adding a bit of red, upping contrast a bit, etc), and you can see that it targets the skin specifically.

Here is Blue Lyn's face texture:
![lynfaceblue](https://cloud.githubusercontent.com/assets/356616/11766732/0ad87eca-a15a-11e5-9722-0a0a39514cb3.png)
Black's:
![lynfaceblack](https://cloud.githubusercontent.com/assets/356616/11766729/0ad4dc70-a15a-11e5-9fef-0bdd0199ab4f.png)
Black's with the effect's region highlighted:
![lynfaceblackregion](https://cloud.githubusercontent.com/assets/356616/11766819/be0a4566-a15d-11e5-9d69-24b0dc0a54d4.png)

From that, I think it's safe to say that that alt's skin is intended to be darker.

Also, fun fact, it seems Lyn's alt skin's all use a different version of the face texture. Thinking that it's a WIP update of her skin. Here's the original base skin for reference. Notice the lips and arm/elbow texture.
![lynfacebase](https://cloud.githubusercontent.com/assets/356616/11766731/0ad748de-a15a-11e5-8afe-fdb873a5288c.png)

**Comment by oXMugetsuoXo** [comment]
Regarding the "skin tone not changing from costume to costume" Immediately two that come to mind are wolf/olimar. It has already happend before and i doubt Lyns was an accident.

**Comment by ghost** [comment]
The textures back up what you are saying. I'll merge the pull request.

**Comment by ghost** [comment]
Issue solved and merged. Closing.

**Comment by bb010g** [comment]
Closed in #162.
