### ISSUE TITLE
Is diddy.zip supposed to be present?

### ISSUE THREAD

**Issue by zziccardi** [TheOriginalSINe/Project-M-CC#72]
This is more of a question than an issue, but is /projectm/pf/fighter/diddy.zip intended to be there? I'm assuming not, since the files contained therein seem to be duplicates of those in the diddy folder and the .zip isn't in the 3.6 build.

**Comment by ewmb7701** [comment]
They are not; I deleted them. The file patch code cannot even access them, so they were just adding to the download size. Issue closed.
