### ISSUE TITLE
Knuckles New Dtaunt

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#76]
Knuckles New down taunt has no sound. I recall from this video a little after 1:40 his down taunt says "No Contest" .

http://www.youtube.com/watch?v=cZAuKvIrrZM&t=1m40s

**Comment by ghost** [comment]
Does his old down taunt from the PM dev build have a voice clip assigned to it? If so, it's just a matter of making the sound get called for earlier(the new animation is shorter IIRC, so the current call may be after the animation ends).

**Comment by Jorge-SunSpirit** [comment]
From the dev build the sound Knuckles used was a copy of Sonic's voice clip. Either they can use another voice clip or add new SFX for knuckles.

**Comment by MadoKage** [comment]
What if we make this his Down-Taunt

Doesn't matter if he crouching or standing

http://i.imgur.com/bCC7177.png

**Comment by bb010g** [comment]
Ooh. That would be neat if we could pull it off. It would go well with looping.

**Comment by chickangamer** [comment]
Why is it closed

**Comment by bb010g** [comment]
Didn't we had given him a new dtaunt animation along with the sound effect?

**Comment by vinegar97** [comment]
It was only slightly updated by @thecoolguy, it's not a whole new animation.

**Comment by bb010g** [comment]
_Insert Chillindude face here_
