### ISSUE TITLE
Lyn Vantage

### ISSUE THREAD

**Issue by oXMugetsuoXo** [TheOriginalSINe/Project-M-CC#77]
If you land vantage critical and then once the opponent is sent flying you follow up quickly with another vantage critical midair there is no knockback or critcal. Damage is still done however.

**Comment by JCOnyx** [comment]
This probably has to due with how you can't follow up a stun with another stun, a la ZSS.  It's working as intended although it does look odd.

**Comment by oXMugetsuoXo** [comment]
Ah true. Just feels odd seeing her slash. Guess zss never felt that way because shes not hitting physically. Nvm then thnx for clearing this up.
