### ISSUE TITLE
Knuckles Final Smash Freezes in Invisible Brawl

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#78]
Title. Since the PM devs forgot to make a copy of FitSonicFinalSpy, Knuckles' final smash crashes when Invisible Brawl calls for it. Today i'm going to make a fix for 64 mode, which was meant to replace Invisible Brawl.

**Comment by ewmb7701** [comment]
Did you ever get this fixed.

**Comment by ghost** [comment]
I made a 64 mode fix, which looks buggy in Dolphin. Can't test it on real hardware to see if the texture bugs out there.

**Comment by Blueturtle21** [comment]
@Rage17 I can test the fix on my wii if you want.

**Comment by ghost** [comment]
@Scottam https://www.cubbyusercontent.com/pli/64%20Models.rar/_ae9409794ce74ac1a0447cd5af3b9974

**Comment by ghost** [comment]
This was fixed again with the newest PR.
