### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by jojmaht** [TheOriginalSINe/Project-M-CC#80]
I created a Discord server so that we can have more immediate discussions about passing subjects as Github Issues are not really made to do that.
This way, we can really focus on specifics subjects and have internal conversations between contributors instead of polluting issues.
(this also means that those of you who can't create a Pull Request can ask me 24/7 :'D)
Of course, having a Discord server doesn't mean all discussions will go down there, we will still use Github as the primary issues and technical matters tracker. Every other discussions will take place in the Discord server.

Anyway, the address is https://discord.gg/0gfdMUkajXaUVpzF

If @TheOriginalSINe approves of this, I'll also update the README to include this address.

**Comment by bb010g** [comment]
I've thought about doing a Discord or Gitter for 3.CC, but my issue with it would be that it's not easily searchable. We want to be transparent and obvious, and, sadly, for now chat is counter to that. If we do end up doing chat, I'd much rather go with [Gitter](https://gitter.im/) because it's text-only (and thus all discussion is logged) and people don't need extra accounts.

**Comment by jojmaht** [comment]
That's why I think that all important decisions should still have their place in the GH issues and Discord should be used for immediate discussions. (and Gitter's interface sucks but that's my opinion)

**Comment by bb010g** [comment]
Gitter's got the bonus of integrations and the option to get digests of channel activity.

**Comment by ewmb7701** [comment]
Hmm. I just looked it up and I do like the idea of Gitter. Discord and Gitter both have their own merits, though. Perhaps we could have both?

**Comment by bb010g** [comment]
Having both would mean two text chats to keep track of.

**Comment by ewmb7701** [comment]
True. I prefer Gitter, tbh. It seems less social oriented and more appropriate for our needs.

**Comment by bb010g** [comment]
Once you set up the repo chat, it should even PR a badge for you in the README.

**Comment by ghost** [comment]
I feel like Gitter does everything that Discord does, plus the addition of a Project Activity Feed (big bonus, helps keep chat focused on development and less on social).

I think having both could be a good idea. There currently is no real social space for this project (reddit, smashboards, etc). We could have Discord be that. If there was distinction that the Discord chat was for people interested in the project to socialize/shitpost while the Gitter was for development discussion and debate, I think they could co-exist just fine.

**Comment by ewmb7701** [comment]
@Azuran17 My thoughts exactly. I'll set up a Gitter right now.

**Comment by ewmb7701** [comment]
Alright, it seems that the Gitter is working properly. I'll close this issue.
