### ISSUE TITLE
Knuckles Plays Sonic's sounds if Sonic is in the same match.

### ISSUE THREAD

**Issue by Eltrion** [TheOriginalSINe/Project-M-CC#81]
Sonics sounds play if Knuckles and Sonic are in the same match, provided that Knuckles doesn't have an existing sound clip. Most noticeably down taunt, but also a death sound effect, and Victory Sounds.

Proposed Fix: Give Knuckles  proper voice clips and sound effects for all the affected animations.

**Comment by vinegar97** [comment]
Fixed in #351, closing
