### ISSUE TITLE
Knuckles Animation Cleanups

### ISSUE THREAD

**Issue by SuperSandbag** [TheOriginalSINe/Project-M-CC#83]
The following animations have bizarre in-game bugs. While not game breaking, and barely visible in normal play, they are quite jarring when noticed. The strange thing is, I can never find these bugs through BrawlBox, and most of them can only be seen in-game in slower speeds.
- AttackAirLw: At the last frame of the animation, Knuckles' model will spasm. 
- AttackAirB: Same as AttackAirLw, but due to the Allow Interrupt in the PSA, it cannot usually be seen.  
  - Neither of these animation spasms can be seen in BrawlBox, leading me to believe that these are animation oversights in the PSA.
- AppealHi: On frame 102, Knuckles loses the top of his head. This can not be usually seen, due to the Allow Interrupt occurring at frame 99. I fixed this here: https://www.dropbox.com/sh/iotpzsr8633zs8o/AACdgL22FveIawSqmhAIRkGCa?dl=0 (Just take the animations and replace them with the same-named animations in BrawlBox. Both animations are listed towards the bottom of the animations list.)
  - AttackEnd: Same sort of deal as AppealHi, but with an incorrect expression instead. Fixed in the same link. 
  - Edit: CatchWait: Modified to make the animation not look silly with Knuckles' janky mouth movement.
- Wait1, WalkSlow, WalkMiddle, Attack100: On all of these motions, Knuckles' right hand spasms at certain frames. 
- AttackLw3: For a single frame in the middle of the attack, Knuckles' left leg flies upward.
  - For both the hand and foot, neither error can be found in BrawlBox. I think this might be due to scale changes in the MotionEtc during certain frames, but don't quote me on this quite yet. 

I would fix these problems on my own if I could, but I still have a long way to go before I can do stuff of this caliber on my own yet. All the same, great work, folks!

**Comment by ghost** [comment]
Hey, do you think you could split this issue into one issue per problem? I think it would help tracking progress and make sure none of these fall through the cracks. The only ones I have already seen issues created for are the hand spasms on Slow and Middle walk. Everything else I think deserves it's own issue. Good work!

**Comment by SuperSandbag** [comment]
Oh wow, I wasn't quite sure my voice would be heard here, to be honest! Glad to know I'm getting noticed!

About the issue sorting, do you want me to make an issue for every animation error, or every type of animation error? It seems like the remaining two problem types I couldn't fix would be solvable by the same means across the animations they infect, but I want to do what would be the most convenient for you guys in an addressing standpoint. Either way, I have no problem writing out any animation error I find in whatever format you want.

Thanks for letting me help out! I hope to be of more service down the road! 

(On a semi-unrelated note, I have started messing around with making one of Knuckles' taunts added from the other Knuckles hack to look more P:M-y (the three punch one, to be specific). I'm not sure if you need this help yet, or even if you're already getting this covered, but I'm more than ready to help fix up other animations if you need it. Granted, I'm still a novice at 3d animation, but I hope to be of service all the same.)

**Comment by bb010g** [comment]
We'll take any improved animation work for the newcomers.

**Comment by SuperSandbag** [comment]
Will do! I will try to give you folks the best animation work I can offer!

**Comment by bb010g** [comment]
This needs to be updated to match the new Knuckles leak.
