### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#85]
It's kinda strange all characters not having a new battle portraits. Here are a few suggestions,
.Knuckles and Lyn are in All Stars Mode.
.replace diddys orange outfit (newest addition too PM) with a Donkey Kong Jr. Outfit)
.Give Isaac a new voice and his grab and neutral special be close range
.Add all N64,Melee,and Brawl Stages
. By pressing A in the stage menu when using a wiimote (without the nunchuck) it loads the secret stages (N64 Hyrule Castle and N64 Peach's Castle
That's all I have but this is a great Project :)

**Comment by ghost** [comment]
As a note, Diddy's new orange outfit does reference something. in Donkey Kong Country Returns, Super Kong is a guide that completes a level for you. When Super Kong(Who is a DK recolor) is in use, Dk is replaced by him, and if he reaches a DK barrel, Diddy is replaced by "Super Diddy", which is the orange recolor.

**Comment by Darquezze** [comment]
Oh, I didn't know that. Then lets keep it in xD

**Comment by JCOnyx** [comment]
And to add on, some of those suggestions seem to deviate from this projects main objective, which is to include the assets which were in the leaked builds and finish Knuckles and Lyn.  Adding all of the melee, 64, and Brawl stages seems like a completely different project.

**Comment by Darquezze** [comment]
@JCOnyx you do got a point :/ Reason I added the all stages from N64, Melee and Brawl stages was because some stages a loved from Melee and Brawl were not in PM (Example: Mario Kart and Mushroom Kingdom 2) PS a project called Smash Bros Legacy has 3 stages per slot (cool concept if u ask me)

**Comment by JCOnyx** [comment]
Those are good points and a reason to search for good custom PM builds.  But this project is just a "base" project in a way if you understand.  We don't want to deviate too far from 3.6 with all the additional content.

**Comment by ghost** [comment]
This isn't an "issue" per say as it is a list of random suggestions. Also character select portraits are covered in another issue. This should be closed.

**Comment by ewmb7701** [comment]
Hey, thanks for taking interest in the project! However, as others have pointed out, some of your suggestions aren't really related to the project goals. I forgot about the All-Start mode, so thanks for pointing that out! Closing the issue.

**Comment by Darquezze** [comment]
@Azuran17 My mistake, I'm new to github so I'm not aware to most things and sorry to everyone else for wasting your time

**Comment by ghost** [comment]
@Darquezze No worries man, don't feel bad. The more people trying to help the better. If you have some free time, see if you can root out some bugs and report them here :+1:

**Comment by Darquezze** [comment]
@Azuran17 I do know some bugs but may have been said already.
.Knuckles has Sonics voice when fighting Sonic
.Lyns Portrait art doesn't match her black outfit (also the skin is different too on some places on the same alternative)
And just another suggestion, I rather use thedudemonns version of Lyn.
It's less buggy than the one currently being used. while using down b when in the ground and near an opponent, it attacks then with a slash (which is better in my opinion) Oh and that moveset also references something from Fire Emblem. He said there's a red trail when using a strong attack. I'll give u a link to his vid if u want

**Comment by bb010g** [comment]
@Darquezze If you want a bulleted list, do this:

```
My previous paragraph

- List item 1
- List item 2

My next paragraph
```

Also, for any future bugs or suggestions, search around in issues first. If you don't find them, make a new one for each bug.

**Comment by ghost** [comment]
All of those have been mentioned already

**Comment by ghost** [comment]
@Darquezze thedudemonn's edit of Lyn is the one that is used here.

**Comment by Darquezze** [comment]
@Rage17 his newest release? (I'm downloading the one uploaded today so I'm not aware yet)

**Comment by ghost** [comment]
today's version of this completion build, yeah.
