### ISSUE TITLE
My Music errors

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#86]
The one I noticed off the bat is Bad Mario, I'm sure there's others
In-game it says "Bad Mario (by Phonetic Hero)"
My Music menu says "Warioware Inc. Medley"

Fix: Revert music listing to 3.6 full

additionally, there's inconsistency in the PMDT's naming scheme w/ the 64 tracks if you wanna do something about that

"Peach's Castle (Super Smash Bros. 64)"
"Yoshi's Island 64"
"Metal Mario (Super Smash Bros.)"

**Comment by ewmb7701** [comment]
Fixed this in a recent commit. f2f2ad3b19152fc21c05a9e9e6bf6443ebdf72a9
