### ISSUE TITLE
Transparency on Strap Screen Version Number

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#88]
text has black background

also can I recommend the ESRB warning says something along the lines of "This build is not tournament-legal, please read the README"

**Comment by bb010g** [comment]
We don't need a tournament legal disclaimer. People can use this build wherever they want to use it. We may not recommend using it at tourneys, but we don't need the build to say that.

**Comment by Jeelix** [comment]
I actually just fixed this. I'll do a pull request soon hopefully; I'm still setting everything up.

**Comment by ewmb7701** [comment]
Merged the pull request. Closing.
