### ISSUE TITLE
Kirby's warlock punch

### ISSUE THREAD

**Issue by CharlesAMiller** [TheOriginalSINe/Project-M-CC#90]
When Kirby absorbs Ganondorf and then attempts to use his neutral b, the animation does not complete and Kirby is unable to move.

**Comment by ghost** [comment]
Are you using the latest project build, based on 3.6, not the leaked dev version? I can't reproduce this issue.

**Comment by oXMugetsuoXo** [comment]
I also have problems with kirby freezing after ganon absorb.

**Comment by ewmb7701** [comment]
I'm working on fixing this right now. I think it's a codeset issue, but I am not sure.

**Comment by ewmb7701** [comment]
I believe I fixed this issue. I had to delete all the Kirby files in his folder, and replace them with the 3.6 build. It's odd, though. I shouldn't have had to do that, as the affected files were from the dev build. I'm worried about the integrity of the other character files. Closing the issue.
