### ISSUE TITLE
Knuckles' results screen animation

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#92]
I noticed that there is one very awkward animation for Knuckles at the results screen that ends with him having his back facing towards the screen. I'd like to suggest that you guys change it into one where he does a digging animation similar to in Sonic adventure and makes that "hoda hoda hoda" sound he does in that game as well as a homage to it. Then he just stays dug underground instead of coming back up, like how Meta-Knight has an animation where he teleports away.

PS: I've also been told that Knuckles using the voice he has in Sonic X, so if you guys are looking for more lines to get for him, that show would be a good place to start.

**Comment by ghost** [comment]
I believe this issue is covered by #21 please comment there if you have suggested fixes.

**Comment by ghost** [comment]
I think this can be closed

**Comment by ewmb7701** [comment]
Duplicate issue, closing.
