### ISSUE TITLE
New alt stage GCT and gameconfig.txt broken

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#93]
The new gct for alternate stages is lacking codes from before, and yet gecko throws an error saying that it has too many codes.

**Comment by ewmb7701** [comment]
I can't seem to reproduce this error. Do you have the gameconfig.txt on your SD card? Even if you load your codes from the USB you still need it at the root of you SD card.

**Comment by ewmb7701** [comment]
Going to close this issue, as I was unable to replicate it, and using the most recent build it worked fine.

**Comment by ghost** [comment]
It seems that I had the terrible luck of downloading the fix AS you were putting it up. Weird.
