### ISSUE TITLE
Revert Knuckles's Entry Animation?

### ISSUE THREAD

**Issue by Hellraz0r** [TheOriginalSINe/Project-M-CC#97]
This is more of an opinion thing I guess. I really dislike the animations added from the recent update since they're extremely low quality but the entry animation is easily the worst, especially if Knuckles spawns on a platform at the beginning of a match. Cloning Sonic's animation for Knuckles should be fine, similar to how all FE characters have that glowing rune ring thing upon entrance. At least until we have a quality, unique animation, such as gliding in.

**Comment by ghost** [comment]
I'll fix the platform thing with the entry animation once I get back to my house at around 6. Just wait till then.

**Comment by ghost** [comment]
https://www.cubbyusercontent.com/pli/EntryL.chr0/_4d838aea5b004dde94a2883cb0c589f7

**Comment by bb010g** [comment]
Duplicate of #12. Closing.
