### ISSUE TITLE
Lyn: Neutral B Frame Data

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#98]
There seems to be some consensus that Lyn's arrows in the dev build were not in a finished state leading the move to be broken, similar to her B-air. This is one of the few cases in this project that calls for the need to adjust frame data.

Tested on FD, uncharged does 7 damage at point blank and 13 at full stage length. Fully charged does 15 at point blank and 21 at full stage. For reference, Link's Bow does 5 damage uncharged, 15 damage fully charged, and damage doesn't scale with distance. Lyn's arrows also fly faster than Link's and have a larger range.

The issue seems to be, as in most cases, an imbalance between risk and reward. It takes little effort/skill to land an off stage arrow and doing so can net a kill in too many cases, ie at low %'s

I think it can be fixed without altering the move's functionality or purpose, but just by tweaking the numbers. As I've said before, I think sticking as close to the PMDT's design is the best route for the project.

Suggested Fix: The move should be made harder to land, and to a lesser extent, the damage should be scaled back (it is a tad overbearing).
- The main change I'd suggest is making the arrows slower by a substantial %. The exact amount would require testing but ~15% sounds good as a back-of-the-napkin estimate. This makes landing the shot at long range more difficult and justifies the move's increasing power as shot distance increases.
- Add 3-5 frames of endlag to the move. This increases risk for players who use the move offstage in order to increase their chance of landing the shot. This also has the twofold effect of discouraging using the move to camp. With more endlag, grounded spam of the move is less safe, so players have more incentive to shorthop when using the move in order to cancel the endlag. The aerial version has a sharper downward angle and therefor has a much shorter range, making it less viable for camping.
- Finally, bring the damage down across the board by ~2%. That would change it to 5-11% uncharged and 13-19% at full charge. Again, the exact number would require some playtesting but I believe this would keep the move from gimping low % opponents. I don't think a substantial amount more than 2% would be needed as the other nerfs increase the difficulty/risk of the move and if a player manages to land an offstage shot with this they should be rewarded for it.

**Comment by somealternateaccount** [comment]
I feel like moving the arrows to a much more dedicated gimping/last-damage-in-a-combo tool would be a better design to reduce their power and leave room for her other moves.

My idea is to reduce the damage, KBG and BKB massively, probably to around 75% of Link's, but retain most of the current speed. The arrow can be sent downwards in the air, so it can be aimed below the stage to nail opponents who are recovering from far away.

This would be an even stronger nerf than the original proposal.

**Comment by ghost** [comment]
Hm, I think both changes are potentially good ones. For your idea, I still think adding extra frames of endlag would be beneficial.

So basically the two potential designs are a slow, slightly less heavy hitting version (mine) or a just as fast, but weak gimping version ( @somealternateaccount 's).

Anyone else have input on this?

**Comment by JCOnyx** [comment]
I feel like a couple more grounded starting frames (around 2-4, aerial remains the same) and an additional 2-4 frames of endlag, with a 2-3% percent potential damage decrease should be enough. They're a zoning tool and should be kept as such.

**Comment by ghost** [comment]
A gimping tool would be nice, but I thought we weren't altering the new character movesets until after all the bugs are worked out.

**Comment by Eltrion** [comment]
so far I like the fast gimping arrow idea the best. I will throw my voice in agreeing that they need substantial nerfs.

**Comment by Hellraz0r** [comment]
Agreeing with @JekyllMD 

Regardless of my similar opinion that the arrows need tweaks, changes to character balance should be bottom priority. Functionality is most important; let's refine animations and work out all the kinks in all characters in actual gameplay.

**Comment by ghost** [comment]
So far it seems like these changes for the new characters have been suggested. Did I miss any?

http://www.filedropper.com/suggestedchanges

**Comment by Hellraz0r** [comment]
...How about a Google doc?

**Comment by ghost** [comment]
Sorry about that, totally spaced that I could make a URL to share

https://docs.google.com/document/d/1urDBQMIz07ncU7H2IjKn3ffx7l_mepRT4ZJy7WRZ-ZY/edit?usp=sharing

**Comment by ghost** [comment]
@JekyllMD You are right. This should be low priority. It's only getting all this discussion now because it is unbalanced to the point of being a bug, like Bair having no landing lag.

**Comment by ghost** [comment]
I've played around with this some more.

No matter what else, there definitely needs to be added endlag to the move. We haven't yet considered the fact that this move can be used as a stall/recovery. Lyn is able to get off three shots off stage and still be able to recover. That's kinda ridiculous, even if this WASN'T a ranged kill move.

Additionally, I'm tending to agree more with an overall nerf to the damage in lieu of projectile speed. The % at which an opponent gets put into heavy hitstun is too low right now for such a fast move.

When we get around to working on this, I propose as a first pass, something along these lines. 1 frame added startup. 5 frames added endlag. Cut the damage down to 4%(point blank) - 8%(FD distance) uncharged and 8%(point blank) - 12%(FD distance) fully charged.

The 6 extra frames added to the move should help prevent on stage spamming and allow at most 2 offstage shots. Additionally, from my testing, I found that 8% from that move is enough to put an opponent into heavy hitstun when they are around 70%. What that means is that with these changes, the move will still act as a hard gimp in 2 situations:
- Lyn nails an uncharged shot from about the distance of FD's width and the opponent is over 70%.
- Lyn nails a fully charged shot at any distance and the opponent is over 70% (this is functionally similar to how Link's bow works)

**Comment by bb010g** [comment]
3f2e31c changed:

> Arrows:
> Non charged
> Close range: 3%
> Max range: 8%
> Charged
> Close range: 7%
> Max range: 12%

Credit to @Azuran17.

**Comment by ghost** [comment]
Changelog is incorrect. switched the 7 and 8 in your comment.

**Comment by ArtfulHobbes** [comment]
@Azuran17 changelog was indeed correct. I tested from the very ledge of FD to the other ledge of FD and arrows did 8%.

**Comment by ghost** [comment]
@ArtfulHobbes Hm. I must have messed up my recording of the data then. No matter, its a minute difference. The move will probably still need changing anyways after people play around with it.

**Comment by SzionBlue** [comment]
Is it possible for us to agree that the knockback should decrease slightly and endlag increase slightly??

Im really hoping to submain this character along with whats over there in my profile picture..(just made an account today, idk how that picture was there automatically. whatre the odds of that??)

**Comment by ghost** [comment]
@SzionBlue are you up to date with the latest rendition of the move?

For the rest of us. How does the move currently feel? I believe the endlag of the move should still see a marginal increase before we close this issue.

**Comment by somealternateaccount** [comment]
Pretty sure this has been resolved following the changes to Lyn's neutral b. Testing needed to verify the changes are as listed in the commit, and if they are accurate then this issue may be closed. In the future more discussion would ideally take place on an issue regarding a new character's balance.

**Comment by SzionBlue** [comment]
Was a bit late to the party but couldnt find anything saying changed X or Y until later...the current rendition of lyn's Arrows seems fine to me. No crazy KB or damage, retains the same pressure and speed of use. 

Nice work

**Comment by ghost** [comment]
From Discord chat, I believe the endlag is still being slightly increased before we close the issue. This is to address grounded spamming. I think 5 or 6 frames was the suggested change.

**Comment by bb010g** [comment]
Could someone check to see what Lyn's endlag is so we can finish this up?

**Comment by ghost** [comment]
@bb010g Atm the endlag is 53 frames.

**Comment by bb010g** [comment]
I'm for leaving her endlag where it is at right now, and seeing how it works out for a while. IMHO each character has a pretty good way to avoid arrow spam pressure.
