### ISSUE TITLE
Knuckle's Spin Dash Too Slow/Choppy

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#99]
It seems to me that Knuckle's Spin Dash has room for improvement, with the need of more swiftness, fluidness, (and more control).

**Comment by ghost** [comment]
Is this a request for an animation edit? Could you please specify changes you'd suggest?

**Comment by bb010g** [comment]
I think we should leave spin dash where it is right now. This is a request for a buff. If it ends up being complete suck after a couple of months, then we can deal with it.

**Comment by ghost** [comment]
If that's the case, that you are requesting a balance change/buff then I'll have to agree with @bb010g and this should be closed.

I think there should be a disclaimer in the readme about this being first and foremost a bugfix patch and not a balance patch.

**Comment by ghost** [comment]
Yeah, I guess it is. If you use him, though, you could see what I'm talking about. I understand though.
